### ISSUE TITLE
Create "bootcamp" training template

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#104]
We want to create a template for "bootcamp" training sessions. This template will be created according to design requirements which will be set by @CervenBWI and the training department.

**Comment by adios113** [comment]
**First update**
* Map: Chernarus
* Concept picture drawn on the map with ACE's Map Markers.
* http://steamcommunity.com/sharedfiles/filedetails/?id=601802710

**Comment by adios113** [comment]
**Update No. 2**

1. A template "room" inside a hangar has been made, which will be copied to other hangars. 
 * Chairs, big billboard, which will be used as a place to show pictures. (Controlable by the Training Officer) http://steamcommunity.com/sharedfiles/filedetails/?id=604803400 http://steamcommunity.com/sharedfiles/filedetails/?id=604804629
 * Small room, for other smaller billboards with additional material in the given topic.
 * Practical area - in case of formations, I placed a bunch of cons and flags which will have custom colors, to represent specific fireteam (HUD Color)

**Comment by adios113** [comment]
**Update No. 3**

**Formations Hangar:**

* Objects: 100%
* Images: 0%
* Scripting: 10%

**Medical Hangar:**

* Objects: 70%
* Images: 0%
* Scripting: 0%

**Convoy Hangar:**

* Objects 80%
* Images: 0%
* Scripting: 100% (none required)

**Radio/Misc Hangar**

* Objects: 80%
* Images: 0%
* Scripting: 30% 

**Firing Range:**

* Objects: 100%
* Images: 0%
* Scripting: 0%

**Killhouse:**

* Objects: 40%
* Images: 100% (none required)
* Scripting: 0%


As you can see, I'm slowly finishing with the object placement, total is around 90% and total object count for now is ~1200. Don't worry, the objects won't affect the performance much. In Arma it was  AI mostly which was causing FPS Drops. I'm in talks with Abel, to seek for help with the images for all the signs, billboards and so on, asked as well Lord Cavac about his photoshop skills, waiting for answer, as I  speak now. Below to do list of scripts required:

* Firing Range Management GUI.
* Killhouse Script (reset, timer, scoring system)
* Firing Range Script (scoring system, random target course)
* Medical Simulation Script with randomization for wounds.
* Teleport on random location in Chernarus for compass/map training.

The list may grow.

**Comment by adios113** [comment]
Bootcamp will be ready before the next meeting :). Slight delay from my side, caused by my upcoming LOA.

**Comment by adios113** [comment]
List of Images:

> 1.Formations: (Introduction Image)
> 
> - Line
> - Wedge
> - Column
> - Staggered Column
> 
> 2.Convoys (Introduction Image)
> 
> - Convoy Formation while driving on a road (gunner facing)
> - Convoy Hold Formation (with soft dismount, gunners in vehicles, covering their areas)
> 
> 3.Medical (Introduction Image)
> 
> - Bandage Chart
> - ?
> 
> 4.Radio/Misc (Introduction Image)
> 
> - Radio Frequency Chart (same as on the templates)
> - Image from the radio with button description (AN-152 example)

**Make sure, all images have BWI's logo in some way.

If you think, we are missing something - feel free, to add it here.

**Comment by abelarno** [comment]
Putting the images that are done here. Please let me know if you see an error.

1.Formations: http://www.imgdumper.nl/uploads9/56bb8f8ea64ac/56bb8f8e92e8b-main_formations.png

Line: http://www.imgdumper.nl/uploads9/56bb8f9f5139e/56bb8f9f404b2-line.png
Wedge: http://www.imgdumper.nl/uploads9/56bb8facec43e/56bb8facb48aa-wedge_poster.png
Column: http://www.imgdumper.nl/uploads9/56bb8fcad2576/56bb8fcac2eee-column.png
Staggered Column: http://www.imgdumper.nl/uploads9/56bb8fe579b4f/56bb8fe56a088-staggeredcolumn.png
Diamond
Echelon

2.Convoys: http://www.imgdumper.nl/uploads9/56bb900496a37/56bb900485b3f-main_convoys.png

Convoy Formation while driving on a road (gunner facing)
Convoy Hold Formation (with soft dismount, gunners in vehicles, covering their areas)

3.Medical: http://www.imgdumper.nl/uploads9/56bb9029f0042/56bb9029dc211-main_medical.png

Bandage Chart
?

4.Radio/Misc: http://www.imgdumper.nl/uploads9/56bb9049415d6/56bb90492e1a2-main_radio.png

Radio Frequency Chart: http://www.imgdumper.nl/uploads9/56bb9068d2626/56bb9068bca31-radio_freqs.png
Image from the radio with button description: http://www.imgdumper.nl/uploads9/56bb9086b3939/56bb9086a1e12-radio_button.png
GPS Grid

**Comment by ShiFoo** [comment]
I really like the design, Abel. Very nice. Regarding the radio frequencies: Logistics and Medical are combined on 101. only thing that i noticed for now.

**Comment by Fourjays** [comment]
Look good. I think the formations should have 10 people though, same as our squads.

On the radio one, are you sure the lines are going to be thick enough and clear enough for the size it will be appearing at?

**Comment by adios113** [comment]
It is thick enough. The billboards are pretty big: http://steamcommunity.com/sharedfiles/filedetails/?id=620927999

**Comment by Fox87** [comment]
It looks really really great guys. Awesome design work on the pictures, and really nice watching the progress on the bootcamp.

**Regarding Ifu**: I agree in Log. and Med. is on combined 101.
**Regarding Jays:** I do agree on changing the pictures to a 10 man squad. Only cause that is what we have currently. I also think that was you were ment to do, maby just forgot the RTO :)
I don't see any idea of changing size of the lines. I think they are fine as they are now.

Overall; I really like this guys :)

**Comment by abelarno** [comment]
Like fox assumed, totally forgot the RTO. Will add it in.

**Comment by adios113** [comment]
**Update No. 4**

Bootcamp is almost finished. Waiting for the rest of the images and we will be good to proceed towards finalization. Because of the upcoming Arma 1.56 update and a big modpack update, I decided to only make sure we have all the stuff we need. Features like Killhouse, Firing Range GUI, scoring systems will be added after the update to avoid any possible errors, but still both features are functional as we speak.

**Comment by adios113** [comment]
Medical Vitals, Morphine, Epi,
Micro DAGR, LR Radio pictures
Medical Script Error
Scoring System Error

**Comment by Fox87** [comment]
Spawn flag: USA flag to NATO flag

**Comment by Fourjays** [comment]
Emphasis on QuikClot's role (bandaging wounds when Corpsman not likely) as it isn't obvious from the table.

**Comment by adios113** [comment]
Question:

Are we sure, we want to release the bootcamp in the upcoming week, or do we wait for the modpack update?

**Comment by Fox87** [comment]
I dont know any about the tech. reasons. 
Therefore let's stick with the upcoming week.

**Comment by Fourjays** [comment]
Depends on when the modpack is able to be released, but it would be unwise to release the bootcamp until the contents of the modpack is known. Otherwise it is potentially broken soon after release.

**Comment by adios113** [comment]
http://imgur.com/a/OkJKV

LR Radio Image
Medicaments Image
Vitals Image

**Comment by ShiFoo** [comment]
Morphine is not available for riflemen anymore. They only have bandages. As a general remark, keep it unspecific about these things in case we are changing loadouts in the future (so we dont have to adapt the text aswell)

**Comment by Fourjays** [comment]
I've just updated the Field Manual as I realised it was out of date, so please use the newest information.

Also, please do not reference the ACE ranges. These ranges merely relate to the non-medical indicators and shows why they can't be trusted in any kind of diagnosis (a "normal" pulse could be 46, which is not a good time to use a morphine).

A safe pulse will be between 70 and 90. A safe blood pressure is between 100/60 and 120/80.

**Comment by Fox87** [comment]
_Oh yes I forgot, thanks Ifu. 
Also a good idea to keep it nonspecific._


Lets add:

1. 
**Morphine:**
Morphine is used to reduce heavy pain. 
As it reduces the heart rate, morphine should only be given to a patient once and never to a casualty with a low heart rate.

2.
**Epinephrine:**
Epinephrine is used to wake unconscious casualties. 
It will also increase the heart rate and blood pressure, and as such should never be given to a patient with a high heart rate or blood pressure. Avoid giving an epinephrine soon after a morphine, as it may not have the desired effect.

3.
**Checking Vitals:**
Blood loss and the use of medication, will both affect the heart rate or blood pressure of the patient. The vitals can be checked on either the arms or the head. Only Corpsmen and Combat First Responders are able to get an accurate vitals reading.

A patient's pulse should be kept within the range of 70 to 90, and blood pressure between 100/60 and 120/80.

**Comment by abelarno** [comment]
Dont forget the right font Adi! Arvo http://www.fontsquirrel.com/fonts/arvo

(Yes im always watching)

**Comment by adios113** [comment]
thanks, thats the only thing i needed.

**Comment by adios113** [comment]
Bootcamp will be ready to release couple of days after the modpack update.

**Comment by Fourjays** [comment]
There are a number of issues with the bootcamp as it stands that need to be addressed.

**Convoy holding**
- Front/rear vehicles not blocking the road, not providing interior cover.
- Left/right vehicles angled too strongly, not providing interior cover.

**All formations**
 - Indicates squad leader is point (can be anyone).
 - Indicate fireteams need arranging specifically (they're not).
 - Point style does not convey sector coverage well.
   - If we’re going with ShackTac style, all points should be forward so it matches what players will see (familiarity).
   - If we’re conveying sectors, we shouldn’t use ShackTac to represent it and use a style that indicates the sector to be covered (e.g. a cone).
 - No rear or flank coverage indicated.
   - Left/right edges should check flanks.
   - Rear covered by rear most man in formation.
 No information on strengths/weaknesses/uses of the formations.

**Echelon, Wedge, Staggered Column, Column**
 - Weird fanning where units near front are pointing more forwards than those at rear.

**Staggered Column**
 - No urban variant of the staggered  column demonstrated.

**Column**
 - Nobody is centered in the column (slightly staggered).
 - Why is the squad lead on point but RTO in the middle?

**Diamond**
 - Do we really want to include it?
  - Can’t find any information on this as an regular infantry formation.
  - Only as a SWAT corridor clearing or a police riot control formation.

**Other**
 - No information on holding a 360’ or 180’ (more important than Diamond).

**Radio**
 - Include a board with basic terminology and/or example conversations.

**Comment by Fox87** [comment]
**Convoy holding**

1. I agree, the vehicle needs to be blocking the road. 
2. vehicle is angled correct, no need to change that.

**All formations  **
I agree in the most FourJays just said. So lets have all the guys pointing in the directing of movement. Keep the SqL as it is for now, and the instructors will tell about the sectors to cover orally.

We dont need a urban variant of the staggered column, since this is the bootcamp and not anvanced training.

_Nobody is centered in the column (slightly staggered)._ This will change, then we are making all face in the directing of movement.
_Why is the squad lead on point but RTO in the middle?_ Agree, needs to be changed.

**Comment by Fox87** [comment]
**Convoy holding**
1. I agree, the vehicle needs to be blocking the road. 
2. vehicle is angled correct, no need to change that.

**All formations  **
I agree in the most FourJays just said. So lets have all the guys pointing in the directing of movement. Keep the SqL as it is for now, and the instructors will tell about the sectors to cover orally.

We dont need a urban variant of the staggered column, since this is the bootcamp and not "anvanced training".

_Nobody is centered in the column (slightly staggered)._ This will change, then we are making all face in the directing of movement, i guess?.
_Why is the squad lead on point but RTO in the middle?_ Agree, needs to be changed!

**_Diamond_** Yeah, i agree on that we can remove this from bootcamp, and paste into the advanced training.

We need a formation on 360’ as jays says, agree. We can maby use the dimond sketch?

_Include a board with basic terminology and/or example conversations._ I would love to see the terminology and a small example. 
http://blackwatch-int.com/field-manual/appendix/radio-terminology
The example might be:
_“Jackal, this is Templar.”
“Send it Templar.”
“We require you to move into the town and cover the road to the east. How copy?”
“Solid copy.”
_

**Comment by TheGrandVizier** [comment]
> Rear covered by rear most man in formation. No information on strengths/weaknesses/uses of the formations.

^Not correct, in my opinion. One man before last needs to be the rear glancer / observer.
In case the last guy in the formation goes down, if he is the one observing rear, no one will know and he will be left behind.

**Comment by Fourjays** [comment]
@Fox87 The staggered column sector coverage is moot if the indicators show direction of travel and sectors are explained instead.

@TheGrandVizier From recent research I've done, it is the rear most man in a column who checks the rear because he has the clearest view. In a wedge it is either rear most, second to last, or second from point (information varies).

@Fox87 Regards the convoy, my concern with a 45' angle on the sides you are not effectively able to use the hood as cover in a firefight compared to the 35' angle you've previously taught.

**Comment by Fox87** [comment]
Niko: If the rear guy in a formation goes down, you WILL hear the crack and/ or the hit. So I also says the last guy are covering the rear.

Jays: I did not see the convoy as a 45¨, but if that is I also agree in it is angeled a bit mutch. Rather 35¨ like Jays said.

Regarding the indicators then moving in a formation. 
How about having a small arrow pointing in the direction of moving, and a "watermark" that is showing a approx location of the covering secters. (Look an example in the link)
http://i.imgur.com/Fv98KJC.png
In this example, the guy are moving forward in a column and has a secture to the left side.  
No need to tell them "You need to watch the secture at berring 40¨" Couse the field of view will be way more then one degree.
The main idea with the slight provocative text if- We need to keep it simpel, make it easy to read and remember, and make it practical insted of theoretical. 
(Yes I know the picture is well made, thanks)

Also I would like if we can have:
Convoy front takes a left turn - **Second in a column is taking the left also.** So we can have it consistent.

**Comment by TheGrandVizier** [comment]
I think convoys and sides of convoys and who pulls over on what side should be a situational thing.
For example:
Lead blocks road.
Second vehicle takes left.

**Comment by Fox87** [comment]
_By doing this we will cut essential time of, due to all know there task._
_The gunner will aim at the same direction as the vehicle._

This is from a session summery (http://blackwatch-int.com/forum/training/session-summary-june-29th-ied-convoy)
And I still have my claim. Think about having around 10 cars that needs to alternately take sides before they can make the hold. Compared to having all know there respected side!
Time is of the essence then we har doing a hold!

**Comment by Fourjays** [comment]
@Fox87 The best way to indicate the sectors a person should be covering is via "field of view cones" (http://i.stack.imgur.com/ESaz3.png). It's a common way of depicting where a person is looking in games, so is instantly recognizable as depicting that in this situation. After a lot of iterations (including ShackTac points and "arm" styles) it is what I ended up with for the ones I designed for the field manual (https://www.dropbox.com/s/ynmmr9cud8fsio8/column-diagram.png).

**Comment by Fox87** [comment]
Okay that will work for me. 
Lets go ahead and make the formations pic. with the "field of view cones".

**Comment by Fourjays** [comment]
The bootcamp should also incorporate information on the ShackTac HUD and how to use it to keep good spacing (i.e. middle ring or further is good, inner ring or closer is bad).

**Comment by TheGrandVizier** [comment]
+ Color code? Orange = TOO DAMN CLOSE!

**Comment by Fox87** [comment]
Sounds like a good idea. 
Lets add following after formation.
Green is a optimal distence to the next player (Middle ring), and red is to close/ far! (Inner and outer ring)

**Comment by adios113** [comment]
I got couple of points on this...

1. Abel is not here anymore, so there's no one who can do new images - its too much for me, I can edit some of them but i cant complete all the stuff you listed AFTER it already got approved.- i just don't have much time following my hospitalization and stuff attached to it.

2. We went trough all the images during the preview, everyone accepted it as they are with some smaller adjustments and i remember that the bootcamp was supposed to focus on Sign-offs stuff and mostly the basic terminology, with more complicated stuff being explained by the training guy during the course. I am really surprised that you want to make changes now, knowing Abel is gone and im about to go to the hospital.

**Comment by Fourjays** [comment]
@adios113 Simply put, it is important we get the bootcamp right and that it contains all elements of the sign-offs. Otherwise we just continue the issues we've had before. If necessary others can make adjustments while you are absent.

I've made updated images with the sectors displayed as discussed with @Fox87:
- Column: https://www.dropbox.com/s/1c12ombrmfn60c5/bootcamp-column.png?raw=1
- Wedge: https://www.dropbox.com/s/kah6usok9sadtg8/bootcamp-wedge.png?raw=1
- Echelon: https://www.dropbox.com/s/rkgm3ylmy8lcn9p/bootcamp-echelon.png?raw=1
- Line: https://www.dropbox.com/s/qj4ep1ikv9jpnlb/bootcamp-line.png?raw=1
- Staggered column: https://www.dropbox.com/s/kze7spffmfkwli6/bootcaml-staggered-column.png?raw=1

Corrected the convoy hold:
- Convoy hold: https://www.dropbox.com/s/sy0e4y1piiwp1x1/bootcamp-convoy-holding.png?raw=1

New diagram for spacing:
- Spacing: https://www.dropbox.com/s/3togwmyl82yknaj/bootcamp-spacing.png?raw=1

Let me know if you need help with making others, @Fox87 and @adios113.

**Comment by Fourjays** [comment]
Further tweaks as requested by @Fox87.

- Column: https://www.dropbox.com/s/ttlz2v6aa9ll97i/bootcamp-column-v2.png?dl=0
- Convoy hold: https://www.dropbox.com/s/gy3mvx2ztx886eq/bootcamp-convoy-hold-v2.png?dl=0

**Comment by Fox87** [comment]
Need two more pictures:

1: Terminology is needed on the 1. pic.
- From the Field Manuel- Basic.

2: An example will be needed on the 2. pic.
- The example will be:
_“Jackal, this is Templar.”
“Send it Templar.”
“We require you to move into the town and cover the road to the east. How copy?”
“Solid copy.”_

**Comment by Fourjays** [comment]
Had to split radio across three images, couldn't fit it on one or two without it being too small:

- https://www.dropbox.com/s/stiy66sz0s3u7em/bootcamp-radio-term-pt1.png?raw=1
- https://www.dropbox.com/s/y23x2gelc9ekhmr/bootcamp-radio-term-pt2.png?raw=1
- https://www.dropbox.com/s/oa8ddq5b1yxffjz/bootcamp-radio-example.png?raw=1

**Comment by Fourjays** [comment]
Corrected the examples image, had some errors:

**Comment by Fourjays** [comment]
Removing milestone as this will be release individually.

**Comment by adios113** [comment]
Bootcamp will be ready for FINAL release for the meeting, pending reviews, possible hot fixes and to be released officialy if accepted after the meeting.

**Comment by Fourjays** [comment]
Additional images as requested by @adios113: 
https://www.dropbox.com/s/e0etikqqv66224b/bootcamp-medical-medicine.png?raw=1

**Comment by Fourjays** [comment]
Updated further with strong emphasis on important elements as suggested by @TheGrandVizier: 

- https://www.dropbox.com/s/9hsxzmdyalima4r/bootcamp-medical-medicine-v2.png?raw=1
- https://www.dropbox.com/s/eptwjlbc27uh9ob/bootcamp-medical-vitals-v2.png?raw=1

**Comment by adios113** [comment]
I got 2 weeks left. If there's something that still needs to be done, now it's the time.
I am still waiting for input.

**Comment by Fourjays** [comment]
Some problems with the bootcamp that need addressing:

- Replace cones/flags for formations with moveable prisoners.
 - Cones/flags are buggy (fall over/get stuck in air).
 - Can't indicator sector coverage right now (should be possible with prisoners).
- No medical gear added when selecting Corpsman or CFR at the medical hangar.
  - Need the gear to do the tests.
- Remove cones/flags from all hangars.
- Remove inventories from all vehicles.
- Remove inventory from armory box.
- Remove facewear box at spawn.
- Move armory/scopes boxes to firing range.
- "Radio terminology 2" appears twice (one should be 3).
- "Compas" spelt wrong on teleport pole.
- Zeus only works for the first slot/player.

**Comment by adios113** [comment]
Update, Bootcamp RC2
Changelog:

- Bootcamp has now its own slot structure, containing 4 Instructor Slots and 24 Trainees slots.
All soldiers wear USMC Woodland camouflaged uniform with Booniehats for Instructors and standard USMC caps for trainees. No one is spawning with any kind of gear besides those two items in the beggining.

- Cones and Flags inside the medical hangar have been replaced with movable USMC Woodland camouflaged soldiers, acting as prisoners. Bootcamp Instructor is and will be made responsible for any harm done to them during the course.

- Medical gear will be added to players, who use the "Become CFR/Corpsman" action and will be reloaded if a player uses it again. Action utilises the Field Manual and its Gear Regulation for both roles.

- Cones and Flags have been removed from the other hangars.

- HMMVS behing the Convoy Hangar now spawn without Cargo.

- Armory Box at respawn spawns now without Cargo.

- Facewear box has been deleted from the Bootcamp.

- Accessories Box has been deleted from the Bootcamp and replaced with VAS inside the Firing Range Area.

- "Radio Terminology 2" duplicate has been renamed to "Radio Transmission Example"

- "Compass" is now spelled correctly

- Player receives a map and a compass after moving trough the "Compass Training Teleport". Additional Gear will be then removed upon returning to base.

- Zeus slots have been fixed.

- After leaving each hangar and the firing range, all players are stripped from the gear, leaving them only with the uniform and the cap.

**Comment by adios113** [comment]
New version pushed to repo
https://github.com/blackwatchint/ADI-s-mapmaking/commit/7049e37c1ebeba1cb73cef7f64e88dab9f597be6

**Comment by Fox87** [comment]
**Formations:**
1. - Delete diamond formation
2. - The 2. man in the column needss to look to the right (Thats my bad- Here is the right one- https://dl.dropboxusercontent.com/content_link/fdfiwuFfnlpMpqfSB7fCb6mpL7TtsD5BcZY5NTNei5KJc6f09V7qv7PbvItL5BSm/file)
3. - Missing one man in the formation test- Theres only 9 right now
4. - Needs to make the guys in handcuffs so we can move them

** Medical:**
1. Remove the CFR loadout
2. Make the hangar surgical abel
3. I need a option to make the handcuffed guy unconscious

**Convoy:**
1. Were are the test- Cant find the TP

**Radio:**
1. Make a line to separate the 2 examples in "_Radio Conversation Ex_."
2. The trainees and instructor needs a peditool to take a RTO loadout- then doing the test  (LRR and GPS)
3. Make a picture of the GPS, and were to see the grid (Use the vanilla GPS)

**Spawn base:**
1. Change name on the "Radio" sign- It´s called "_Radio?_"
2. Make pictures to the Killhouse and firing range- So the Bootcamp visually looks done also

**Comment by Fourjays** [comment]
@Fox87 Think you mean this link: https://www.dropbox.com/s/1c12ombrmfn60c5/bootcamp-column.png?raw=1

The prisoners should be handcuffed, yes. Should be ten of them (we're not changing structures yet) and should also be invincible (in case of accidents).

My understand is that there can't be an unconscious option for medical tests. In ACE if a guy is make unconscious, he can only be woken up by being specifically made unconscious (not by medical treatment). The only way for a patient to be made unconscious and be treatable, is for them to have injuries that will make them unconscious (as is the case now).

**Comment by Fox87** [comment]
Thats the one Jays thanks :+1:

**Comment by Fourjays** [comment]
Done a re-test of the bootcamp (RC2) on the test server, running latest ACE and ALiVE (shouldn't effect it). Some issues remain and are some new ones too:

- Start area TP for the Radio hangar is labelled "Radio ? ".
- Remove the diamond formation.
- Wrong column image is being used (see comment above).
- Neither "Become Corpsman" or "Become CFR" do anything, for instructors or trainees.
- The "Vehicle Crash" and "Grenade" injuries do nothing now (possibly ACE update).
- Convoys hangar could benefit from a teleport pole to the vehicles (for expediency).
- HMMWVs for convoys parking should probably have ammo removed, if possible.
- Instructor slots have no Zeus available.
- No long range radio available at Radio hangar.

**Comment by adios113** [comment]
Bootcamp RC3 will be ready tomorrow for another test run.

**Comment by adios113** [comment]
Bootcamp RC3 Update:

* TP for the Radio & Misc Hangar action name is spelled correctly now
* Diamond Formation has been removed.
* Columnd Image has been fixed
* Become CFR action has been deleted and Become Corpsman action fixed.
* New teleport to the vehicles from Convoy Training.
* HMMWVs have no ammo now.
* Another try on fixing Zeus, for some reason not working (possibly because of 3DEN?)
* Box with Radios has been added to the Radio Hangar. As well, moving trough compass training gives you a long range radio now.
* Bootcamp's Formation Hangar has 9 soldiers, not 10 for two reasons:
 - New Squad Structure with the upcoming changes
 - Makes the formation look  even on both sides (no extra man on one side)
* Medical Hangar is now treated as Ace's medical facility
* It is not possible to give you the option to make the guys unconssious, since you won't be able to revive them trough medicaments after that.

**Comment by Fourjays** [comment]
Title images for the range and killhouse. Ready for when they are completed:
- https://www.dropbox.com/s/8mv72ieeufk1rat/bootcamp-killhouse.png?raw=1
- https://www.dropbox.com/s/jegqazs567e5xru/bootcamp-range.png?raw=1

**Comment by adios113** [comment]
Most up to date version of Bootcamp - RC3 has been uploaded to github 
https://github.com/blackwatchint/ADI-s-mapmaking/commit/4aaaf543fecda0d92e40bb9aa4deded622c2996e

Bootcamp is all yours now. I tested the bootcamp as it is, alone on the server, where no issues/bugs with bootcamp features occured. But as we know, one person cannot find everything, so if there's any problems, I am sure you will handle them and it will be mostly some minor bugs.

When Im back, I wanna do the bootcamp, so I hope it will be out by then.

Cheers, you're doing a great job over here. See ya in ~ 2 months.

**Comment by Ludvigroosen** [comment]
> Start area TP for the Radio hangar is labelled "Radio ? ".
> Remove the diamond formation.
> Wrong column image is being used (see comment above).
> Neither "Become Corpsman" or "Become CFR" do anything, for instructors or trainees.
> The "Vehicle Crash" and "Grenade" injuries do nothing now (possibly ACE update).
> Convoys hangar could benefit from a teleport pole to the vehicles (for expediency).
> HMMWVs for convoys parking should probably have ammo removed, if possible.
> Instructor slots have no Zeus available.
> No long range radio available at Radio hangar.

Gonna take a look at this and test this tomorrow.

**Comment by Ludvigroosen** [comment]
> - 1. Start area TP for the Radio hangar is labelled "Radio ? ".
> - 2. Remove the diamond formation.
> - 3. Wrong column image is being used (see comment above).
> - 4. Neither "Become Corpsman" or "Become CFR" do anything, for instructors or trainees.
> - 5. The "Vehicle Crash" and "Grenade" injuries do nothing now (possibly ACE update).
> - 6. Convoys hangar could benefit from a teleport pole to the vehicles (for expediency).
> - 7. HMMWVs for convoys parking should probably have ammo removed, if possible.
> - 8. Instructor slots have no Zeus available.
> - 9. No long range radio available at Radio hangar.

1. Radio is fixed. Named "Radio, Misc Hangar"
2. Diamond formation is removed
3. Think it's fixed just double check the picture [This collum formation is being used](https://dl.dropboxusercontent.com/content_link/ous2ZpUWCRf21aSaNw0g12WD3qeVq3XJsiTFSq96XuG5pB7m0TEJytGgHYAbTeLh/file)
4.  Works. Get's backpack with gear.
5. Non of the medical alternatives are working. (Tested on first pod.)
6. Fixed. Teleporter in the back of the hangar
7. No more ammo in the HMMWV's
8. Instructor got Zeus access
9. Get's an long range without batteries when teleporting to compass training
10. No pictures on killhouse or Shooting Range

**Comment by Fourjays** [comment]
Please clarify what you mean regards point 5, and the batteries for point 9?

**Comment by TheGrandVizier** [comment]
Please make sure all instructor slots are zeus'd.

**Comment by Ludvigroosen** [comment]
@Fourjays So when you go into the medical hangar there is 4 pods. These 4 pods have some alternatives in scroll menu, when selecting one of them nothing happens at all.

**Comment by Ludvigroosen** [comment]
All 4 instructor position is double checked. All of them have Zeus access.

**Comment by Fourjays** [comment]
@Ludvigroosen all the options on the medical boards appear to work for me?

Gave the bootcamp a test, it appears to be pretty much ready.

**Comment by Fourjays** [comment]
Bootcamp is ready to go, but two minor issues need addressing:
- Soldiers used for formations and medical training need their equipment removed (weapons, etc).
- The "Become Corpsman" and "Become CFR" options in the medical hangar need to assign the relevant ACE class.

**Comment by Fox87** [comment]
Thats true, its ready. And only minor things needs to be addressed.

- No need to have two medics- We only need corpsman. And the one we have can not use his surgical kit, dont know why....?

- I really want to follow the guidelines for the sign offs, by adding a GPS to the "radio hangar", so the RCT. can learn to use it.

_> "By signing-off on Misc, you are confirming that:
> The recruit can locate their position on the map with GPS?
> The recruit can read and give 6-grid coordinates over radio?"_

**Comment by Fourjays** [comment]
Had reports from training department that Zeus is not functioning across all four instructor slots, and that the medical "admin" tools (for triggering medical tests) are only working on the first slot. Need to be verified and fixed.

**Comment by Ludvigroosen** [comment]
Checking the Zeus issue tonight.

**Comment by abelarno** [comment]
Tested zeus functionality and ability to trigger medical tests. Could not replicate. Everthing worked fine for me. The become corpsman and become CFR buttons worked for me as well.

Weapons from the formation AI has been removed. Working on the removal of the weapons for the medical AI.

**Comment by abelarno** [comment]
Medical AI weapons removed. For further troubleshooting I'll need a reproducible scenario when something goes wrong.

**Comment by Fourjays** [comment]
@abelarno Let's go ahead and update the bandages chart with the new information available from ACE. Then we can close this as complete.

**Comment by Fourjays** [comment]
Confirm chart has been updated. Initial creation stage complete. Closing.
