### ISSUE TITLE
Investigate addition of new weather effects

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#107]
As discussed previously we want to investigate the possibility of adding sandstorm and snow weather options for use on suitable templates.

Any solution will need to be robust and thoroughly tested.

**Comment by ShiFoo** [comment]
One thing that might be ovious but still needs tobe said is that the howling wind sound should be included into the templates. This boosts the size of the template up to 3 or 4 MB whether the effect is used or not.

**Comment by Fourjays** [comment]
That is a good point. Not sure what Arma's sound support is like, but perhaps we could optimise or replace the audio?

**Comment by ShiFoo** [comment]
Another idea: we just make a second template for the specific map that has the sound included. This way a Zeus can decide whether he wants the sound or not.
Otherwise i only see a remakrable size reduction in cutting the audio. But this will increase the likeliness of realizing that it loops.

**Comment by Fourjays** [comment]
A different template is probably the best idea.

**Comment by Fourjays** [comment]
Transferring to addons tracker for future idea development: blackwatchint/addons#9

Closing.
