### ISSUE TITLE
HAFM NH90 Helicopter and Retextures

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#133]
**Description:**
This is my latest addon, the NH90 helicopter and it can be used as part of my HAFM mod as also as an individual (separate) addon (there are no other mod dependencies - not even of my mod).

This addon includes two variations of the NH90 Helicopter, one for transport only (can transport 14 soldiers plus 2 as crew) and another one armed, for transportation and support (two side doors miniguns and can transport 8 soldiers plus 4 as crew).

**Download:** http://www.armaholic.com/page.php?id=28231
**Size:** 52MB

**Retextures also suggested:**
http://www.armaholic.com/page.php?id=28294
http://www.armaholic.com/page.php?id=28297

**Comment by Kentersnoodlefactory** [comment]
Textures are nice, the flight model is kinda funky, it slides on the landing gear literally the opposite of the blackhawk it drifts lol... It slows down like a bus, No tailrotor recovery is a no go. It simply wont nose down and get speed back, you literally need 1k more in altitude lol. It flies quite weirdly but it looks good.

**Comment by ShiFoo** [comment]
I think we need to be cautious with "flying funky". We just try to replace USAF because of similar reasons...

**Comment by Kentersnoodlefactory** [comment]
Agreed

**Comment by LordCavac** [comment]
I couldn't find anything technically wrong with these. My main issue is that I would tap the rotor button to assist in a bank and the tail rotor would immediately break, and it happened repeatedly. My tail rotor was broken most of the time I was testing. I was also personally unable to get it to not explode in any kind of emergency landing and it will not recover an auto rotation at all. Bug wise no issues. Fun wise I would never agree to fly this.

**Comment by ShiFoo** [comment]
I think we should reject this one. Multiple reports of weird behaviour while flying.

**Comment by Fourjays** [comment]
The models and textures are ok, and the sounds are pretty nice. However, the flying does seem a bit unusual. At times it feels very light, others very heavy. Autorotation is a definite problem. I didn't experience any tail rotor losses in general flight though.

- http://steamcommunity.com/sharedfiles/filedetails/?id=649939026
- http://steamcommunity.com/sharedfiles/filedetails/?id=649939999
- http://steamcommunity.com/sharedfiles/filedetails/?id=649939924
- http://steamcommunity.com/sharedfiles/filedetails/?id=649939832

**Comment by Fourjays** [comment]
Rejected in the meeting on 29/03/2016 due to flight model problems.
