### ISSUE TITLE
AV-8B Harrier II

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#145]
**Description:**
This is another port i made from the Sample Models, with minor modifications of my own.
I've had this in the works for a long time, mostly because i got busy with other projects and for some technical problems i had a hard time solving.
There are some features i meant to implement (dampers, decent MFD, reworked interiors) but that would take even MORE time and i don't feel like keeping this for myself any longer.
Some of you will be pissed because of the aircraft loadouts i guess but i think the current loadout is balanced enough, they are fun enough without giving pilots god-like firepower that can obliterate whole AOs on their own.
As for the cockpit, as i mentioned earlier i meant to rework it because it's mid-low detail right now but that might take some time and i still have to get the hang of it, also there is the huge limit of PiP that doesn't allow much customization and doesn't have enough detail to be an effective navigation tool (i'll be leaving links to feed tracker tickets if you want to help out).
Good news is, i did some minor tweaks i'm really satisfied with, especially collision lights and materials/textures.
They still have all the STOVL features from A2 and can take off and land safely on the LHD, i'm pretty sure that is also true for the Nimitz.

**Download:** http://www.armaholic.com/page.php?id=26840
**Size:** 32MB

Posted as a result of #131 for consideration in replacing USAF pack.

**Comment by Fourjays** [comment]
We had this mod once before. It works well and is of a pretty good quality. The interior is good with fully working thermal MFDs. It flies well and feels the way I imagine a Harrier should. There is no hangar support but each of the variants includes a good selection of weaponry. It can be a little bit loud in the cockpit, which may be a minor issue.

I had a go at landing using the VTOL mode. It is awkward and will take some practice for pilots to be able to handle it.

Screenshots:
http://steamcommunity.com/sharedfiles/filedetails/?id=574771389
http://steamcommunity.com/sharedfiles/filedetails/?id=574771701
http://steamcommunity.com/sharedfiles/filedetails/?id=574771625
http://steamcommunity.com/sharedfiles/filedetails/?id=574771824
http://steamcommunity.com/sharedfiles/filedetails/?id=574771892

**Comment by Kentersnoodlefactory** [comment]
It works nice, flies pretty decent. Although the VTOL landing? It might be me being stupid but i cant really get it to hover properly. It looks nice both interior and exterior, seem to be a nice weapon selection for several different roles. The targeting pod seem to work with thermal vision and such.

**Comment by Fourjays** [comment]
Accepted in the meeting on 13/12/15.

**Comment by Fourjays** [comment]
The AV-8B Harrier II appears to have a bug in 1.54. A vanilla "Darter" drone appears just behind the front landing gear, and prevents operation of the landing gear. Will be investigated further, but its inclusion in the modpack is now pending the resolution of this bug.

**Comment by Fourjays** [comment]
Will be moved to the backlog for now, as it won't be possible to fix this within the immediate future.

**Comment by Fourjays** [comment]
This has been obsoleted by #296 which includes as updated version of this mod.
