### ISSUE TITLE
Performance testing of Wake Island

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#155]
The Wake Island map isn't used much because some people report poor performance on it. We need to do some testing to determine how much of a performance impact there is on this map.

**Comment by karlkarl93** [comment]
This probably doesn't tell us much, but on battle royale, the map had pretty good FPS. I'll try to do some official testing and report here.

**Comment by LordCavac** [comment]
I just hosted this on the server with three players, several hundred AI, lots of waypoints, tanks, helis, and fixed wing. Hessel had the lowest FPS at 24. Performance wise I don't think there are any issues.

That being said, there are lots of discolored areas on the map that look like things should be there but there is nothing present. I don't know if that is normal or not as I never played the map extensively.

**Comment by ShiFoo** [comment]
could you maybe provide a screenshot of what you mean or at least point the grid where you have spotted this issue?

**Comment by Ludvigroosen** [comment]
Tested this briefly. Had no problems with unit's. Normal fps were 60 on wake island lowest were 20 fps with about 70 units all over the island. Remembered we had an OP about 2 weeks ago were i had no issues either.

**Comment by Fourjays** [comment]
Theres enough evidence here to consider Wake Island's performance to be within normal bounds.
