### ISSUE TITLE
Medium Tactical Vehicle Replacement (MTVR)

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#159]
**Description:**
Based upon the Medium Tactical Vehicle Replacement (MTVR) by RichardsD which adds a variety of MTVR's used by the United States Marine Corps.
This addon contain all MTVR from original addon and:
- tanned variants of all MTVRs from original addon
- tweaked configs (less armor, angles of weapon rotation to pevent textures overlap)
- retexture of cabin interior and vehicle body

All changes was made with config editing and HEX-editor (resolve some issues with pathes).

**Download:** http://www.armaholic.com/page.php?id=28907
**Size:** 66MB

**Comment by karlkarl93** [comment]
My tests didn't show any immidiate problems, it was very nice to drive, maybe even a little bit too nice to drive (didn't feel heavy like a truck). I didn't notice any model problems except one that I already put into the suggestion post on the forum.

There are multiple versions of this truck, as said on the Armaholic page. There are armored trucks, trucks with MGs on them, fuel and cargo trucks, etc.

I think this would be a very nice mod to have since the current trucks we have are kinda bad.

**Comment by LordCavac** [comment]
They don't handle like trucks, feels more like driving a small car. They accelerate and stop in very short distances. They look great though, you can check my steam profile for the screenshots. I didn't find any technical issues.

**Comment by TheGrandVizier** [comment]
Are they ACE Refuel / Rearm compatible?
Do they have the same inventory space for loading boxes as trucks or as smaller cars?

**Comment by LordCavac** [comment]
They are refuel/rearm compatible, all of them only hold 1x Ace ammunition box except the extended cargo which holds 2. the MK. 27 extended cargo seats 29 men, the MK 23 seats 14, the 4x4 seats 8, and the 16 ton seats 3 all those numbers include the driver.

**Comment by TheGrandVizier** [comment]
Amazing. Thank you!

**Comment by Ludvigroosen** [comment]
**Compatibility**(If it compatible with the mod pack)
This mod has no compatibility issues with our mod pack except some weird behavior against ACE. (Check screenshots)

**Performance Issues**
Worked fine. Had no performance issues

**Playstyle** (If it compatible with how we play)
Yes, would think this would work to fit in the way we operate.

**Impacts** (Any extra work/impacts & needed mods)
 None that I could find.

**Quality** (Quality of mod, graphic, works correct etc.)
No dynamic meter in the panels of the cars. All the cars look good and works fine. Would say they are quite nice if the issue with ACE wasn’t there.

**Sounds**
Sounds fine in my headphone’s.

**Screenshot's – [imgur ](http://imgur.com/a/RPgbZ)**
So explanation on the elevation on the wheel, I removed the wheel from the vehicle, but it didn’t remove the wheel I wanted, so I fired some rounds on it and it started to elevate.

**Uncompressed Size**
93,1 MB

**Activity - Development**
10 June 2015 – Author still active.

**Personal opinion**
Would love to see this mod in the mod pack if the ACE compatibility worked correctly. I would say no to this mod.

**Comment by Fourjays** [comment]
The MTVR mod was abandoned and has since been adopted by ruPal, who has adopted many such abandoned projects. Overall the MTVRs look and sound good, with some minor visual texture issues (http://steamcommunity.com/sharedfiles/filedetails/?id=658624477). There are a number of different versions, from armed and unarmed, to short and long, all available in woodland or desert camo. The trucks handle well, but don't really feel like heavy trucks - they accelerate very quickly (0-100kmh in 6 seconds), maintain high speed even up steep hills (90-100kmh), and grip like a race car regardless of the road surface. Crashing at 104km/h into a rock only broke a wheel.

All of the MTVRs are semi-broken when it comes to replacing wheels. Removing the wheel does not have any visual effect, although the wheel does appear next to the player. It is unclear if the wheel is actually removed or not, but shooting a wheel will destroy it, after which it can successfully be replaced with a new wheel.

The MTVRs would be a good addition, if not for the buggy ACE interaction and the ridiculously un-truck-like handling. Screenshots:
http://steamcommunity.com/sharedfiles/filedetails/?id=658624417
http://steamcommunity.com/sharedfiles/filedetails/?id=658624209
http://steamcommunity.com/sharedfiles/filedetails/?id=658624267
http://steamcommunity.com/sharedfiles/filedetails/?id=658624347
http://steamcommunity.com/sharedfiles/filedetails/?id=658624531

**Comment by Fourjays** [comment]
Rejected in the meeting on 04/04/2016 due to ACE issues.
