### ISSUE TITLE
HuntIR grenades spawn multiple times

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#167]
It appears that with the new updates HuntIR grenades spawn multiple times in the same position. When fired upon they immediately fall the ground, revealing that there are multiple grenades spawned.

The rounds may also be appearing larger, as people seemed to think they were infantry.

**Comment by Fourjays** [comment]
Confirmed that HuntIR rounds spawn multiple instances of a HuntIR in the air. Likely to be an ACE issue.

**Comment by Fourjays** [comment]
We need to verify exactly which mod is responsible (i.e. make sure it is purely ACE) for this bug before it can be reported to the developers.

**Comment by LordCavac** [comment]
Unable to reproduce in singleplayer, ADi said it might be a script issue where it spawns one grenade per player on the server. If so it can only be tested and narrowed down on the server.

**Comment by adios113** [comment]
Maybe will get fixed with the ACE Update to 3.4.2

**Comment by Fourjays** [comment]
This needs testing server side.

**Comment by Fourjays** [comment]
We also need to verify if this still occurs with the latest modpack.

**Comment by ShiFoo** [comment]
I will test it later when i get home

**Comment by ShiFoo** [comment]
This does not seem to exist anymore. I fired like 20 rounds and all worked fine.

**Comment by Fourjays** [comment]
Been a report of this still occurring (multiple copies spawned in the air). It sounds like a locality issue. Has anyone tested on the server with multiple people present?

**Comment by ShiFoo** [comment]
Well, i have tested it on the dedicated server with steven present. Not multiple people but even with two i should have been able to see a problem because two hunt IRs would collide as well...

**Comment by Fourjays** [comment]
Should also check the number of HuntIR monitors, HuntIR grenades, or grenade launchers as potential causes for the multiplication.

**Comment by Fourjays** [comment]
Confirmed with @wingatex that this is still occuring: http://steamcommunity.com/sharedfiles/filedetails/?id=655896926

Looks like a straightforward locality issue as one HuntIR round is spawned per-player.

**Comment by ShiFoo** [comment]
And why wasn't it as issue when i tested it with steven on the server?

**Comment by Fourjays** [comment]
Issue no longer relevant due to modpack reset.
