### ISSUE TITLE
Mortars, howitzers spread shrapnel over huge range

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#169]
With the newest update, mortars and howitzers spread leathal shrapnel over a very large range (approximately 200-500m for mortars). This seemes excessive.

**Comment by Fourjays** [comment]
Tested and confirmed this is a modpack bug. Running a vanilla install the mortars have a range of up to 75m.

This could be an ACE configuration setting.

**Comment by DextroNC** [comment]
Does this effect all mortars also the player and AI operated ones?

Without advanced medical it seems normal, I tested it a bit. (Kind of relevant for monday's mission)

**Comment by TheGrandVizier** [comment]
I think all shrapnel is based in ACE3. Test without ace?

**Comment by ShiFoo** [comment]
Or is it just an occasional bug? Might not be that it is always broken...

**Comment by abelarno** [comment]
Running tests in an empy virtual reality map with all the mods on is having ok results. Shrapnel seems not to be lethal passing ~75m for mortarts. With the Howitzers its ~100m and sometimes a bit over it seems.

**Comment by abelarno** [comment]
Mortars seem to spread lethal shrapnel to about 200 meters. After that you still hear the shrapnel around you, but it doesnt seem lethal anymore. Howitzer rounds spread shranpel a lot further.
Ace 3 Frag seems to be the creator of shrapnel: (https://github.com/acemod/ACE3/tree/master/addons/frag)

It can be altered in the addons/frag/CfgAmmo.hpp file.
For example:

   
> class ModuleOrdnanceHowitzer_F_ammo: Sh_155mm_AMOS {
        GVAR(enabled) = 1;
        GVAR(classes)[] = {"ACE_frag_large", "ACE_frag_large", "ACE_frag_large_HD", "ACE_frag_large", "ACE_frag_huge", "ACE_frag_huge_HD", "ACE_frag_huge"};
        GVAR(metal) = 1950;
        GVAR(charge) = 15800;
        GVAR(gurney_c) = 2320;
        GVAR(gurney_k) = 1/2;
    };

**Comment by Fourjays** [comment]
We need to verify if this still occurs with the latest modpack.

**Comment by Fourjays** [comment]
@Ludvigroosen has confirmed this issue still occurs: http://snag.gy/QiZyq.jpg

**Comment by TheGrandVizier** [comment]
Please clarify - Is this only Zeus Fire Support or is this relevant for all mortars and howitzers?

**Comment by ShiFoo** [comment]
As far as i know, the explosion class is the same, so i would assume its for all

**Comment by Fourjays** [comment]
Testing indicates that mortars and howitzers are very likely to kill someone within 100m for howitzers and 50m for mortars. Shrapnel appears to affect a range twice that, and has a far lower chance of causing an injury.

From the information I can find (http://www.globalsecurity.org/military/library/policy/army/fm/7-90/Appb.htm), these ranges seem fairly accurate. For reference, the Arma 3 Zeus fire support options are 155mm howitzers and 82mm mortars.

**Comment by Fourjays** [comment]
Closing as intended behaviour.
