### ISSUE TITLE
RHS AFRF and USAF update to v0.4.0.1

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#171]
**Changelog (AFRF):** http://www.rhsmods.org/mod/1#changelog
**Changelog (USAF):** http://www.rhsmods.org/mod/2#changelog

**Download (AFRF):** http://www.armaholic.com/page.php?id=27150
**Download (USAF):** http://www.armaholic.com/page.php?id=27149

**Comment by Fourjays** [comment]
Will need considerable testing to make sure everything plays nice together.

**Comment by Fourjays** [comment]
Both AFRF and USAF have been updated to v0.4.0.1. The previously linked changelogs and downloads are up-to-date.

**Comment by Fourjays** [comment]
Requires testing on all elements of RHS, as well as additional testing to determine effect on existing mods that may be affected, such as  RDS Tanks/Static Weapons/Civilians, TF47 Launchers, Leight's Opfor Pack and any other mod or feature subsequently dependent on these mods.

**Comment by TheGrandVizier** [comment]
Both have been uploaded to repo.

**Comment by Fourjays** [comment]
Pushed to next milestone to ensure #232 is given full attention.

**Comment by Relvox** [comment]
uploaded (source: torrent from site)

**Comment by Fourjays** [comment]
No obvious issues have turned up during limited testing.

Is ready for deployment to the live repository.
