### ISSUE TITLE
3CB BAF Vehicles update to v4.0

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#173]
Vehicles of the British Royal Marines Commandos and other UK Armed Forces.

**Changelog:**
 - added Apache AH1
 - added AW159 Wildcat AH1 & HMA2
 - Jackal/Coyote:
  - fixed missing door sounds
  - tweaked cargo deck visuals
  - optimised graphics
  - added ACE refueling option to Coyote Logistics variant

__Size:__ 232 MB
__Link:__ http://www.armaholic.com/page.php?id=27203

**Comment by Fourjays** [comment]
Needs some brief testing on the new helicopters.

**Comment by TheGrandVizier** [comment]
Uploaded to repo

**Comment by Fourjays** [comment]
Pushed to next milestone to ensure #232 is given full attention.

**Comment by Relvox** [comment]
uploaded (source: armaholic)

**Comment by Fourjays** [comment]
Changes deployed to the test repository, awaiting push to live.
