### ISSUE TITLE
Medium Utility Helicopters

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#187]
**Description:**
This mod contains various medium class helicopters from previous BI games. 
The weight of passengers and mounted weapons and ammo will greatly affect the helicopters when using the advanced flight mode. 

Advanced Flight Model implemented.
The weapons mounted on some of the helicopters effects how the helicopters handles. when fully loaded with both gun/rockets-ammo and passengers, helicopters might have difficulties taking off.
In the Mil Mi-17 'Heavy Rockets' it can help to release the wheel brake and do a rolling takeoff. (Releasing wheel brakes only works when AFM is enabled)

**Download:** http://www.armaholic.com/page.php?id=28841
**Size:** 339MB

**Comment by LordCavac** [comment]
I'll do this as a review for each helicopter and a final thoughts in my initial testings.

AW101 Merlin (Unarmed): 
Aesthetics and non-flight functionality:
First, the detail on the helicopter is pretty amazing, you can open and close the two doors plus the ramp independently and walk around inside the passenger area. The area for interacting to get in the pilot's seat is a bit weird being behind the cockpit, but that is not a real issue.

Regular Operation:
Taking off the the sounds  for the helicopter is well done, although maybe slightly out of sync with how the rotors are actually moving, but I'm not a real life helicopter expert so I can't say for sure. The helicopter handles incredibly well on the controls and is perhaps the most responsive on the pitch and roll of any helicopter I have ever flown. However, even unloaded the primary rotor feels weak, throwing out torque and RPM warnings almost any time you do adjustments on the throttle. The max cruising speed I was able to achieve flying level was 264km/h. The only thing I could find that it would slingload was the quadbike. The quadbike did not seem to affect helicopter performance in any meaningful way. There is a glitch with the slingload assist feature that will cause the thing you are trying to slingload to disappear if you center it in the target, it must be kept off center. If the target disappears you must restart the process.

Emergency situations:
The helicopter has significant issues dealing with auto-rotation, I only successfully broke out of it once only to slip back in to it and crash en route back to the airfield. If the tail rotor goes you need to be going over 120km/h to avoid going back in, if I remember right I was going around 140 the time I managed to stop it the first time. I think this has to do with the under-powered main rotor as it felt like I was getting out of it at lower speeds but the rotor trying to power back up would occur in such a way that would restart the rotation (anytime you hit the throttle it spins right). The main rotor seems to be neigh indestructible, the entire helicopter blew up before I could ever find a way to break the rotor. What does happen is that the rotor begins under-preforming at both ends of the throttle, forcing the player to play the throttle loser to the middle where performance is unaffected (I don't know if that is a glitch or intended). This indestructible main rotor is good in that engine failure in this helicopter cannot be recovered from. Gunning the throttle unpowered does not do anything to slow it down regardless of how much power is stored, and only serves to pull it hard to the right adding to the list of problems the pilot must try to deal with.

Overall:
I enjoyed flying this craft, I feel like it would make an excellent alternative to the Chinook when slingloading is not required as it is far more forgiving in almost every situation and far easier to handle. The only drawback (compared to the Chinook) I can tell is a slightly reduced passenger capacity which I haven't been able to get a full count on but I guess is in the mid-20s. I do believe the Chinook is the most comparable heli we currently have available, but it is better in almost every aspect as far as I can tell. I do not feel like it would outperform the Blackhawk as far as a smaller unit transportation platform though

I'll post reviews of a few more later but I need to go to bed I just wanted to write this while it was fresh.

**Comment by LordCavac** [comment]
My experience with the AW101 Merlin(Armed) could not be more different than the unarmed version. The additional weight added by the 3 MMGs loaded into both doors and the ramp really shows in the handling and performance. As before the main rotor feels under-powered for a helicopter this size, and with the gun weight the controls became noticeably sluggish and the tail rotor seems like it was destroyed by a strong breeze. (it literally broke when I put on slight pedal pressure to assist a turn.) and it has the same handling problems as the unarmed version. I actually quit playing with it before I was done testing, to me it was painful to fly and completely unfun. I can say that that is pretty much the only bad experience I had with this mod though

**Comment by LordCavac** [comment]
The UH-1 and UH-10 are pretty much the same helicopters except the UH-10 has a spotlight mounted on the bottom that seems to be co-pilot controlled.

They both handle like a lighter version of the blackhawk with an equally strong primary rotor, both the gunship and unarmed variants were very responsive to the controls.

They both handle emeggency situations extremely well, and are capable of sliding landings when the tail rotor is destroyed even though they lack wheels. They both also handle engine loss so well that I was still maneuvering around with them while falling to position myself over the ground better, in fact I didn't even try to level until around 70m height and I accidentally gunned the collective slightly early and I still successfully touched down with no personal injury.

Slingloading works I didn't have time to get the total weight, preformed well with the quadbike attached.

I would highly recommend this for C-Grade level pilot tests if this mod is adopted, they are both highly forgiving platforms that can take a great amount of stress and stay in operational condition.

One glitch I found is when I broke the tail rotor of the UH-1 the vertical speed indicator over the collective stopped working.

**Comment by LordCavac** [comment]
I would recommend this mod for inclusion in the modpack, I could not locate any significant glitches on any of the platforms after two hours of testing on each, and all of them, except the armed version of the Merlin, was an absolute blast to fly.

**Comment by Kentersnoodlefactory** [comment]
Well! Very nicely detailed models, they fly pretty well. The armed Merlin is a bit under powered, the armed mi17 it feels heavy but it is very much flyable, The Merlin has some difficulties with no engine landing like cavac said, although you can do it quite consistently you just have to make sure you set it down nicely and make sure you are level, as the Merlin has a low sitting tail rotor. The Hueys fly nicely and there is a nice shaking effect when firing rockets, there are alot different models of the huey and versions of the models especially for the UH1-H version there are alot of configurations for it with weapons, transport, transport with machineguns and medical etc. Then you have the more modern UH-1N It corresponds to the Bell-412 civilian version, UH1-H is Bell 205 as civilian helicopter. #FUNFACT... 

Im a bit with cavac on the part that the Huey would fit very nicely for C grade. You get away from the continously flipping problem of the Blackhawk, which has it pros and cons. 

Picture tiimee: http://imgur.com/a/vKsIO

**Comment by Fourjays** [comment]
Main reason for this mod appears to be the Hueys as a lot of other helicopters we already have. The helicopters themselves look pretty well made and are of a good visual/audio quality. There are numerous variants, many of which are CAS capable. All of the Huey's fly really well and feel a lot better than the UH-1Z that we already have. Autorotation appears to be possible and the damage model behaves normally.

I think the only real question about this mod is how useful it can really be.
 
- http://steamcommunity.com/sharedfiles/filedetails/?id=649939179
- http://steamcommunity.com/sharedfiles/filedetails/?id=649939458
- http://steamcommunity.com/sharedfiles/filedetails/?id=649939318
- http://steamcommunity.com/sharedfiles/filedetails/?id=649939247
- http://steamcommunity.com/sharedfiles/filedetails/?id=649939538
- http://steamcommunity.com/sharedfiles/filedetails/?id=649940086
- http://steamcommunity.com/sharedfiles/filedetails/?id=649940271
- http://steamcommunity.com/sharedfiles/filedetails/?id=649940489

**Comment by Fourjays** [comment]
Rejected in the meeting on 29/03/2016 due to likelihood of it not being used.
