### ISSUE TITLE
USS Nimitz surface glitches

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#207]
During an op on Lingor, the USS Nimitz had a couple of glitches relating to people and vehicles on the carrier deck.

First was people falling through a tiny inperceptible gap in the center of the deck, forward of the tower.

Second was a helicopter (Chinook) on the deck that spontaneously combusted while people were loading into it.

**Comment by ShiFoo** [comment]
The nimitz has always been a bit glitchy... Planes sunk into the flight deck, people glitching between the flight deck and the elevator, etc. Hard to reproduce because it happens occasionally... I dont think there are ways to fix it...

**Comment by TheGrandVizier** [comment]
When jeros landed the Chinook the first time, it exploded after 20 meters of rolling on the deck following touchdown.
When jeros actively prevented the roll, it did not explode from regular landing.

**Comment by Fourjays** [comment]
Only glitch I know exists is the elevator edges being a dubious place to walk. Want testing to done to determine if the above glitches are repeatable, as they will affect the usefulness of the USS Nimitz for ops.

**Comment by Fourjays** [comment]
Twice during flight training an aircraft was teleported to the ocean floor on take-off. Possibly an issue with the Nimitz?

Also noticed that the catapults are not correctly aligned anymore:
http://steamcommunity.com/sharedfiles/filedetails/?id=598529882

**Comment by Fourjays** [comment]
Just read the known issues for the Nimitz while working on #236 and noticed two remarks that may be relevant to the issues we are getting. Highlighted them in bold.

> Known issues:
Textures:
o new textures at times stretched, especially in hallways
o texture missing at elevator 3
o JBD 4 still has old textures
o not all carrier areas freshly textured, hangar 4 for example
o missing ceiling texture in hangar 4, small room
General:
**o carrier not assembled correctly when place too far off map**
o water access platform not working well yet, weird texture
o high possibility to glitch through floor at Nimitz information poster
o towing module for Nimitz still needed for ambiance module
o shooter animation not mirrored on cat 4
o see through wall glitch in hallways
o rescue module boats are quite far from carrier
o wires on some planes get drawn up in the air
o flight operations still very experimental
Aircraft:
o vanilla arma3 planes don't work to well with the carrier
o UAVs don't work at all with the carrier
Elevator:
o weapons elevator at times not functional going up
o weapons elevator can be quite deadly

> 
> WORK AROUNDS
> **On some places the carrier seems to work better than on others. If you get glitches, especially in the hangar falling through the floor, try to move the carrier a bit or change direction and see if it works better.**

Source: http://www.armaholic.com/page.php?id=23049

**Comment by Fourjays** [comment]
Could we verify if any of the above "known issues" apply to the placement of the Nimitz on Lingor?

**Comment by Fourjays** [comment]
This would appear to be a placement issue as the "known issues" indicate. On Altis where we frequently use this the Nimitz is located within the map bounds, rotated to face direct north. On Lingor where we had glitching, it is located partly out of map bounds and is rotated to face south west.

Recommend we ensure Nimitz is placed to best avoid these issues for now and see how it goes.

**Comment by Fourjays** [comment]
Moving to backlog for now.

**Comment by Fourjays** [comment]
Closing for now. Will reopen if there are future reoccurences.
