### ISSUE TITLE
F-16C Fighting Falcon update to v0.24

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#212]
**Changelog**
- New Skin System
- Afterburner is no longer act like Frame Skip/Drop
- AGM-65, SDB,SDB II is added into F-16 Loadout Dialog
- Also new template (include custom code in config) is updated too.

**Download:** http://www.armaholic.com/page.php?id=27766

**Comment by Relvox** [comment]
uploaded (source: armaholic)

**Comment by Fourjays** [comment]
Changes deployed to the test repository, awaiting push to live.
