### ISSUE TITLE
FIR AWS US update to v0.7

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#213]
**Changelog**
- New Skin system function
- Add GBU-39 SDB / GBU-53 SDB II / BRU-61 SDB Rack

**Download:** http://www.armaholic.com/page.php?id=28646

**Comment by Relvox** [comment]
uploaded (source: armaholic)

**Comment by Fourjays** [comment]
Changes deployed to the test repository, awaiting push to live.
