### ISSUE TITLE
Chernarus Winter update to v1.11

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#214]
**Changelog**
v1.11
 - fixed: missing server key files

v1.1
 - fixed: Objects altitude issues
 - fixed: missing sound files

**Download:** http://www.armaholic.com/page.php?id=29752

**Comment by Relvox** [comment]
delegated to nik

**Comment by TheGrandVizier** [comment]
Uploaded to repo

**Comment by Fourjays** [comment]
Changes deployed to the test repository, awaiting push to live.
