### ISSUE TITLE
Gorgona update to v1.4

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#215]
**Changelog**
 - ADDED: A few minor cosmetic tweaks to road paths (near Gorgona Scalo) and to the pier at the harbour in Gorgona Scalo. 
 - ADDED : Short road segments to gated compounds to allow AI to path through gates better (hopefully). 
 - ADDED: any changes to objects introduced in the latest (post-Nexus) version of Mikero's Arma3p.

**Download:** http://www.armaholic.com/page.php?id=27996

**Comment by Relvox** [comment]
uploaded (source : armaholic)

**Comment by Fourjays** [comment]
Changes deployed to the test repository, awaiting push to live.
