### ISSUE TITLE
Chechen Republic of Ichkeria Armed Forces

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#219]
**Description:**
Chechen Republic Of Ichkeria Armed forces of the First Chechen War period (1994-1996), the mod contains Ichkerian militia, Army and the President's Guard (infantry, light and armored vehicles)

**Download:** http://www.armaholic.com/page.php?id=30014
**Size:** 167MB

**Comment by Ludvigroosen** [comment]
**Tested (Which map)**
Altis

**Compatibility (If it compatible with the mod pack)**
None found

**Performance Issues**
None found

**Playstyle (If it compatible with how we play)**
This would work with our modpack

**Impacts (Any extra work/impacts & needed mods)**
 Would need to install the following mods – RHS: Armed Forces Of The Russian Federation
HLC AK Pack, HLC-Core, RDS A2 Civilian Pack

**Quality (Quality of mod, graphic, works correct etc.)**
The quality of the mod is good.

**Sounds**
Uses the HLC pack so sound are good

**Screenshot's - [imgur](http://imgur.com/a/WB3Dk)**

**Uncompressed Size**
272 MB - IchkerianTroopsDicslose

**Activity - Development**
30 Dec 15

**Comment by Fourjays** [comment]
Have concerns about this given issues (#479 & #480) with the Soviet Troops in Afghanistan mod, which is from the same author.

**Comment by Fourjays** [comment]
Rejected in the meeting on 11th July 2016.
