### ISSUE TITLE
New Faction - Chedaki

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/modpack#22]
New Faction for our Loadout stands.

- Squad Leader
- Fireteam Leader
- Radio Transmitter Operator
- Corpsman
- Engineer
- Combat First Responder
- Automatic Rifleman
- Assistant Automatic Rifleman
- Rifleman (AT)
- Heavy Machine Gun (NSV Tripod)
- Helicopter Pilot
- Designated Marksman 
- Sniper
- Demolition Man
- Crewman
- Rifleman

**Comment by adios113** [comment]
This New Faction cannot be completed, because of https://github.com/blackwatchint/blackwatchint/issues/233 . Unless we extract the uniforms from the mod and add it separately.
Pending further instructions.

**Comment by ShiFoo** [comment]
Currently on hold. More details to follow. The conflict with the removal of LOP is a valid point. I dont want to put time and effort into this faction before we have a solution (or at least a way to go) on #233.

**Comment by TheGrandVizier** [comment]
Will it be possible to have this for 19th given CUP implementation?

**Comment by Fourjays** [comment]
There will be Chedaki uniforms in CUP. Unsure if they are already present or will be coming further down the line.

**Comment by Fourjays** [comment]
Pushing to a future milestone due to gear uncertainty.

**Comment by Fourjays** [comment]
Due to significant increase in available loadouts and the new development methodology, this request has been obsoleted.
