### ISSUE TITLE
Soviet Troops in Afghanistan Mod

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#220]
**Description:**
After receiving quite a lot of requests I made an OKSVA (Limited Contingent of Soviet Troops in Afghanistan) mod which containts Soviet VDV, MSV, tank troops, artillery and aviation units and groups (in two versions: winter and summer) with the Soviet Afghanistan War equipment ('Afghanka' camo uniforms, winter jackets, soviet booniehats, etc).

**Download:** http://www.armaholic.com/page.php?id=30119
**Size:** 137MB

**Comment by TheGrandVizier** [comment]
The New RHS version adds Ruskies desert camos.
So if that is the only reason to get this, I'd say its not needed once we update RHS.

**Comment by HesselGroenewoud** [comment]
For this I compared both the RHS and the Soviet Troops in Afghanistan Mod. I came to the conclusion that RHS already offers a lot of desert camouflaged uniforms. RHS had uniforms, vests and hats/booniehats. Soviet Troops in Afghanistan Mod has the same items as RHS exept for the vests. I also noticed that both mods lack any type of hard headgear in desert camouflage. 



![20160310151941_1](https://cloud.githubusercontent.com/assets/17065928/13672182/fb9a4212-e6d3-11e5-8fda-b384eb19075e.jpg)
![20160310152141_1](https://cloud.githubusercontent.com/assets/17065928/13672184/fb9b8708-e6d3-11e5-9856-464b639ae152.jpg)
![20160310152226_1](https://cloud.githubusercontent.com/assets/17065928/13672185/fb9bc416-e6d3-11e5-802e-9cbc2bfaae25.jpg)

**Comment by TheGrandVizier** [comment]
For the record, this was suggested before rhs had desert camo

**Comment by adios113** [comment]
##  Soviet Troops in Afghanistan Review:

**About**

Soviet Troops in Afghanistan Mod adds new variety of vests, uniforms, headgear and backpacks into the pole. Works via Arsenal and is Zeus Compatible with different unit compositions.
I personaly like the variety of new Uniforms and headgear available. Mod uses RHS retextures of some uniforms and headgear, but most of them are completely new. They even made their own retexture for Long Range Radio from TFAR, which is a nice plus. It also uses RHS vehicles which are mostly no different/not retextured from the ones we see every day and it utilises statickweapons provided by CUP/RDS:

**Screenshots from Vehicles and Statics:**

http://steamcommunity.com/sharedfiles/filedetails/?id=647457139
http://steamcommunity.com/sharedfiles/filedetails/?id=647457174
http://steamcommunity.com/sharedfiles/filedetails/?id=647457206
http://steamcommunity.com/sharedfiles/filedetails/?id=647457242
http://steamcommunity.com/sharedfiles/filedetails/?id=647457265
http://steamcommunity.com/sharedfiles/filedetails/?id=647457289
http://steamcommunity.com/sharedfiles/filedetails/?id=647457320

Infantry Units come with 2 Main versions - Summer and Winter.
Winter in this example does not mean white camouflaged gear to cover in snow, but warm, thick jackets in desertish camo.

**Summer Units:**

http://steamcommunity.com/sharedfiles/filedetails/?id=647457350
http://steamcommunity.com/sharedfiles/filedetails/?id=647457389
http://steamcommunity.com/sharedfiles/filedetails/?id=647457419
http://steamcommunity.com/sharedfiles/filedetails/?id=647457460
http://steamcommunity.com/sharedfiles/filedetails/?id=647457514
http://steamcommunity.com/sharedfiles/filedetails/?id=647457535
http://steamcommunity.com/sharedfiles/filedetails/?id=647457560
http://steamcommunity.com/sharedfiles/filedetails/?id=647457596
http://steamcommunity.com/sharedfiles/filedetails/?id=647457624
http://steamcommunity.com/sharedfiles/filedetails/?id=647457652
http://steamcommunity.com/sharedfiles/filedetails/?id=647457675
http://steamcommunity.com/sharedfiles/filedetails/?id=647457699
http://steamcommunity.com/sharedfiles/filedetails/?id=647457726
http://steamcommunity.com/sharedfiles/filedetails/?id=647457757
http://steamcommunity.com/sharedfiles/filedetails/?id=647457784

**Winter Units:**

http://steamcommunity.com/sharedfiles/filedetails/?id=647457821
http://steamcommunity.com/sharedfiles/filedetails/?id=647457848
http://steamcommunity.com/sharedfiles/filedetails/?id=647457884
http://steamcommunity.com/sharedfiles/filedetails/?id=647457917
http://steamcommunity.com/sharedfiles/filedetails/?id=647457944
http://steamcommunity.com/sharedfiles/filedetails/?id=647457979
http://steamcommunity.com/sharedfiles/filedetails/?id=647458007
http://steamcommunity.com/sharedfiles/filedetails/?id=647458048
http://steamcommunity.com/sharedfiles/filedetails/?id=647458082
http://steamcommunity.com/sharedfiles/filedetails/?id=647458103
http://steamcommunity.com/sharedfiles/filedetails/?id=647458123
http://steamcommunity.com/sharedfiles/filedetails/?id=647458141

**To summarize...**

Mod expands variety from the Russian Faction. There's a decent amount of new stuff, which gives the feeling of Soviet Era troops. It even has Cold War Era Russian camouflage we could use to simulate [USA <-> USSR conflict ](http://steamcommunity.com/sharedfiles/filedetails/?id=647457389), so we are not limited to Afghan styled missions with this modpack.
Most of the weapons used by the AI soldiers are HLC's AKs, heavier weapons are those from RHS.

Overall, after the update of RHS which added new Desert Camo options for the Russian Factions, we may have some duplicates which we can count on fingers, but this can be overshadowed by the addition of new stuff, specificaly targeted for Soviet Era, which we currently do not have in our modpack, besides the weapons. The mod itself is worth discussing in my opinion, as it provides high quality gear and opens up more fictional conflict possibilities, expanding our mission maker's room to play with.

**Comment by Ludvigroosen** [comment]
**Tested** (Which map)
Altis

**Compatibility** (If it compatible with the mod pack)
Yes our modpack is working with these mods.

**Performance Issues**
No performance issues found. 

**Playstyle** (If it compatible with how we play)
Both yes and no. I can see some possible that we can use this mod during some OP’s

**Impacts** (Any extra work/impacts & needed mods)
RHS: Armed Forces of the Russian Federation -  Already in the pack.
RHS Requirments - CBA

HLC AK Pack	- New mod. Implementation and testing needed.
HLC-Core 	- New mod. Implementation and testing needed.	
 
**Quality** (Quality of mod, graphic, works correct etc.)
The quality of the mod is good, it works as expected. The only problem I had was that the BTR had its own repair alternative (Check Screeenshots). Otherwise no issues found.

**Sounds**
Sounds like RHS, because most of the units need RHS and won’t work without them. 

**Screenshot's - [imgur](http://imgur.com/a/w0wjf)**

**Uncompressed Size**
162 MB – Only Soviet Troops in Afghanistan
295 MB - NIArms_AK V2.0
20,5 - NIArms_Core V1.0

**Activity - Development**
2016-01-05 Release Date

**Personal opinion**
I feel like we have a chance to add this mod due to only giving OPFOR some more chocies.

**Comment by VoicelessPrivate** [comment]
**Mod**
Soviet Troops in Afghanistan.

**Looks**
The quality of the mod is just amazing. The uniforms have a really nice finish to them. 

**Issues**
There were no issues at all with the mod, as long as you have the RHS mod on, there wouldn't be any problems.

**Compatibility**
This mod fits right in our modpack. It will give us a new timeframe to fight in. We allready have the US loadout that is in this timeframe (1980's) and we have a taliban loadout aswell. 

**Extra work**
The work that needs to be done on this mod is implementering the mods that this mod need.
- RHS: Armed Forces Of The Russian Federation (allready in the modpack)
- HLC AK Pack (I tested the mod with out this mod so it's no needed from what i saw there were no problems.)
- HLC-Core (And the same with this mod as well.)

**Screenshots**
The first 5 screenshots are a squad where you clearly can see that it's totally random, with what they have on. But the weapons and other types of items are the same it's just the looks that chances from every time you place a new unit.
http://imgur.com/Rsbcjzy
http://imgur.com/moRiZp9
http://imgur.com/LkzKMUE
http://imgur.com/DKegOpz
http://imgur.com/4IvT8w5

These are some of the variants of the camo pattens that can be found in this mod pack. The last 3 screenshots is a uniform that comes in various colors.
http://imgur.com/ked6go6
http://imgur.com/ZItuXTG
http://imgur.com/FHiY6CC
http://imgur.com/Ru5YzgF
http://imgur.com/yAujcKY

**My opinion**
I would really like to see this mod in our modpack. It would add some much to what we would be abel to do. We could get a bit away from the modern timeframe that we are playing in a lot.

**Comment by Fourjays** [comment]
Uploaded to test repository, waiting deployment.
