### ISSUE TITLE
Plank

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#221]
**Description:**
Plank is a simple but extremely useful open-source fortification script. It can be use in a broad spectrum, base building, FOB building or on-the-fly-defenses. It was designed in the mindset of simplicity with regards to both mission implementation and player use.

**Video:** http://gfycat.com/PitifulScientificAmazonparrot
**Download:** http://www.armaholic.com/page.php?id=26088
**Size:** 1MB

**Comment by Fourjays** [comment]
When testing this we will need some questions answered to determine its usefulness:
 - Who can place the fortifications?
 - What can be placed?
 - What can not be placed?
 - Is there a base object used for deployment, or do objects simply appear from thin air?

**Comment by ShiFoo** [comment]
And maybe: Why should we have this. Just that people have something to do? Are we always expecting hostile counter attacks? Otherwise it is just gonna be an amusement for players...

**Comment by TheGrandVizier** [comment]
@ShiFoo 
This is an ability we had with AGM. It may be returned in a future (very future) version of ace.
What we used to have with AGM was, we had Boxes that could be dragged or deployed, deployment turning them into razor wires, sandbag barriers, etc (box's are pre-designated which obstacle is inside of them, spawnable via zeus). 
This allowed us to establish roadblocks and do all kind of nifty shit, especially in defense scenarios.
In current format it would also give Logistics what to do on top of building the med tent.

Obviously some limitations need to be applied for this to be practically used with our gamestyle.

**Comment by ShiFoo** [comment]
I had a brief look at it. And i must say: if i had to make such functionality myself, i would do it like plank does it. I know it is not suitable for us... yet. I can modify it to our needs and maybe clean something up here and there but starting from scratch would not be the better solution!

**Comment by adios113** [comment]
If MCC will pass trough the tests, then we will not need this, since MCC together with ACE has a fortification building feature.

**Comment by TheGrandVizier** [comment]
@adios113 what does mcc have to do with fortification placement?
afaik ACE only has singular sandbags.

**Comment by abelarno** [comment]
@TheGrandVizier https://www.youtube.com/watch?v=QxNEOnrG9A0

**Comment by TheGrandVizier** [comment]
@abelarno 
MCC is not going in.
Back to the drawing board.

**Comment by adios113** [comment]
Posting here again...

So, here is another ALiVE feature I discovered, that allows us to move, lift, load objects and even tow vehicles. It requires only two Modules to be placed inside the template - "Alive (Required)" and "Player Combat Logistics". Objects can be whitelisted and it is really easy to use - trough action menu.More detailed documentation: http://alivemod.com/wiki/index.php/Logistics_Support
This will solve #221. Works with objects spawned trough Zeus. It is safe to add those two modules to our templates. You will have an occasion to see how it works on Saturday.

**Comment by TheGrandVizier** [comment]
My beef with ALIVE system is multi leveled:

1. I hate the fact we need to use 3(!) different interaction systems. (Ace interaction, ALiVE interaction, scrollwheel interaction).

2. I think we only want certain individuals to be able to deploy stuff, or under certain conditions.

**Comment by wingatex** [comment]
After testing the addon to the templates "plank" it is a good tool and can create awesome bases with it but it is not the way we play and doesn't feel like something we use. It doesn't feel natural as it is a scroll wheel interaction and then the object appears. You can put the objects where you want as shown in the image. http://steamcommunity.com/sharedfiles/filedetails/?id=635266547 . It is also very unatual to "be able to carry this around" to make it worth while base you would need one person to carry a lot of it which is a strech for one person.

**Comment by TheGrandVizier** [comment]
I think nobody intended for this to be used as is.
We talked about the prospect of reverse engineering it and "borrowing" some code from it to make our own "crafting" system.
Am I to understand this is now completely off the table?

**Comment by ShiFoo** [comment]
Regarding your question: I wouldn't say so. Its implementation is pretty straight forward and somehow i would have done it myself. It is a quite complex project though which also needs time. Also, we havent defined any requirements for the base building. Only then i can make up my mind how it could work.

**Comment by TheGrandVizier** [comment]
"As an Engineer,
I would like to have the ability to fortify the medical tent's surroundings or safeguard supplies from stray rounds".

**Comment by LordCavac** [comment]
I haven't found any issues with it so far. As is you can build two of a few types of fortifications (namely sandbags and HESCO constructions). As for in game implementation, personally I would give everyone the ability to place a sandbag fortification with a timer if they have bags in their inventory. Larger stuff would be place-able by engineers within a certain distance of something like the 40 Ton cargo HEMTT transport with a longer timer.

As a mission creator, I would like to see some form of this implemented and I can think of some pretty interesting scenarios utilizing this functionality.

**Comment by adios113** [comment]
Easy workaround is now possible thanks to:

http://ace3mod.com/wiki/framework/cargo-framework.html
http://ace3mod.com/wiki/framework/dragging-framework.html

It can be done in a similair fashion to our Ammo Boxes. Spawnable fortifications trough Zeus, which players will be able to load into trucks and carry, drag them into prefered positions.

**Comment by ShiFoo** [comment]
I would also like to have some kind of crafting mechanism in there. So that resources can be carried around and assembled on site. I dont know if thats viable though.

**Comment by Fourjays** [comment]
Rejected in meeting on 14/03/16, due to poor gameplay fit. We'll be investigating/developing our own system in future.
