### ISSUE TITLE
Investigate alternative "aggressor" mods

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#235]
With the future removal of Leights (#233) and other potential removals we will lose a number of hostile factions, gear and loadouts utilised in ops. We need to try and find some alternative factions. 

One option to consider is some of massi's mods, which appear to fit the desired development standards. All of his collections are listed below, as it is currently unclear exactly what each pack provides, what we want or require:

Middle Eastern Warfare: http://www.armaholic.com/page.php?id=29977
African Conflict: http://www.armaholic.com/page.php?id=21914
PLA Forces: http://www.armaholic.com/page.php?id=29504
ALTIS Guerilla Warfare: http://www.armaholic.com/page.php?id=29378
NATO SF and Russian Spetsnaz Weapons: http://www.armaholic.com/page.php?id=21912
NATO SF and Russian Spetsnaz Vehicles: http://www.armaholic.com/page.php?id=27652
UK Special Forces: http://www.armaholic.com/page.php?id=19345
Russian GRU and OMON Spetsnaz: http://www.armaholic.com/page.php?id=19627
US Marine Corps and MARSOC: http://www.armaholic.com/page.php?id=22749
USSOCOM 75th Ranger, NavySeals DEVGRU and Delta Force: http://www.armaholic.com/page.php?id=19132
Italian Special Operation Forces: http://www.armaholic.com/page.php?id=19050

Due to poor prior experiences with the quality of some massi gear, attention should be focused on ensuring the included gear and weapons is up to standard (particularly obvious faults such as missing sounds).

Inclusion of these mods will also likely be contingent on #234 so as to avoid arsenal bloat.

**Comment by abelarno** [comment]
All of massi's units packs require his weapons and vehicles packs too, wich basically means its a replacement for RHS. That is not what we want I think, because Massi is clearly inferior quality wise to RHS.

In a curated arsenal we could limit the amount of massi gear, so players can only take RHS or mod gear, but for a zeus it could be confusing to see a lot of vehicles double in the spawn list, resulting in mistakes that could potentially ruin an operation.

**Comment by ShiFoo** [comment]
Another thng would be increased loading times... But lets have a look at it first to evaluate its current state.

**Comment by Fourjays** [comment]
@abelarno We're open to suggestions for alternatives on aggressor factions. Must be actively developed and maintained, 1.54+ compatible, compatible with our modset, of a decent visual quality and authentic in appearance.

**Comment by abelarno** [comment]
@Fourjays This might be worth looking at: 
http://www.armaholic.com/page.php?id=29542, 
http://www.armaholic.com/page.php?id=26666 (might require us to make our own opfor units)

**Comment by Fourjays** [comment]
@abelarno Quality is ok-ish, but the spawnable groups they provide are useless (Taliban Fighters are individuals only with no weapons, and Killoch's is vanilla centric). Would require extensive development effort, and we'd have the confusing situation of a load of extra groups that we don't want to use.

**Comment by abelarno** [comment]
@Fourjays Thats true, I'll check out massi's stuff later tonight

**Comment by Fourjays** [comment]
Will change this to a general research thread on aggressors.

**Comment by Fourjays** [comment]
I have checked out IWAR (http://www.armaholic.com/page.php?id=29772). It is of a good quality, but lacks authneticity for "aggressors" as most of the units look like US PMCs.

Also checked out GOS Enemies (http://www.armaholic.com/page.php?id=25738). They again lack authenticity as they are  very generic and feature random elements of vanilla equipment (e.g. Titan).

**Comment by Fourjays** [comment]
I also chcked out CAF Aggressors (http://www.armaholic.com/page.php?id=24441) briefly, but it appears to be abandonware.

**Comment by Fourjays** [comment]
Gave Sub-Insurgents (http://www.armaholic.com/page.php?id=27334) a try and the units aren't terrible, but not awe inspiring either. Is basically a as "close as possible" attempt using RHS/vanilla gear. Similar to what we could achieve by writing our own configs.

**Comment by Fourjays** [comment]
The groups provided by #218, #219 and #220 could also serve as aggressors, but are very conflict specific.

**Comment by Fourjays** [comment]
Gave the first massi modpack a go (Middle East Warfare). Initial impressions were good. Good selection of spawnable factions, they look authentic, produce no errors. The "uniforms" all appear to be of a quality at the same level as Leights Opfor Pack or better. However, it still seems to be let down by the weapons.

At a distance the weapons look good and would make solid "aggressor" weapons. When compared at close range to RHS weapons they are lacking detail, which is only an issue if they are used by players. However, the bigger issue is that the sounds produced by many of the rifles seem to be very generic. This is a far bigger issue than the visual quality as it will impact everyone at all times and not just those who pick up enemy gear.

**Comment by abelarno** [comment]
CUP units devs are saying their next release will probably be coming out in 2-4 weeks, it adds aggressors. They look pretty good:
http://imgur.com/TfrEt6L
http://imgur.com/rRXFLUl
http://imgur.com/ZykiaUz
http://imgur.com/9AmeYFV
http://imgur.com/xZGmMXA
http://imgur.com/fPH8GAY
http://imgur.com/Fv36CcJ

**Comment by ShiFoo** [comment]
They indeed look very promising...

**Comment by abelarno** [comment]
It would mean subscribing to more of CUP tough.
This is the weapon pack, that is for now not as good as RHS:
http://www.armaholic.com/page.php?id=27489

**Comment by adios113** [comment]
Keep in mind, that it's possible to extract single weapons/uniforms from more mods and combine all of them into one addon.

**Comment by abelarno** [comment]
This has just been released:
http://www.armaholic.com/page.php?id=30337

Its EricJ's taliban fighters (http://www.armaholic.com/page.php?id=29542) but then with RHS weapons instead of the CUP ones, meaning its really light weight.

**Comment by abelarno** [comment]
CUP just had a big upgrade releasing the agressors:
https://forums.bistudio.com/topic/179326-community-upgrade-project-cup/page-87#entry2975646

**Comment by Fourjays** [comment]
We'll begin testing CUP as soon as the 08FEB milestone is completed. The current plan, pending any major issues, is to incorporate it into our modpack, replacing many of the existing Arma 2 import mods which are essentially abandoned.

**Comment by Fourjays** [comment]
CUP Units (#297) is being added to provide our aggressor needs and others may be created by ourselves (#239).

Closing as research is now complete.
