### ISSUE TITLE
ACE 3 update to v3.5.0

### ISSUE THREAD

**Issue by abelarno** [blackwatchint/modpack#237]
**Changelog (v3.5.0):**

ADDED:
- Config options for auto downloading ACE from the Steam Workshop
- 3DEN integration of various modules
- Fastroping 
- Advanced Mortar interaction and ammunition handling
- Trench digging 
- Tagging with spraypaint 
- Interaction with portable lamps
- Model for the fuel nozzle
- Deadman switch can now trigger explosives in inventory
- RHS Compat: Add PSO-1M2-1 windage adjust 
- Sandbags are now placeable in the editor
- Optional colorblind wind speed indicator 
- Events for missionmakers added to ACE_Explosives
- Function to detonate explosives via script added to ACE_Explosives 
- Add action to detonate all explosives attached to a detonator 
- Refuel actions to fuel bladder objects 
- Setting to enable Medical Locations to Boost medical Training
- Spectator text chat 
- Added new "Get Out" action that will eject selected civilian from a vehicle
- Added an option to show player names on the BFT module

CHANGED:
- Medical Improvements 
  - Add adenosine to replace atropine effects
  - Add option to enable / disable epinephrine for medics or everyone (basic medical)
  - Add option to allow treat everyone as a medic in medical facility
  - Fix various bugs
  - Fix bandage configuration
- Improved mission load time by recompile on game start
- Optimized load time of various modules with displayLoad XEH
- Darken and improve sandbag texture 
- Better flashbang effects 
- Change the name for wheeled apc 01 cannon from Patria to Badger IFV
- Optimized ACE_Nametags
- Remove Swag Walk Fix, now fixed in Arma itself 
- Remove old ragdoll tweaks, now fixed in Arma itself 
- Optimized various function replacing filter and map with select and apply
- Overhaul and optimization of ACE_Hearing
- Optimized fire handling with the unified fired event handler 
- Overhaul and optimization of ACE_Overheating 
- Reloading no longer unjams weapons by default 
- General cleanup and optimization of the interaction menu 
- Optimized the interaction menu inside vehicles 
- Reserve parachutes are now steerable
- Optimize ACE_Frag and make explosion reflections optional, default off. Greatly improves the performance of ACE_Frag
- Various improvements to the FCS
- Tourniquets now block medication until released
- Free looking in no longer forced while jumping
- Various explosives enhancements in ACE_Explosives
- Move the detonator actions outside the "Detonate" submenu
- Remove VehicleLock Items from Virtual Arsenal
- Unloaded cargo position greatly improved with a custom function
- Can no longer refuel a vehicle with its engine on
- Default font replaced by Roboto
- Spare barrels are no longer added to starting equipment, due to grenades not having enough remaining space

FIXED:
- Fix empty callbacks in medical/repair 
- Handling disconnect and removal of fuel truck 
- Make wound assignment consistent for dll/sqf 
- Remove ace fake weapon from 3den cargo editor
- Don't allow passing mags when not in same vehicle 
- Fixed wrong damage when shooting at units mounted in static weapons and cars
- "setAllGear" - abort function and print warning when used on remote units 
- Fixed error when flashbangs were thrown to the water 
- Fix typo in ACE_Hearing config
- Fix Handgrenade DisplayNameShort to M67 
- Fix ACE_Scopes capturing native adjustment keys for the PSO scope 
- Fix ACE_Goggle changing the tint on the 3den camera
- Fix damage for passengers during vehicle crashes 
- Do not add or remove earplugs if gear should be preserved
- Scopes: Don't show adjustment or play click sound if the adjustment doesn't happen
- Flashsupressor not compatible with .338 rifles
- RHS Compat: fix AB for subsonic ammo
- Fixed ACE_Weather producing wind inversions
- Prevent Tactical Ladder interaction if unit on ladder
- Fix some spectator errors
- Fix the amount of backblast received by the firer via reflection
- Fix module settings for medical litter
- Reduce the chance of interacting through walls
- SwitchUnits conflicts with MenuPosition respawn template 
- Fix rearming vehicles with no remaining ammo
- Fix locked vehicle inventory not being locked
- Wounds are now shown as integer numbers
- Fixed backblast effect when firing from a vehicle
- Fix dragged object been moved to random locations
- Fix corpes not been able to be bagged while the player is respawning
- Fix Javelin conflict with Zeus Remore Control
- Fix unit showing duplicated in the spectator mode unit list
- Removed "Get Down" and "Get Away" actions for civilians in vehicles 
- Prevent the interact menu collapsing during animations
- Fix mines orientations for JIP players

REMOVED:
- Remove BWA3 compat pbo, now included in BW mod
- Disabled ACE_Laser for the Comanche, so DAGR missiles can work with vanilla designators

**Changelog (v3.4.2):**
ADDED:
- Add Adaptation of fnc_makeJerryCan to new interact_menu
- Add support for non local Zeus RC in common-isPlayer
- Add CBA zeus integration

CHANGED:
- Sitting cleanup
- Rearm scope changed for dummy objects
- Explosive enhancements

FIXED:
- Fix M69 Grenade UBC in RHS Compat
- Fix usage of deprectated fired XEH
- Fix ThingX capitalization
- Fix Kill Spectator PFEH when exiting spectator 
- Fix RHS Compat. Fix M113 inheritance
- Fix stringtables merge
- Fix Medical Triagecard Macro
- Fix Third Person Goggle Effect Not Displaying
- Fix Advanced ballstics Eotvos effect
- Fix inverted isTurnedOut for map lighting
- Fix medical menu not closing on range, litter direction
- Fix PT-BR translations and German duplicated entry fix
- Fix RHS Compat fix for SMAW spotting rifle backblast 
- Fix RHS Compat Enhancement for Weapons and Grenades
- Fix Optics - Don't modify camera for ThreeDen Editor
- Fix RHS Compat fix for RU Sprut turret + Disabling FCS for M113 family

REMOVED:
- Remove obsolete hotkey entries
- Remove undefined laser self designate macro
- Remove CUP compat pbo. no longer needed: CUP makes their own cleanup

**Download:** https://github.com/acemod/ACE3/releases/tag/v3.5.0

**Comment by TheGrandVizier** [comment]
Can anyone explain in English what this means:

> "Add support for non local Zeus RC in common-isPlayer (#3052)"

**Comment by Fourjays** [comment]
As I understand, it is just an underlying change to ensure that functionality works across any machine (i.e. local, headless or server).

The relevant issue is here: acemod/ACE3#3052

**Comment by Relvox** [comment]
uploaded (source: ace github)

**Comment by Fourjays** [comment]
ACE v3.5.0 has been released. Edited original issue to reflect this.

**Comment by Fourjays** [comment]
Uploaded v3.5.0 to the test repository.

**Comment by Fourjays** [comment]
Due to the changes listed both the medical and repair/refuel systems should be tested. We also need to test the new or updated features (e.g. fastroping, mortars, trenches, andenosine) to see how they work and identify if loadout changes are required as a result.

**Comment by Fourjays** [comment]
Brief testing hasn't brought up any obvious problems.

Awaiting deployment to the live repository.
