### ISSUE TITLE
Imrali Island update to v1.4

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#245]
v1.3
-Add Normal Map
-Add texture Seabed
-Improve underwater topography
-Remplace all rocks
-Delete Cargo Tower addons

__Link:__ http://www.armaholic.com/page.php?id=26853
__Size:__ 70MB

**Comment by ShiFoo** [comment]
v1.4
- Add Spring version
- Remove misplaced objects

__Link:__ same as above
__Size:__ 140MB

**Comment by Relvox** [comment]
uploaded (source: armaholic)

**Comment by Fourjays** [comment]
Changes deployed to the test repository, awaiting push to live.
