### ISSUE TITLE
Wake Island update to v1.1

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#246]
v1.1
-Add Normal Map
-Add texture Seabed
-Improve underwater topography
-Improve ILS runway for IA
-Delete Cargo Tower addons

__Link:__ http://www.armaholic.com/page.php?id=27321
__Size:__ 86MB

**Comment by Relvox** [comment]
uploaded (source: armaholic)

**Comment by Fourjays** [comment]
Changes deployed to the test repository, awaiting push to live.
