### ISSUE TITLE
Investigate IED behaviour with ALiVE

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#259]
Need to investigate how IED detection and disarmament works with ALiVE, as they do not use the ACE3 explosives system. We must determine areas for adjustment as necessary.

**Comment by Fourjays** [comment]
Some information is available here: http://alivemod.com/forum/358-ied-disarming/0

**Comment by adios113** [comment]
**To be able to disarm an IED, you need to trigger on of these points:**

* Player has to be an "Explosive Specialist" - pref. vanilla unit class.
* Player has to have a specific item in his inventory (default Mine Detector, can be change to ACE_Defusalkit, or anything.)
* Unit has to have "EOD" in its name (not unit description)

**There are two ways of disarming an IED from ALiVE.**

* Action Menu (red-colored "Disarm IED" action)
* Trough a controlled explosion or usage of a big enough caliber by shooting at it

**How to approach the IED?** 
Like usual, by slowly approaching it while prone, close enough, until the action menu option pops out. (tested it myself)

http://alivemod.com/wiki/index.php/IED - More info, but mostly contains what i just wrote.

**Comment by Fourjays** [comment]
Think this can be closed as there isn't anything to research further.
