### ISSUE TITLE
Investigate ALiVE war room and mission persistence

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#260]
Want to investigate the ALiVE war room and mission persistence options available for ALiVE based missions. We need to verify how they work, how they can be applied to our missions and whether they fit with our play style.

**Comment by adios113** [comment]
http://alivemod.com/wiki/index.php/War_Room
http://alivemod.com/wiki/index.php/Persistence

**Comment by adios113** [comment]
Are we going to test it in the near future? (possibly with the current milestone?)

**Comment by Fourjays** [comment]
We will be, yes.

**Comment by Fourjays** [comment]
On hold pending an update to ALiVE that fixes its compatibility issues with CBA v2.3.1.

**Comment by Fourjays** [comment]
Testing can resume as #355 fixed the issues.

**Comment by Fourjays** [comment]
Issue no longer relevant due to modpack reset.
