### ISSUE TITLE
ACRE2

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#266]
We want to investigate a possible switch from TFAR to ACRE2. Need to test the functionality and behaviour of ACRE compared to TFAR, and how well it would integrate with our gameplay style.

Information can be found here: https://forums.bistudio.com/topic/181471-acre2-stable-release/

**Comment by Fourjays** [comment]
ACRE2 has been uploaded to the test repository and server. Testers will need to make sure to use Arma3Sync's ACRE2 Installer to setup the Teamspeak 3 plugin, and to disable the TFAR plugin before testing.

**Comment by Fourjays** [comment]
Some things @wingatex and I have found so far:

- The PTT beeps or tones do not currently work. Enquiring with ACRE2 team about this.
- There are 3 radios that support 100 channels on the same frequencies - one long range, two short range.
- There are another 2 radios with different frequency sets. A basic short range radio and an old fashioned analogue long range.
- Frequency setup is very complicated. Also unnecessary due to 100 channels.
- The terrain occlusion is very strong. Radios within 500m with a large terrain feature between can not communicate.
- Channels can be assigned names that appear on the device. For example, channel 1, group 2 can be named "PLTNET".
- Default key bindings will be problematic. Babel is set to left windows key.
- The inventory radio slot appears to be "blocked". All radios go to uniform/vest/backpack.
- All radios seem to add some degree of noise or static to the transmission, simulating the quality. Is not as crystal clear as TFAR.
- By default all transmissions are "half duplex". This means you can't send a transmission on a frequency/channel while someone else is transmitting.
- There is no "additional" radio channel setting. Two channels requires two radios. Multiple radios are handled similarly to TFAR (Capslock, Ctrl+Capslock, Shift+Capslock, Alt+Capslock).
- Switching between radios is instant. No delay, or pause. No "press, release, press" workarounds.

**Comment by Fourjays** [comment]
- Vehicles do not have a built-in radio (despite online videos appearing to indicate this as a possibility).
- Transmission visual feedback only appears for 3 seconds (potential for unintentional hot mic).

**Comment by Fourjays** [comment]
Still need to investigate:
- Cause of PTT beep/static issue. Appears to be a local configuration issue as some report hearing them.
- If there is any way to enable long range radios in vehicles.
- If Zeus RC'd units can not be spoken through.
- How diving comms work with ACRE.

**Comment by Fourjays** [comment]
- Zeus RC'd units definitely can't be spoken through.
- When diving, all radios and speech function as if above ground.
- Care must be taken to not PTT before the prior sender has released their PTT - message will not be sent.

So far general impression is that ACRE feels clearer and more responsive for ordinary land comms. It just misses some details such as vehicle and diving radios, as well as useful features such as speaking through RC'd units. Will also require an adjustment from players due to the half duplex system - speakers must be allowed to finish before others speak, and people must also be wary of creating hot-mic situations.

**Comment by TheGrandVizier** [comment]
Actors will have to act using their actual selves. Not the end of the world.

**Comment by Fourjays** [comment]
Another thing I've just remembered to mention... when you are in-game with ACRE enabled, all out-of-game people in the channel are inaudible. Unlike TFR, this occurs regardless of the TS channel selected.

**Comment by Fourjays** [comment]
A reasonably bad issue with ACRE right now is that when an individual has two of the main radios (i.e. 148, 152 or 117) and transmits, their FPS will drop by 5-10. The number of radios on the person (perhaps on all persons, was testing alone) seems to have an impact on the size of the FPS drop.

**Comment by Fourjays** [comment]
Adoption of ACRE is pending the release of their next version, which should address the FPS issues.

**Comment by Fourjays** [comment]
Issue no longer relevant due to modpack reset.
