### ISSUE TITLE
Remove RH Accessories, M4s & Pistols

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#292]
The RobertHammer mods are to be removed due to their low-level of developer activity. The modpack will require testing with them removed to check dependencies and content loss.

 - RH Acc Pack
 - RH M4/M16 Pack
 - RH Pistol Pack

**Comment by Fourjays** [comment]
We have a number of M4s and M16s from RHS, as well as pistols. CUP Weapons (#295) contains numerous pistols as well.

The Accessories are the only concerning item here. Not sure on what scopes are included with CUP, but the RH Accessories are used throughout our loadouts.

**Comment by ShiFoo** [comment]
... and i hoped this milestone would be less work for templates/loadouts :-/

**Comment by Fourjays** [comment]
Changes deployed to the test repository, awaiting push to live.
