### ISSUE TITLE
CUP Weapons

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#295]
**Description:**
CUP Weapons contains all the weapons, assault rifles, machine guns, shotguns, grenade launchers, pistols, sniper rifles, and whatever else goes “boom” in ArmA 2 and the expansion and DLC’s. All weapons are stripped of their attachments where possible, and these have been turned into attachable scopes, lasers, flashlights, and bipods interchangeable with the vanilla content.
Some of the weapons are new or derived from the original ones.

**Download:** http://cup-arma3.org/downloads/cup-weapons/
**Size:** 1.1GB

Note we will also require the ACE3 Compatibility Mod, listed on the same page.

**Comment by Fourjays** [comment]
This mod will be tested on the test server, as it will have a wide ranging impact on the rest of the modpack.

**Comment by Relvox** [comment]
uploaded (source: steam)

**Comment by Fourjays** [comment]
Not every weapon has been tested, but tests on random weapons have not demonstrated any obvious issues.

Ready for deployment to the live repository.
