### ISSUE TITLE
CUP Vehicles

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#296]
**Description:**
CUP Vehicles contains all the vehicles from ArmA 2 and the expansion and DLC’s. All vehicles are ported with ArmA 3 standards and features.

**Download:** http://cup-arma3.org/downloads/cup-vehicles/
**Size:** 2.4GB

Note we will also require the ACE3 Compatibility Mod, listed on the same page.

**Comment by Fourjays** [comment]
This mod will be tested on the test server, as it will have a wide ranging impact on the rest of the modpack.

**Comment by Relvox** [comment]
uploaded

**Comment by Fourjays** [comment]
All tested vehicles appear to be behaving as expected.

Awaiting deployment to the live repository.
