### ISSUE TITLE
CUP Units

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#297]
**Description:**
CUP Units contains all the units of the original ArmA 2 and Arrowhead as well as the DLC. Right now, there are a lot of placeholder units that do not look like the original ones but are instead stand-ins using default ArmA 3 uniforms and CUP equipment. Some units might still be placeholders using current ArmA 3 vanilla gear – they will be replaced later. All uniforms and vests are compatible with vanilla content, meaning that you can mix vanilla and CUP content.

**Download:** http://cup-arma3.org/downloads/cup-units/
**Size:** 748MB

**Comment by Fourjays** [comment]
This mod will be tested on the test server, as it will have a wide ranging impact on the rest of the modpack.

**Comment by Relvox** [comment]
Uploaded

**Comment by adios113** [comment]
With addition of CUP Units, we may no longer require BWIMod, the British 3BAF modpack and PMC, since CUP adds those factions.

**Comment by Fourjays** [comment]
Quite a few of the CUP Units are still works in progress, and while their quality may be good for filling many of the "gaps" in our modpack, they may not live up to the quality of dedicated Arma 3 mods.

**Comment by Fourjays** [comment]
One known issue with this is that a number of factions feature placeholder (vanilla) content at this time. Examples include the UN and UK factions.

We'll be deploying despite the known issue. Up to date on the test repository, waiting for deployment to live.
