### ISSUE TITLE
Remove RobertHammer items from the loadouts

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#301]
Due to #292 the loadouts have to be scanned for items prefixed "RH_" and replaced with alternatives.
As far as i can see, this effects __every__ faction we have.

**Comment by Fourjays** [comment]
Hold off on this until testing is complete on #292 and #295 and we know exactly which content is available.

**Comment by ShiFoo** [comment]
Changes committed. Closing.
