### ISSUE TITLE
 Convert templates to 3D editor

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#305]
All templates need converting to the new 3D editor. This is so members can easily use our templates for 3D editor missions, and so that we are prepared for when the 2D editor is removed in "Apex".

**Comment by Fourjays** [comment]
Worth noting that when trying to import our templates it throws an error and won't load in the 3D editor. This seems to be because there is no "Player" unit, only "Playable". Adding a "Player" unit allows it to be opened in the 3D editor.

**Comment by adios113** [comment]
With addition of 3DEN, description.ext file is partialy obsolote - mission parameters like respawn, no save option and such. Make Sure to delete them from the description.ext and leave the file only for configuration purposes and `disableChannels[]={0,1};` setting.

**Comment by Fourjays** [comment]
The 3D editor is reportedly breaking the virtual slots for the headless clients (see https://forums.bistudio.com/topic/188371-eden-destroying-headless-client-setup/). We will hold off on making the 3D templates until this is fixed by Bohemia.

**Comment by TheGrandVizier** [comment]
@adios113

**Comment by adios113** [comment]
All settings that are now editable in game, are under "Attributes" Menu in 3DEN.

**Comment by adios113** [comment]
Arma 3 HotFix from 03.03.2016 is supposed to fix the issue with 3DEN and HC's. Can we check it again, if problem occurs?

**Comment by ShiFoo** [comment]
Might be that the HC issue is fixed. Last time i checked it was fine. But Jays reported that some mods are not working with the new 3D templates and are spewing errors. I know that the LHD from CUP is not working at all.

**Comment by Fourjays** [comment]
Tentatively marking this for next milestone. At some point we may have to just proceed and workaround any mod-specific issues.

**Comment by ShiFoo** [comment]
Ok, this would include to deactivate the Wasp teleporter because it is broken with the the 3D templates.

**Comment by adios113** [comment]
Could we spawn the Nimitz and the Wasp via script if it's not possible to spawn via 3den yet?

**Comment by Fourjays** [comment]
I think we'll have to hold off on any move to 3DEN for now. We can easily move from 2D to 3D, but not the other way.

**Comment by ShiFoo** [comment]
I agree. Lets not do it this milestone... Even though i would like to have it in this one. But i don't feel comfortable with the switch yet.

**Comment by Fourjays** [comment]
As previously discussed with @ShiFoo, we will now be upgrading templates to 3DEN having found a workaround for some of the issues. This _may_ resolve #372.

**Comment by ShiFoo** [comment]
Done with #348. More details in that issue.
