### ISSUE TITLE
BWMod Update to v1.3.2

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#308]
Changelog:
v1.3.2
- added: P2A1 flare pistol
- added: compatability with 3DEN.
- added: democracy box can now be slingloaded
- fixed: DM25 and DM35 no longer fly through walls
- changed: Navipad now stays open after using your scope
- fixed: muzzle flash in the virtual arsenal
- fixed: last round in magazine didn't produce muzzle flash
- fixed: holster animation for P8 and MP7
- removed: modules (replaced with object attributes)

__Link:__ http://www.armaholic.com/page.php?id=24147
__Size:__ 768 MB

**Comment by Relvox** [comment]
uploaded (source: https://bwmod.koffeinflummi.de/BWMod_A3_v1.3.2.zip)

**Comment by adios113** [comment]
With addition of CUP Units, we may no longer require BWIMod, since it contains German Units and Vehicles.

**Comment by Fourjays** [comment]
Changes deployed to the test repository, awaiting push to live.
