### ISSUE TITLE
N'ziwasogo Update to v0.8

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#310]
v0.8
 - Added many trees all over the map and patches of dense foliage along the roads.
 - The aim is to offer more concealment in general for guerilla/Coin scenarios.
 - Changed name to G.O.S N'ziwasogo in the editor.

**Download:** http://www.armaholic.com/page.php?id=24455
**Size:** 527MB

**Comment by Relvox** [comment]
uploaded (source: armaholic)

**Comment by Fourjays** [comment]
Changes deployed to the test repository, awaiting push to live.
