### ISSUE TITLE
Research reloading for non-BAF static weapons

### ISSUE THREAD

**Issue by TheGrandVizier** [blackwatchint/modpack#322]
Static weapons are a mess.
I am not sure which is what, and what should and should not be used, how it should be used, what is and is not reloadable, etc.

Could we please have customized boxes, like the ammo ones, containing deployable statics and relevant ammo?

I understand that the non-BAF deployables do not have proper ammo units. Is there a solution at all to reloading these?

Thanks!

**Comment by Fourjays** [comment]
Created action item for new ammoboxes with #324.

Renamed this issue to focus on research.

**Comment by Fourjays** [comment]
All deployable static weapons can be reloaded via the ACE resupply system. However it is not consistent with the way vehicles are loaded or neccessarily practical.

Once a static weapon has used it's ammunition, you must go to the truck and select to take ammo for the static weapon. You may then go to the weapon and reload it using the ammo you just carried. This may not be repeated to add more magazines - you must subsequently return to the truck, carry another magazine and then use it.

**Comment by TheGrandVizier** [comment]
Could we get around this by making a crate that behaves like a resupply truck, that can be placed adjacent to a static weapon, eliminating the need for walking back and forth?

**Comment by Fourjays** [comment]
Maybe? Would need a lot of research and effort, that may not be worth it given the rarity of us using static weapons.

**Comment by Fourjays** [comment]
Created action item for investigating a static ammo resupply crate at blackwatchint/addons#3.

Closing as research completed.
