### ISSUE TITLE
Gear Reconciliation

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#323]
As already discussed in private convo with FJ and partly in the last meeting, we might want to iterate the current gear. I would like to collect some points that are open for discussion:

- Reduce amount/remove 40mm HE grenades from PL/APL. (Remove the 3GL completely?) Also serves the purpose to reduces space due to the LR radio backpack.
- Remove Demolition Block from (P)RTOs and (A)PL. Why should they have them?
- Give "standard" personnel white smoke and Leadership positions coloured smoke.
- Increase amount of smoke nades for the CFR.
- Does every loadout need a pistol?
- Are we happy with the amount of smoke nades / 40mm smokes / 40mm HE / 40mm flares in our roles?
- How many spare rockets should be available for the russian MAT (RPG7V2) loadouts?

**Comment by TheGrandVizier** [comment]
My take:

- I think Leaders having GL's is an important incentive to play the role. Cerven will not give up his GL.
- Agree, only FTL/SL should have a breaching charge. Perhaps even only FTLs.
- Agree
- Agree
- No, it doesn't. I think pistols are a must for AR at least.

**Comment by Fourjays** [comment]
Regards the 40mm for PL and APL, it is a matter of practicality. They can't carry all the 40mm ammo in the radio backpack, as well as things they actually need. This is why we repeatedly have problems with PL loadouts missing critical equipment such as medical.

**Comment by TheGrandVizier** [comment]
Wont the removal of the demo block allow enough space for a few 40mm rnds?

**Comment by ShiFoo** [comment]
Maybe for some factions. A faction where it is almost critical everytime is the SEALS - scuba. The missing vest makes it difficult to shift items around. And the radio backpack has limited capacity, of course.. Right now, the PL is missing some mags and smokes. The removal of the demo block will free up some space but, as far as i can remember, it wont be enough. If we agree, that this role has not the full gear, i'm fine but i would like to make it work for every faction/role.

**Comment by TheGrandVizier** [comment]
Oh well, at least we saved some weight :dancer:

**Comment by ShiFoo** [comment]
Added point of grenae/40mm quantities. It seems kind of random currently. Are we happy where we currently are?

**Comment by TheGrandVizier** [comment]
Original logic of what I can recall:

**Comment by adios113** [comment]
Just my insight on the top question:


  *  Reduce amount/remove 40mm HE grenades from PL/APL. (Remove the 3GL completely?) 
    Also serves the purpose to reduces space due to the LR radio backpack.
 > For PL/APL - sure, I don't see a reason they need those. They barely have a chance to use their rifle, not talking about GL.
    
  * Remove Demolition Block from (P)RTOs and (A)PL. Why should they have them?
> Same as up

 * Give "standard" personnel white smoke and Leadership positions coloured smoke.
> Got no problem with that. Why not.

* Increase amount of smoke nades for the CFR.
> For what reason and to how many?

* Does every loadout need a pistol?
 > Definitevely YES. Saved my life so many times. This question shouldn't be even asked.


 
Are we happy with the amount of smoke nades / 40mm smokes / 40mm HE / 40mm flares in our roles?
> Yes. No too much, not to few. Actualy, more flares (doesnt have to be 40mm flares) for standard roles would be useful.

**Comment by Fourjays** [comment]
Every role should retain white smokes. They are essential for cover while moving. Coloured smokes for PL/SL/FL/RTO only would make sense to a degree, although even a rifleman could find a green smoke useful in certain situations.

**Comment by TheGrandVizier** [comment]
I used Green smoke as Rifleman to visually confirm a CCP.

**Comment by Fourjays** [comment]
Generally speaking, I think it is important that for every faction/role that we consider the balance of its loadout, the resupply options we now have and what an individual faction/role requires for their tasks.

**Comment by ShiFoo** [comment]
Added point: How many spare rockets should be available for the russian MAT (RPG7V2) loadouts?

**Comment by TheGrandVizier** [comment]
I think rockets should be a direct derivitive of weight, so, depends on which launcher, which rockets?

**Comment by Fourjays** [comment]
I think the best way for us to tackle this is by first going through existing loadouts and identifying areas that need adjustment:

1. Loadouts with extremely limited space.
2. Loadouts pushing limits of carryable weight.
3. Loadouts with superfluous or illogical gear for the role.

**Comment by Fourjays** [comment]
Going through the USMC loadouts, here are my thoughts:

- All units need medical increase with new platoon structure (#348).
- Query whether every role needs:
  - Pistol?
  - Chemlights?
  - IR grenades?
  - Laser?
  - Silencer?
- Redistribute 40mm rounds between leaders and grenadiers. Currently 8 HE, 5 smokes,1 flare. Make it 5 HE, 3 smokes, 1 flare for leaders. Current values for grenadiers?
- Platoon Leader is full. Remove 40mms entirely or severely reduce?
- Give Fireteam Leader the "Android" cTab device?
- Give all fireteam members the "MicroDAGR" cTab device?
- Replace blood with plasma/saline in medical roles (prep for future ACE updates)?
- Give the new "CFR" the corpsman loadout minus the surgery kit?
- Rangefinder for assistant roles instead of Vector?
- MAT team features 8 rockets in total. Reduce to 4-6?
- PL, LMG, MMG, MAT, AA, Sniper are all over 35kg+.

Thoughts on faction-to-faction differences:
- Modern loadouts should feature MicroDAGR as minimum for all roles.
- Add low-tech/old-era variants of loadouts with less tech available.
- Suggestion from members for SAS/KSK/Spetnatz loadouts.
- Special forces loadouts (black ops, SEALs, etc) should naturally vary from the norm. Either very task oriented (SEALs), light (black ops?) or prepared for anything (SAS).
- Ensure every faction has appropriate variety in any secondary weapons (pistols, launchers).

It is unfortunately pointless trying to compare IRL equipment too strictly (as someone did above). The weights often don't match up, and even when they do we have the arbitrary space requirements to deal with. What we can do is ensure each faction and role's loadouts match with the tasks they are destined to carry out, and provide us with a fair variety in terms of gameplay differences.

**Comment by TheGrandVizier** [comment]
> Redistribute 40mm rounds between leaders and grenadiers. Currently 8 HE, 5 smokes,1 flare. Make it 5 HE, 3 smokes, 1 flare for leaders.

For PL, I think HE is not required and he can make do with Smoke / Flare rounds.

> Give Fireteam Leader the "Android" cTab device?
Yes Please

> Give the new "CFR" the corpsman loadout minus the surgery kit?
Yes Please

> Rangefinder for assistant roles instead of Vector?
VERY yes please!

> MAT team features 8 rockets in total. Reduce to 4-6?
Also very yes.

> PL, LMG, MMG, MAT, AA, Sniper are all over 35kg+.
I think Launcher guys (MAT, AA) can spare some "defaultgear", like chemlights, IR grenade, etc.

**Comment by Fourjays** [comment]
Chemlights and IR grenades are not going to make a difference to a 35kg loadout.

**Comment by Fourjays** [comment]
Checked through UK and Russian loadouts. They generally suffer the same issues as the USMC, except in the case of the Russian's they are very tight on vest and backpack space.

**Comment by ShiFoo** [comment]
__All units need medical increase with new platoon structure__
I would suggest 6 packing and elastic, 10 field dressings, 10 CQs. This gives them enough buffer to not ask for MEDEVAC immediately, but when they run out, they can quickclot to patch up for the EVAC

__Query whether every role needs__
Apart from the pistol and the IR grenade, i would say the rest is neccessary to have. Quite unemotional regarding the pistol. I dont mind if we get it removed for most of the classes.

__Redistribute 40mm rounds between leaders and grenadiers__
Proposed quantaties look fine for me.

__Remove 40mms entirely or severely reduce?__
Some PLs like using the 3GL. I would say that reducing it to other leadership levels is ok.

__Give Fireteam Leader the "Android" cTab device?__
YES

__Give all fireteam members the "MicroDAGR" cTab device?__
NO. Not a fan of this idea.

__Replace blood with plasma/saline in medical roles (prep for future ACE updates)?__
Errr, did i miss something (future ACE updates?). Otherwise saline never had the same effect as blood. Currently, i dont see why we should change it.

__Give the new "CFR" the corpsman loadout minus the surgery kit?__
If the CFR can treat can wounded on-site without a full MEDEVAC, i would say that CM-loadout minus SurgeryKit is ok. Still concerned that the surgeon on the FOB will be a very boring role. Now, Corpsman have to stitch and watchs vitals while giving blood and such. It will be a left-click-only role and nothing else. But i was wrong being salty about the last big corpsman revamp. So i am curious how this plays out.

__Rangefinder for assistant roles instead of Vector?__
Why exactly?

__MAT team features 8 rockets in total. Reduce to 4-6?__
A well functioning MAT team should be able to hit at least 4 out of the 6 rockets. This could potentially disable 3-4 vehicles. If there is resupply, it is good.

__PL, LMG, MMG, MAT, AA, Sniper are all over 35kg+.__
Do you consider 35kg too much? I don't see your concern...

>Thoughts on faction-to-faction differences:

__Modern loadouts should feature MicroDAGR as minimum for all roles.__
I don't really know why you want this. We are more and more moving to giving everyone the goodies  It started with zoomed scopes. Ok, it had a certain need because ALiVE missions or ASR AI were fighting on longer range.

__Add low-tech/old-era variants of loadouts with less tech available.__
For all loadouts? I am confused... what is your thinking behind this. Could you explain with an example?

__Ensure every faction has appropriate variety in any secondary weapons (pistols, launchers)__
Still confused. For example: we don't really have an alternative to the MAWWS. Sorry, but i can't follow your thoughts on these points.

**Comment by Fourjays** [comment]
@TheGrandVizier and @ShiFoo. These are points of query that I've thought of after spending two afternoons going through the loadouts invidually. They are points that will be raised in a future meeting where we can discuss it in detail. Let's not turn Github into a discussion board.

**Comment by Fourjays** [comment]
Learned that the types of night vision goggles we have have varying amounts of static. We might want to consider varying it according to the "tech level" of each faction. We currently use a lower-tech variant for all factions.

**Comment by Fourjays** [comment]
Following meeting and discussions on 29/03/2016, the action items have been created with #361, #362, #363, #364, #365, #366, #367, #368 and #369.
