### ISSUE TITLE
Werthles Headless Kit update to v1.5

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#328]
**Changelog:**
No changelog... 

**Download:** http://www.armaholic.com/page.php?id=29455
**Size:** 1MB

**Comment by Fourjays** [comment]
Thread here (https://forums.bistudio.com/topic/184485-werthles-headless-module/) indicates the update is related to attempt to workaround the issues with 3DEN and headless clients. Unclear on any other changes.

**Comment by ShiFoo** [comment]
Are wo going to implement the mod version? The script is at http://www.armaholic.com/page.php?id=28917 but i dont see that it has been updated because it has a different version history than the mod equivalent...

**Comment by Fourjays** [comment]
We'll keep using the script version. Sure there hasn't been any changes?

**Comment by ShiFoo** [comment]
Yes, i used a diff-tool to compare both files. They are identical.

**Comment by Fourjays** [comment]
Ok, we'll close this then.
