### ISSUE TITLE
Re-position USS Nimitz on affected templates

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#329]
USS Nimitz lists various positioning issues that can cause glitches as reported with #207. We should ensure the USS Nimitz is within map bounds and rotated to a direct N/W/E/S angle on all templates that feature it. If a map does not have enough room to reasonably permit this (e.g. VT5), we should consider whether the map requires a Nimitz or not.

**Comment by ShiFoo** [comment]
Changes committed. Closing.
