### ISSUE TITLE
Add LHD to templates

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#330]
The addition of CUP Vehicles (#296) has introduced the USS Wasp LHD (Landing Helicopter Dock). Templates featuring a USS Nimitz should also feature a USS Wasp nearby, with an appropriate teleporter link located at the spawn.

Details can be found here: https://docs.google.com/document/d/1iXjN0pLlbJ51n5e4SoKR00491WkbHpbhFxbVyTEkwxk/edit

**Comment by Fourjays** [comment]
Tentatively marking for next milestone, but could be pushed if time doesn't permit.

**Comment by ShiFoo** [comment]
The LHD is totally bugged. It will spawn the object on sea level but everything else is on ground level (under water)!

http://steamcommunity.com/sharedfiles/filedetails/?id=638435413
http://steamcommunity.com/sharedfiles/filedetails/?id=638435463

**Comment by Fourjays** [comment]
Probably because it doesn't support the 3D editor yet.

**Comment by ShiFoo** [comment]
Following the conversation with Jays:
Confirmed, the Wasp is not compatible with 3D editor. Reverting templates back to 2D.
Implementing the "empty" version of the Wasp. Predefined aircrafts are likely to bounce and explode when being entered.

**Comment by ShiFoo** [comment]
Following list of vehicle should be placed on the Wasp.
2x AH-1Z (one CAS, one Multi Role), 2x CH-53 (RHS or CUP), 2x UH-60, maybe 1x Huey

**Comment by ShiFoo** [comment]
Changes committed. Closing.
