### ISSUE TITLE
Porquerolles Island

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#333]
**Description:**
This terrain tries to be as close to the real Porquerolles Island as we possibly could. The height map and vegetation is based on the real world island.

Being originary from the south of France and in the vicinity of Porquerolles, with the help of [V]Xnam who made Angel Island, I took over the modelling of the Porquerolles Island which is the biggest and most to the west in the Hyères islands. It's forming an arc oriented east-west with jagged coasts.
The highest point in the island is the Semaphore at 142m.

I hope you'll enjoy playing on the island as much as I enjoyed making it!

**Download:** http://www.armaholic.com/page.php?id=30553
**Size:** 179MB

**Comment by Ludvigroosen** [comment]
Gonna take a look and leave a review today.

**Comment by Ludvigroosen** [comment]
So i tested the map Porquerolles Island. The map looked good in the 3D editor when i did a fly over, many elevation point and very promising buildings, when i flew over the "Harbor" it felt a bit like "Kavala" from Altis so i feel this map is unnecessary.  When i spawned a unit and went in to him and ran around i found some visual things that i hated (Pictures in [link](http://imgur.com/a/EABDE/all)). There seems to be no problems with our current modpack with this map but i don't like it at all so will give it a big no and rate it. 3/10

**Comment by LordCavac** [comment]
I disagree with roosen, especially with a 3/10 rating as a 3/10 on most standard out of ten ratings a three means not functional, however I digress about that.

I would compare it more to a larger, less buggy Gorgona with nice open relatively flat fields for Zeuses to build on if they are feeling so inclined, but plenty of interesting environments already in the map. The city environment is one of my more favorite out of all the Arma cities, I don't know how to describe why though, its sort of like the roads are more open and the alleys are more compact than in most other city environments. I don't know, it just feels more (modern?) in city design. I would love to see this map in the modpack and I really don't understand why roosen does not like it. The visual issues he points out don't seem like things that people would notice in the course of normal gameplay to me.

**Comment by LordCavac** [comment]
Map was updated April 02, most changes were performance improvements and a few of the fields were emptied out for more of a mission maker sandbox area. Nothing of substance was really changed however and my opinion is still unchanged.

**Comment by Fourjays** [comment]
An updated version of this map has been released (23rd May): http://www.armaholic.com/page.php?id=30553
Includes adjustments of existing objects, so may be worth checking again to see if any prior complaints have been resolved.

**Comment by Fourjays** [comment]
Another update has been released on 5th June, which includes further changes to object positions and textures: http://www.armaholic.com/page.php?id=30553

We'll give it one final pass.

**Comment by Fourjays** [comment]
Rejected in the meeting on 20/06/2016 due to consistent quality concerns.
