### ISSUE TITLE
3den Enhanced

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#336]
__Description:__
This modification adds new functionalities to 3den, without creating any dependencies for players. That means, mission builder can use this mod to make their lifes easier without making the lifes of the players harder by forcing them to download additional mods.

__Features:__
advanced skill settings for units
advanced damage settings for vehicles
advanced damage settings for units
captive attribute
activate gunlight attribute
ambient animations attribute
ambient combat animations attribute
random patrol
one click clear cargo
one click clear inventory
one click remove weapons
on click add full Arsenal
restore loadout on respawn (playerable units only)
enable music while editing
and much more..

__Download:__ http://www.armaholic.com/page.php?id=30461
__Size:__ 1MB

**Comment by TheGrandVizier** [comment]
So, is this like... Ares for Eden?

**Comment by adios113** [comment]
Yep, something like that. It basicaly adds additional options to be selectable trough attributes, instead of putting them trough scripts.

**Comment by Fourjays** [comment]
I'm not clear why this is even a suggestion... it says it is pure clientside with no mod dependency once the mission is exported?

**Comment by ShiFoo** [comment]
Oh, i did not realize that. Some of these kind of mods are dependent serverside (e.g. XCam). I assumed it would be the same here.
