### ISSUE TITLE
Missing weapons in loadouts

### ISSUE THREAD

**Issue by Ludvigroosen** [blackwatchint/modpack#337]
Seems like there's something wrong with the load outs 

- USMC 
Missing Side Arms on both load outs
- US Army
Missing Side Arms on both load outs
- Blackops
Misses both guns (Primary gun and Side Arm)
- Bundeswehr
Missing Side Arms on both load outs
- US 1985
Misses both guns (Primary gun and Side Arm)
- SEALS Scuba 
Misses both guns (Primary gun and Side Arm)
- UN
Missing Side Arms on both load outs
- Taliban
Missing Side Arm
- Independent
Missing Side Arms on both load outs

**Comment by Fourjays** [comment]
This sounds like an old template with the new modpack.

**Comment by Fourjays** [comment]
Confirmed in conversation with @Ludvigroosen that this was using an old template.
