### ISSUE TITLE
SMD Sahrani A3

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#340]
**Description:**
Sahrani, the original terrain from Bohemia Interactive's "Armed Assault" is being lovingly brought up to current standards and beyond. M1lkm8n and myself have spent countless hours documenting and fixing placement issues, bugs, and shortcomings of the terrain. Further, M1lkm8n has opened, improved, or port forwarded 100's of BI buildings and objects. Special attention has been paid to every minor detail and that same faithful attention to detail will be continued as I take the project forward.

**Download:** http://www.armaholic.com/page.php?id=27437
**Size:** 940MB

**Comment by Fourjays** [comment]
From looking into the thread on Bohemia Interactive's forums, it seems the developer of this has joined the CUP team and will be bringing any future changes/updates to the CUP version.

**Comment by Ludvigroosen** [comment]
I read true the BI spot quickly and found [https://forums.bistudio.com/topic/175705-smd-sahrani-a3-bohemias-sahrani-terrain-as-ported-by-smd/page-15#entry2957167](url) i would say that we do an evaluation on the maps visual etc. I can do a review on both map and then we can make a desicion.

**Comment by Fourjays** [comment]
Rejected in the meeting on 14/03/16. Key benefits that we're interested in appear to be coming to the CUP Terrains version in future.
