### ISSUE TITLE
Remove duplicate weapon attachments

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#342]
The LLM Mk3 Flashlight has a built-in IR laser that can be toggled by Ctrl+L. So the spare IR laser attachment is not needed.
This effects all factions except Bundeswehr and US1985.

**Comment by Fourjays** [comment]
I'd like a little more verification on the impact of this keybind wise. Don't want people unable to use it because of duplicate keybinds, different keybinds, etc.

Is this keybind available via vanilla options or a mod? Is it the default keybind? Can it be rebound?

**Comment by ShiFoo** [comment]
Default is Ctrl+L, can be rebound via Configure > Configure Addons > Ace Weapons > Switch Laser / IR Laser

**Comment by Fourjays** [comment]
Which mode is the device in by default?

**Comment by ShiFoo** [comment]
I believe it was the flashlight.

**Comment by TheGrandVizier** [comment]
Confirm, default flashlight.
CTRL+L to toggle, but,, then must press L again to switch on.

**Comment by ShiFoo** [comment]
The old flashlights were roberthammer and have been removed.

**Comment by Fourjays** [comment]
We'll go ahead and do this. Just need to make sure training department is aware so they can instruct new members on how to switch.

**Comment by ShiFoo** [comment]
Changes committed. Closing.
