### ISSUE TITLE
WHK transfers cause reduction in clothing

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#346]
When an AI is transferred from Zeus to a Headless Client, they will sometimes lose their clothing and/or weapons.

**Comment by Fourjays** [comment]
According to a Steam workshop comment from the WHK developer, this can be caused by a small amount of desync in the transfer process. They recommend adjusting settings so there is more time between transfers and fewer transfers are made at a time.

**Comment by TheGrandVizier** [comment]
I have gotten a naked transfer when it was the only unit spawned on the server.
I would argue has nothing to do with amount per cycle although sure a convenient excuse for them.

**Comment by Fourjays** [comment]
As I understand it, we're talking desync between server and HC. At the point of transfer, the HC has yet to "register" the contents of the units inventory (including clothes, weapons, etc). Once it is transferred to HC, the version the HC has becomes distributed to everyone else - hence they become naked.

**Comment by Fourjays** [comment]
@Ludvigroosen is going to make some test templates to try different settings.

To change the settings we just need to edit the WerthlesHeadless.sqf call at the top of the init.sqf file. It currently uses these settings:

```sqf
[true,30,false,true,30,3,true,[]] execVM "BWI\scripts\WerthlesHeadless.sqf";
```

In order these settings are:

1. Runs repeatedly if true. Runs at mission start only is false.
2. Time between repeated runs (seconds).
3. Debug availability (false is admin/host only).
4. Advanced balancing of units between multiple HCs.
5. Delay after mission loads before executing (seconds).
6. Additional time between groups transferred to reduce bad unit transfers caused by desyncs (seconds).
7. Display initial setup report after first cycle.
8. Array of additional phrases to look for when checking for units to ignore. Unit names, group names, current transport vehicles, modules synced to units and class names are all checked.

**Comment by Ludvigroosen** [comment]
Template's are created, modified and uploaded to the server. Value's are following.

[true,30,false,true,30,3,true,[]] execVM "BWI\scripts\WerthlesHeadless.sqf"; - Basic Template
//[true,30,false,true,60,20,true,[]] execVM "BWI\scripts\WerthlesHeadless.sqf"; - 144.units.11.Altis
//[true,30,false,true,60,20,true,[]] execVM "BWI\scripts\WerthlesHeadless.sqf";  - 144.units.22.Altis
//[true,60,false,true,30,30,true,[]] execVM "BWI\scripts\WerthlesHeadless.sqf"; - 144.units.33.Altis
//[true,10,false,false,20,40,true,[]] execVM "BWI\scripts\WerthlesHeadless.sqf"; - 144.units.44.Altis
//[true,20,false,true,15,5,true,[]] execVM "BWI\scripts\WerthlesHeadless.sqf";  - 144.units.55.Altis
//[true,5,false,true,5,5,true,[]] execVM "BWI\scripts\WerthlesHeadless.sqf"; - 144.units.66.Altis
//[true,40,false,true,40,10,true,[]] execVM "BWI\scripts\WerthlesHeadless.sqf"; - 144.units.77.Altis
//[true,5,false,false,5,5,true,[]] execVM "BWI\scripts\WerthlesHeadless.sqf"; - 144.units.88.Altis

**Comment by Fourjays** [comment]
Been doing some testing with this myself today. Appears that simply increasing the 6th option to 10 seconds fixes the issue. We'll probably increase the first value to 50 seconds as well:
```sqf
[true,45,false,true,30,10,true,[]] execVM "BWI\scripts\WerthlesHeadless.sqf";
```

**Comment by Fourjays** [comment]
As there's no way to test this fully without just using it, we will proceed with the settings in the comment above for now.

**Comment by ShiFoo** [comment]
Change committed to develop. Closing.
