### ISSUE TITLE
Implement new Platoon structure

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#348]
We will be switching to a new "Flexible Platoon Structure" in future. All templates will need adjusting accordingly. The new structure is currently planned as follows, subject to minor changes: https://www.dropbox.com/s/fr577btqkt7bhdy/Flexible%20Platoon%20Structure.png?raw=1

**Comment by Fourjays** [comment]
We will likely complete #305 as a result of these changes as well.

**Comment by adios113** [comment]
Additional adjustment needs to be made in order to make #356 work:

- Zeus Modules need to be named.

**Comment by Fourjays** [comment]
Full slotting list:
- Platoon
  - Platoon Leader
  - Platoon Sergeant
  - Platoon Corpsman
- Alpha
  - Squad Leader
  - Fireteam Leader
  - Grenadier
  - Automatic Rifleman
  - Anti-Tank Rifleman
  - Fireteam Leader
  - Grenadier
  - Automatic Rifleman
  - Anti-Tank Rifleman
- Bravo
  - Squad Leader
  - Fireteam Leader
  - Grenadier
  - Automatic Rifleman
  - Anti-Tank Rifleman
  - Fireteam Leader
  - Grenadier
  - Automatic Rifleman
  - Anti-Tank Rifleman
- Charlie
  - Squad Leader
  - Fireteam Leader
  - Grenadier
  - Automatic Rifleman
  - Anti-Tank Rifleman
  - Fireteam Leader
  - Grenadier
  - Automatic Rifleman
  - Anti-Tank Rifleman
- Medevac
  - Combat First Responder
  - Combat First Responder
  - Combat First Responder
- Engineering
  - Combat Engineer
  - Combat Engineer
  - Combat Engineer
- Rear Echelon 1
  - Rifleman
  - Rifleman
  - Rifleman
- Rear Echelon 2
  - Rifleman
  - Rifleman
  - Rifleman
- Vehicle Crew 1
  - Commander
  - Gunner
  - Driver
- Vehicle Crew 2
  - Commander
  - Gunner
  - Driver
- Vehicle Crew 3
  - Commander
  - Gunner
  - Driver
- Vehicle Crew 4
  - Commander
  - Gunner
  - Driver
- Air Crew 1
  - Pilot
  - Copilot
- Air Crew 2
  - Pilot
  - Copilot
- Air Crew 3
  - Pilot
  - Copilot
- Air Crew 4
  - Pilot
  - Copilot
- Technical
  - Game Master
  - Assistant Game Master
  - Actor 1
  - Actor 2

**Comment by ShiFoo** [comment]
I hope that we dont run into space problems here. These are significantly more slots than the old one. I see that space on some island maps could be critical (Gorgona, Imrali, Bozcaada, ...).

**Comment by Ludvigroosen** [comment]
Is there a possibility to stack all the units on the same place for all 3 factions? 
We dont play any PVP based Operations so i cant see any issues on doing it thia way. 

Up to iFu how he wanna do it :)

**Comment by ShiFoo** [comment]
__We dont play any PVP based Operations so i cant see any issues on doing it thia way.__
That is not *entirely* true. And stacking them would even make more of a mess than we already have. The best approach would be to insta switch between sides, but as already discussed in another issue, that brings a lot of problem that could potentially break gameplay.

**Comment by ShiFoo** [comment]
[BWI]Template now incorporates the new platoon structure in 3DEN format.

Necessary changes that need to be done manually:

__description.ext__
- Remove "respawn"
- Remove "respawnDelay"
- Remove "disableAI"
- Remove "enableDebugConsole"
- Remove "respawnbutton"

__In 3DEN editor:__
**Attributes->General**
- Presentation -> Title is "[BWI]<mapname>
- Presentation -> Author is "Black Watch International"
- States -> all checked
- States -> Debug Console = Available for the host or logged-in admin
- Misc -> Independents Allegiance: Hostile to west and hostile to east
- Misc -> Uncheck Binarize the Scenario File

**Attributes->Multiplayer**
- Type -> Game Type: Cooperative Mission
- Lobby -> Enable AI: uncheck
- Respawn -> Respawn: Respawn on Custom Position
- Respawn -> Uncheck all but "Show respawn counter"
- Respawn -> Respawn Delay: 10 seconds
- Respawn -> Show Scoreboard: check
- Respawn -> Allow manual respawn: uncheck

Scenario file will only be binarized if release has been branched and stamped.

**Comment by ShiFoo** [comment]
All templates done.

**Comment by Fourjays** [comment]
As previously discussed, please make sure the scoreboard is off:

> Respawn -> Show Scoreboard: **uncheck**

**Comment by ShiFoo** [comment]
I can't recall the "previously discussed" part but i will change it.

**Comment by ShiFoo** [comment]
Platoon Corpsman spawn with PL loadout. To be fixed.

**Comment by ShiFoo** [comment]
Corpsman initial loadout call fixed.

**Comment by ShiFoo** [comment]
Pending:Restore TFAR module on templates.

**Comment by ShiFoo** [comment]
New platoon structure deployed. Closing.
