### ISSUE TITLE
GPS cannot be picked up from fallen soldier

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#35]
I had it multiple tiems now that i wasnt able to pick up the GPS from fallen FTL. You see it in the inventory but drag & drop or right mouse click won't work. has also been reported by sammy in yesterdays op. Can't tell whether this happens after a specific time or what triggers this.

**Comment by adios113** [comment]
I noticed that, for example, you cannot manage inventory while playing a
reload animation. That and inside of vehicle are the only instances i know
when inventory stops responding

**Comment by adios113** [comment]
yo, guys dont comment trough blackwatch's  email, cause its says  that i wrote that.


This bug is known since months, probably BIS' fault.

**Comment by Fourjays** [comment]
The same problem occurs with the Map item (not an issue usually, but noticed it when we played one of those "escape" missions).

**Comment by ShiFoo** [comment]
Sadly, accessing dead player inventory is not really working. Workaround: Use onPlayerKilled event to spawn a GPS on the coordinates of the dead body, if the dead player had a GPS in the first place.

Necessity and/or release TBD.

**Comment by ShiFoo** [comment]
We had this issue again in yesterdays op. Maybe we got used to live with it, but that doesn't make it any less annoying. Are we going to tackle this problem or not?

**Comment by ShiFoo** [comment]
Just to make sure we are on the same page: The workaround has not yet been committed, but i can implement it fairly quick for testing. Which brings me to the next point: I really dont have a proper test case for this issue because the cause of this bug is not known. Might need a "field test" with a live mission.

**Comment by Fourjays** [comment]
Testing wise I think it just needs the testers to do a test run with it on the server to ensure it all works on the server and it is practical in difficult environments (ground level vegetation). After that it can be discussed at the officer's meeting for inclusion across all templates.

Can you make a template (Chernarus) available on the server for testing it?

**Comment by ShiFoo** [comment]
ok, it will be available for testing today or tomorrow

**Comment by ShiFoo** [comment]
Testtemplate has been deployed to the server. GPSTest on Chernarus.
I want the testers to confirm a couple of points:

- When a player with a GPS dies, he drops an additional GPS
- When a player without a GPS dies, nothing additional happens
- The GPS is spawned on the exact location of the player *before* he became a ragdoll.
-   - If he was sitting on a grenade and his body is getting propelled for one meter ( rather rare occurence ), the GPS should be in his initial position ( also the gun would be there! )

As a conclusion: The GPS should either be in the list when opening the inventory on the dead player ( should then list 2x GPS ) or at least where the gun is.

**Comment by Fourjays** [comment]
Moving to backlog for now. Has been approved for inclusion but we require considerable testing before it can go ahead.

**Comment by Fourjays** [comment]
Still need to confirm if this is an issue or not. Reports differ from person to person.

Is possible it could also be resolved via the inclusion of cTab (#156).

**Comment by Fourjays** [comment]
Not heard any reports of this issue occurring for a while now. Can we verify if it is still an issue?

**Comment by ShiFoo** [comment]
Yes, i can verify it. Had multiple occasions that someone wasnt able to pick up the cTab device aswell. We are still "living with it", but its an issue nonetheless!

**Comment by Fourjays** [comment]
The cTab devices technically don't need to be in the GPS slot. They work fine from the backpack. Doesn't help for the radio and map though (those last happened pre-1.54, not since).

**Comment by TheGrandVizier** [comment]
The workaround appears to be much more simple.
Drag the item you want to loot to the "Ground" tab.
Click Ground tab.
Loot GPS / Radio / cTab.

Source: BI forums threads (multiple)

**Comment by wingatex** [comment]
I havent found this to be an issue since you can go through ACE and CTab

**Comment by ShiFoo** [comment]
Its also about the cTab device. If you assume command of your fireteam and want to pick up the cTab receiver and it wouldnt let you. I think we could close this because Niks workaround seems to be working. I wasn't able to confirm it myself, tho.

**Comment by Fourjays** [comment]
I'll close this for now. We'll reopen if the issue persists in future.
