### ISSUE TITLE
Alter Armory organisation to reflect new Platoon structure

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#350]
The Armory loadout organisation should be altered to be more intuitively aligned with the flexible platoon structure and how it functions.

**Comment by Fourjays** [comment]
I will try to submit sketches or ideas on how to achieve this within the next week.

**Comment by Fourjays** [comment]
My suggestion for this would be for the groups to be elements or types of elements within the platoon structure. Then the roles within those categories. For example:
- Platoon
  - Leader
  - Sergeant
  - Surgeon
- Squad
  - Leader
- Fireteam
  - Leader
  - Grenadier
  - Automatic Rifleman
  - Anti-Tank Rifleman
- Fireteam (MMG)
  - Automatic Rifleman
  - Assistant Automatic RIfleman
- Fireteam (MAT)
  - Assistant Anti-Tank
  - Anti-Tank

How difficult would it be to have loadouts that don't exist for a specific faction hidden or greyed out?

**Comment by ShiFoo** [comment]
Ok, the restructuring is simple. Hiding the unavailable roles would require to define all of them for every faction. It is possible but makes the script a bit harder to maintain. If it is needed, it can be done, though.

How would you like the Armory to look like, if the FTL is selecting a team loadout? Your current structure doesn't really give much opportunity for it. We either make a second screen or incorporate it into the existing structure.

**Comment by Fourjays** [comment]
I think hiding them might be worth the effort. If only because right now players take the message that is displayed as "it is not working" rather than "it's not meant to be there".

See #351 regards team loadouts.

**Comment by adios113** [comment]
Additional adjustment needs to be made in order to make #356 work:

- Zeus Modules need to be named.

**Comment by ShiFoo** [comment]
Ok, i took a closer look at this. Sadly, it raises some more problems. The loadout selection is based on indices. I cant hide or grey entries out. The only solution is to remove the entry entirely but this would scramble the indices. I can only make the error messagemor explicit for now.

**Comment by Fourjays** [comment]
Guess that will have to do then.

**Comment by Fourjays** [comment]
Full role list:
- Platoon
  - Platoon Leader
  - Platoon Sergeant
  - Platoon Corpsman
- Squad
  - Squad Leader
- Fireteam
  - Fireteam Leader
  - Grenadier
  - Automatic Rifleman
  - Anti-Tank Rifleman
- Fireteam (MMG)
  - Automatic Rifleman
  - Assistant Automatic RIfleman
- Fireteam (MAT)
  - Assistant Anti-Tank
  - Anti-Tank
- Fireteam (HAT)
  - Assistant Anti-Tank
  - Anti-Tank
- Medevac
  - Combat First Responder
- Engineering
  - Combat Engineer
- Rear Echelon
  - Team Leader
  - Rifleman
- Rear Echelon (Logistics)
  - Driver
- Rear Echelon (Fire Support)
  - Gunner
  - Assistant Gunner
- Rear Echelon (Recon)
  - Designated Marksman
  - Spotter
- Rear Echelon (Sniper)
  - Sniper
  - Spotter
- Rear Echelon (TACP)
  - Radio Transmitter Operator
  - Spotter
- Vehicle Crew
  - Commander
  - Gunner
  - Driver
- Air Crew
  - Pilot
  - Copilot
- Other
  - Joint Terminal Attack Controller
  - Explosive Ordnance Disposal
  - Radio Transmitter Operator

The bracketed groups could be done as individual groups (as above) or as sub-groups like so:
- Fireteam
  - Fireteam Leader
  - Grenadier
  - Automatic Rifleman
  - Anti-Tank Rifleman
  - MMG
    - Automatic Rifleman
    - Assistant Automatic Rifleman

Groups could also include the full set of loadouts, although this introduces a lot of duplication:
- Fireteam
  - Fireteam Leader
  - Grenadier
  - Automatic Rifleman
  - Anti-Tank Rifleman
- Fireteam (MMG)
  - Fireteam Leader
  - Grenadier
  - Automatic Rifleman
  - Assistant Automatic Rifleman

**Comment by Fourjays** [comment]
Just realised, there should be two groups for Air Crew (rotary and fixed wing) in that list.

**Comment by ShiFoo** [comment]
First changes committed. Faction/role preselection in initPlayerLocal pending.

**Comment by ShiFoo** [comment]
Coding part is done so far. Needs testing to eliminate bugs

**Comment by ShiFoo** [comment]
Testing did not reveal any problems. Closing.
