### ISSUE TITLE
Add Armory group loadout distribution

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#351]
As suggested by and discussed with @ShiFoo, we'd like to create an additional selection option on the BWI Armory that allows a team loadout to be selected. This would allow a Fireteam Leader to choose "MMG Team" and have their whole fireteam kitted out accordingly.

**Comment by Fourjays** [comment]
UI wise I think this should be an additional section in the armory for "groups" that appears for leaders of the appropriate options only:
- (etc)
- Fireteam (MAT)
  - Assistant Anti-Tank
  - Anti-Tank
- Groups
  - MMG Team
  - MAT Team
  - (etc)

Alternatively, have a separate UI interface specifically for the group loadouts, but that is probably more effort than it is really worth.

**Comment by ShiFoo** [comment]
First functionality could be tested.

**Comment by ShiFoo** [comment]
Development work done. Closing.
