### ISSUE TITLE
ALiVE incompatible with CBA v2.3.1

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#353]
The latest version of ALiVE is incompatible with the latest version of CBA, as previously mentioned in #281.

**Comment by Fourjays** [comment]
Waiting on a hotfix release from the ALiVE team.

**Comment by adios113** [comment]
New ALiVE update came out today:
https://github.com/blackwatchint/modpack/issues/355

**Comment by Fourjays** [comment]
Needs testing to see if it fixes the issues as expected.

**Comment by Fourjays** [comment]
#355 appears to fix this issue. Will be released in next update. Closing as fixed.
