### ISSUE TITLE
ZEC - Zeus and Eden Templates

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#354]
**Description:**
ZEC is a mod aimed at expanding the pre-built compositions available within Eden/Zeus to the mission maker. The mod only uses vanilla objects and requires no additional mods running on other clients or the server.

**Download:** http://www.armaholic.com/page.php?id=30590
**Size:** 1MB

**Comment by wingatex** [comment]
I very much want this, dosent seem to have any issues and has loads of diffrent options

**Comment by Fourjays** [comment]
Gave this a quick look. Not much to say, it is a lot of object compositions. It's only small, but unsure how much use it'd really be. We already have a lot of compositions via vanilla Arma, Ares and ALiVE that don't get used very often, with mission makers often composing their own instead.

http://steamcommunity.com/sharedfiles/filedetails/?id=650522737
http://steamcommunity.com/sharedfiles/filedetails/?id=650522905
http://steamcommunity.com/sharedfiles/filedetails/?id=650522827
http://steamcommunity.com/sharedfiles/filedetails/?id=650522953
http://steamcommunity.com/sharedfiles/filedetails/?id=650523056
http://steamcommunity.com/sharedfiles/filedetails/?id=650523118
http://steamcommunity.com/sharedfiles/filedetails/?id=650523178
http://steamcommunity.com/sharedfiles/filedetails/?id=650523237

**Comment by LordCavac** [comment]
They work? I don't see why this would need to be in the modpack because I can add them into a mission via editor then just save it and I don't need the modpack anymore for the server connection. It is a nice tool if you want to customize the map a bit, but just seems like bloat for the non-mission makers.

**Comment by Fourjays** [comment]
Accepted in the meeting on 29/03/2016.

**Comment by Fourjays** [comment]
Added to the test repository, awaiting deployment.
