### ISSUE TITLE
ALiVE Update to v1.0.1.16

### ISSUE THREAD

**Issue by adios113** [blackwatchint/modpack#355]
**Changelog:**
Hotfix 1.0.1.1603161 - fixes a critical issue related to Mil_IED that caused ArmA3 to crash to desktop in certain situations.

v1.0.1
[MAIN] Raised compatible clusterbuild for A3 Version: 1.56.134787
[sys_indexer] Fix issue where stuck in map view for object categorization
[MIL PLACEMENTs] Added Field HQ! Explanation below!
[X LIB] Added Function: ALIVE_fnc_findNearObjectsByType, pretty useful: returns all objects of given type within radius. Works with P3D name AND config class (f.e. to be used with typeOf). Very useful for building[__pos, 500, ALIVE_militaryBuildingTypes + ALIVE_militaryHQBuildingTypes] call ALIVE_fnc_findNearObjectsByType
[X LIB] Improved ALiVE_fnc_getNearestObjectInArray with lazy evaluation
[MIL INSURGENCY] Removed obsolete placeholder module (already done in staging, doesnt need to be cherry picked)
[sup_command] Fixed RPT UI errors ("cannot load control")
[MIL C2ISTAR] Fixed task "clear the town" was instantly cleared on dedicated server
[MIL CQB] Fixed issue with null-groups sometimes being kept in CQB for some time until GC collected them
[SUP COMMAND] Fixed object-leak when spectating an OPCOM group and player was killed
[SUP COMMAND] Corrected syntax for BIS_fnc_MP "call" parameter
[sup_command] Optimized tablet performance
[sup_command] Fixed stringtable references
[sup_command] Changed map-click profile selection radius to be dynamic based on map-zoom
[sup_command] Fixed missing semicolon
[sup_command] Fixed corrupted marker bug, optimized loading of ops interface, switched createMarker to drawLine
[X LIB] Improved debug to show the calling function if ALiVE_fnc_HashGet retrieved wrong input values
[X LIB] Fixed error due to wrong input param check in landAtRemote and landRemote (CS threw a script error on heli transport -> land)
[Main] Full index of Kunar Province
[Main] Kalu Khan Index - 75%
[Main] Kalu Khan index - WIP
[Tasks] Some fixes
[X LIB] improved performance of ALiVE_fnc_SortBy by using deleteAt again
[X LIB] Added Inpput validation in various remote-functions to fix da Freeze!
[VARIOUS | XLIB] Fixed broken BIS_fnc_SortBy and changed to ALiVE_fnc_SortBy!
[sys_indexer] Added debug for Friznit
[sys_indexer] Added key press to continue after static data generation and before map completion.
[Map Index] Kunduz re-indexed, please test
[sys_indexer] Added support for using a custom map bound within the module settings. Once indexed, the value must be added to the main staticData.sqf file.
[sys_Indexer] Converted Tuplindexinator to Indexing module. Use ALiVE key to access Map indexing
[Map Index] Added Chernarus Winter
[Tuplindexinator] Improved logging, added support for A2 Chernarus static data
[indexer] remove diags
[Tuplindexinator] Improved camera angles, dump object list to log
[Main] Updated Indexing Object Blacklist (Chernarus)
[Main] Indexing Object Blacklist
[SUP CS | C2ISTAR] Fixed support options (Combat Support and Player Resupply) were accessibly via ALiVE tablet even though the defined items on the modules wouldn't allow it!
[MISSIONS] Fixed ALiVE Sabotage to work with new CLIT ALTIS index
[MIL C2ISTAR] Updated taskSabotage to work with new CLIT indexes (incl. fallback for older indexes)
[Tuplindexinator] Fixed case sensitivity issues
[MIL C2ISTAR] Changed: Task Sabotage building was selecting lampposts and other weird tall objects. Changed to primarily selecting buildings with the most indoor building positions (to prefer f.e. big military offices and HQs) at the objective, and if no useful buildings are found fallback to random houses within 500m of objective (f.e. for A2 non enterable buildings).
[Tuplindexinator] Added a boolean value to ALiVE_fnc_indexMap that indicates if a default staticdata should be us["path\myaddon_map.pbo", true] call ALiVE_fnc_indexMap
[ALiVEClient] Updated
[ALiVE Map Indexer] First version ready for testing
[VARIOUS] Fixed occassion of an error where ALiVE_fnc_AllCurator was undefined. Refactored and removed ALiVE_fnc_AllCurators completely
[UI] Updated UI to work with CBA 2.3 hotfix that includes ability to hook into initDisplay
[Tuplindexinator] Prototype complete.
[Tuplindexinator] Remove debug test
[Tuplindexinator] Updates
[MIL CQB] Fix for CQB debug "CQB ERROR: No House was defined for CQB group <NULL-group>"
[Tuplindexinator] Updated static data dialog
[Tuplindexinator] Updated cam script
[tuplindexinator] Added WIP UI for static data
[MapIndex] Reindexed Altis for 1.56
[MapIndex] Reindex of Stratis for 1.56
[Tuplindexinator] Fixed incorrect variable. Added static object function.
[Tuplindexinator] Added compiled DLL
[xlib] Removed spheres from debug function as they spam the RPT
[Tuplindexinator] End to end index (with prepopulated static data) still WIP
[Tuplindexinator] DEPLOYED! WIP
[ALiVEClient] DeWRP and object parsing automated in extension
[sys_profile] Fixed profile speed modifier module setting
[sup_combatsupport] Fixed issue where incorrect classname was used for invisible helipad
[extensions] Committed ALiVEPlugIn and ALiVEClient
[extensions] removing extensions to get rid of submodule
[sup_combatsupport] Fixed precedence in code replacement
[sys_stats] Fixed issue where nil was being passed to shots fired.
[Map Index] Re-indexed Stratis to avoid exploding helicopters
[mil_CQB] Fixed issue where spawning of units did not look up unit blacklist.
[Main] Stratis reindex
[sys_profiles] Removed debug code
[sys_profiles] Fixed issue where identically named groups would conflict
[C2ISTAR] Fixed UI errors due to changed RscButton class
[C2ISTAR] Fixed issue where incorrect side was returned for tasks
[sup_combatsupport] Fixed UI issue with buttons
[xlib] Improved random group function to handle issues if ALiVE group mappings are incorrect
[Main] Fixed RHS insurgent group mappings

**Download:** http://www.armaholic.com/page.php?id=23684

**Comment by Fourjays** [comment]
Please remove any # references when posting changelogs. They show up as references to our own issues (and can never be removed).

**Comment by Fourjays** [comment]
Need to determine if this fixes #353 or not.

**Comment by Fourjays** [comment]
Can confirm this fixed #353.

Uploaded to the test repository, waiting deployment.
