### ISSUE TITLE
Create group ID selection UI

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#359]
We wish to implement a UI for selecting the group IDs that appear on cTab or BluFor tracker. The UI should offer a predefined list of IDs based on the groups and units available via the flexible platoon structure (#348).

Would be best implemented as an action on the ACE interaction menu, descending directly into the selectable groups (for consistency with "Team Management"). Practicality of this method depends on exact number of selectable IDs, or ability to group the IDs into submenus.

Alternatively, a single ACE action or scroll wheel action that launches a simple UI to select the group ID.

Tentatively listing as a template feature, although exact implementation may necessitate a move to blackwatchint/addons.

**Comment by ShiFoo** [comment]
Which entries should be available in the predefined list?

**Comment by Fourjays** [comment]
Thinking something like this, broken into logical sub groups that can be used or not used depending on eventual UI implementation:
- Basic
  - Platoon
  - Alpha
  - Bravo
  - Charlie
  - Delta
  - Echo
- Support
  - Medevac
  - Casevac
  - Medical
  - Engineering
  - Logistics
- Specialized
  - MMG
  - MAT
  - HAT
  - EOD
  - TACP
  - Recon
  - Mortar
  - Artillery
  - Fire Support
- Armor*
  - Hammer
  - Thor
  - Thunder
- Air*
  - Sparrow
  - Blackbird
  - Bluejay

There is some redundancy in this list, to give us some flexibility in exactly what we use. The ones marked with an asterisk are examples right now, as I'd like to incorporate the callsigns members frequently use for these elements.

**Comment by ShiFoo** [comment]
GUI done. ACE interaction integration pending.

**Comment by ShiFoo** [comment]
Changes done. Can be tested...

**Comment by ShiFoo** [comment]
Functionality test ist fine. One remark: two groups cannot have the same name. Group1 is called Alpha , group2 is called Bravo. Bravo Leader selects Alpha from the GroupID Menu -> Alpha and Bravo will swap Group names. This can be a problem with Weapon Teams like MMG, etc.

**Comment by ShiFoo** [comment]
Added to support multiple groups with the same purpose:
"MMG 1";
"MMG 2";
"MAT 1";
"MAT 2";
"HAT 1";
"HAT 2";
"EOD 1";
"EOD 2";
"Recon 1";
"Recon 2";

**Comment by ShiFoo** [comment]
Functionality test complete. Closing.
