### ISSUE TITLE
Adjust anti-tank loadouts

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#367]
The quantities of rockets for anti-tank loadouts are to be adjusted, on a faction-to-faction basis, to be in line with the following guidelines:

- [x] MAAWS rounds to be reduced to max of 6 amongst the team.
- [x] RPG rounds to be remain at a max of 8 rounds amongst the team, space and weight permitting.

Anti-tank loadouts should have their launcher checked for faction accuracy. The following list will be updated as checked:

- [x] Replace USMC MAT launcher with the SMAW.
- [x] Ensure any loadouts using the SMAW include spotting rifle ammunition.

**Comment by ShiFoo** [comment]
Is the SMAW reloadable? Wasnt it a single shot tube?

**Comment by Fourjays** [comment]
It's a reloadable launcher from what I understand.

**Comment by Fourjays** [comment]
Confirmed the SMAW is reloadable. The aiming round for the SMAW's spotting rifle can also be reloaded.

**Comment by Fourjays** [comment]
None of the applicable loadouts will hold the desired number of rounds. Have included as many as possible for now.

**Comment by Fourjays** [comment]
Changes tested and verified for all loadouts via #410.
