### ISSUE TITLE
UH-1Y Venom causes clientside crash

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#371]
Report from a member that the UH-1Y Venom Transport and MEV helicopters will cause the game to crash when they are entered, and that the helicopter blades are messed up.

**Comment by Fourjays** [comment]
Confirmed that the UH-1Y spawns with contorted rotors and causes a clientside crash when spawned via Zeus. When placed via the editor, the issue is not occuring.

**Comment by Fourjays** [comment]
On further testing (gathering data to pass on to the CUP team) the issue is not occuring. I've tried a fresh map load, remote controlling a unit first and restarting the game - I have been unable to reproduce it since the first test.

We need to do some more testing to determine the exact circumstance that leads to the glitch and subsequent crash.

**Comment by Ludvigroosen** [comment]
First time i spawned it true Zeus it looked like [this](http://imgur.com/a/xwdgB).
After a reload of Arma the issue didn't show up anymore. Tested this thru Zeus, 2D Editor, 3D Editor and a merge thru 2D to 3D editor non of the helicopters were bugged. Even went onto the server and spawned one thru Zeus but no luck. My thought is that this is a one time thing on the first spawn of the object.

RPT download is linked true Megafileupload if you need it. 
[Megafileupload](http://www.megafileupload.com/6pfy/arma3_2016-03-30_20-21-39.rpt)

**Comment by Fourjays** [comment]
We need to confirm this is a pure CUP issue. @Ludvigroosen you need to get together with someone who hasn't yet spawned one of these helicopters (perhaps @abelarno), run CUP vehicles only (copy @BWI_Vehicles, remove any files not starting with CUP_) and see if it can be reproduced.

**Comment by Fourjays** [comment]
I don't think this is limited to first time runs. In doing testing of a mod I'm working on I've had this reoccurring with UH1Y's placed in 3DEN.

**Comment by Ludvigroosen** [comment]
After about 10 minutes i figured out that "United States Corps" UH-1Y Venom Transport is getting 2 chopper blades if they are packed. 1 is correct and one is over the pilot.. When unpacking the correct chopper blade disappers.. [Here](http://imgur.com/k2ZtFTw).

I were able to reproduce it with this helicopter. Tested 13-14 Swedish time for log purpose

**Comment by Fourjays** [comment]
Will be resolved by removal of CUP (#384).

**Comment by Fourjays** [comment]
Issue no long relevant due to CUP removal (#384).
