### ISSUE TITLE
Zeus sometimes not available on slotting

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#372]
Had reports via members of the first Zeus slot being broken on Chernarus, as well as similar issues with the Zeus slots on Altis.

**Comment by Ludvigroosen** [comment]
Had this issue when i tried to help Cadias. Is the issue with the standard template's?

**Comment by ShiFoo** [comment]
Mh... i usually make the platoon structure and its modules on the [BWI]Template and copy it to the other maps. So either every template works are none at all. Weird that only some seem to be affected. I need details on this...

**Comment by Ludvigroosen** [comment]
Sure thing, gonna test this directly when i get home!

**Comment by Fourjays** [comment]
My suspicion is that it isn't the slot itself, but the clientside loading of Zeus randomly failing. If so, I'd expect the slot to start working simply by quitting to the lobby and rejoining in the same slot.

**Comment by Ludvigroosen** [comment]
Can't find any issue's with the template's on Stratis, restarted the mission 2 times, switched slots 4 times and did the same thing on Bozcaada. @ShiFoo 

There is a issue with Zeus, but there is no knowledge of what. I think it might be the 3D editor (Had problems with my rerun that was created in the 3D editor). Would say next person who gets it will need to fill up some sort of report on the information on what he did when it stopped working.

**Comment by Fourjays** [comment]
I doubt it is the 3D editor as our templates don't use it yet. More likely to be a 2D editor thing, although if you've had it on a 3D editor mission then that is ruled out too.

**Comment by Fourjays** [comment]
This is still occurring, but have yet to find any evidence (RPT or otherwise) as to the cause of the difficulties.

**Comment by Ludvigroosen** [comment]
Had this problem on the "Test - Server" yestoday.

**Comment by ShiFoo** [comment]
If you reload the template it works again. Another fact is that once Nik was able to enter Zeus mode and reslotted again, i tried to use the first Zeus slot and it did not work for me. After, like a couple of minutes, it suddenly worked. Totally weird.

**Comment by Fourjays** [comment]
I know this issue initially occured with the 2D templates, but it is occuring in a more specific manner with the 3D templates now that has allowed me to determine the probable cause - the 3DEN update.

With templates created in 3DEN, only the first person to take a Zeus slot has Zeus access. Subsequent players are unable to access Zeus.

A workaround for now is to respawn, after which Zeus will function normally again.

**Comment by Fourjays** [comment]
Issue no longer relevant due to modpack reset.
