### ISSUE TITLE
Black Ops Weapons 80s 90s

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#373]
**Description:**
I've made all the weapons playable with some minor bugs (hand animation mainly) so I thought it would be nice to have some feedback and maybe hope that someone would make a mission with them.

**Download:** http://www.armaholic.com/page.php?id=30698
**Size:** 29MB

**Comment by PalmersPhil** [comment]
downloaded them and took a look. yet another set of weapons I think. nothing special, the pistols are the best part of it, though we utilize them little anyway :)

**Comment by abelarno** [comment]
This mod requires the CUP weapons map. The mod still seems to work tough. The weapons only work with its own accessories, and are not that high quality. 

Even tough the mod works without CUP, I don't recommend using it. It could cause bugs that I have not found. The weapons are not special enough either to risk it, or to dig in the code to see where CUP is needed.

**Comment by Fourjays** [comment]
Rejected in the meeting on 20/06/2016 due to quality and CUP requirement.
