### ISSUE TITLE
HLC AK Pack Update to v2.0

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#376]
v2.0
- Conformed mod icons,mod.cpp to rebranding
- Soundshaders implemented, minor discretionary sound tweaks
- AK12 series, RPK12 reanimated
- 60Round Coffin-mags added in support of RPK12.
- RPK12 mesh - 
+ 60-Round Coffin Mag replacing 45-round RPK74 mag
- All AK12 meshes-
+ Offset mounts added, replace under-side mounting of accessories	
- Added: 
hlc_rifle_ak74_MTK	
hlc_rifle_aks74_MTK	
hlc_rifle_aks74_MTK	
hlc_rifle_ak74m	
hlc_rifle_ak74m_gl	
hlc_rifle_aks74u_MTK	
hlc_rifle_aek971_mtk	
hlc_rifle_RK62
hlc_rifle_slr107u	
hlc_rifle_slr107u_MTK	
- Arsenal Icons implemented
- Grenade sight accuracy improved(all). Should hit more or less Bang on for respective zeroings.	
- Implemented Animated zeroing.
- Removed duplicate inventory slots. Adheres the CBA/ASDG standard almost entirely. 
- Optional RHS and CUP compatibility patches updated to reflect most current versions respectively
- Assorted Material adjustments.

__Link:__ http://www.armaholic.com/page.php?id=25099
__Size:__ 197 MB

**Comment by Fourjays** [comment]
Update uploaded to the test repo, ready for deployment.
