### ISSUE TITLE
HLC AUG Pack Update to v1.5

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#377]
v1.5
- Conformed mod icons,mod.cpp to rebranding
- Soundshaders implemented, minor discretionary sound tweaks
- Arsenal Icons implemented
- Removed duplicate inventory slots. Adheres the CBA/ASDG standard almost entirely. 
- Optional RHS and CUP compatibility patches updated to reflect most current versions respectively
- General Material changes. RVMAT Fresnels altered for better effect, less dependency on generic maps.	

__Link:__ http://www.armaholic.com/page.php?id=27928
__Size:__ 58 MB

**Comment by Fourjays** [comment]
Update uploaded to the test repo, ready for deployment.
