### ISSUE TITLE
HLC AR15 Pack Update to v1.8

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#378]
v1.8
- Conformed mod icons,mod.cpp to rebranding
- Soundshaders implemented, minor discretionary sound tweaks
- Arsenal Icons implemented
- Grenade sight accuracy improved(all). Should hit more or less Bang on for respective zeroings.
- Removed duplicate inventory slots. Adheres the CBA/ASDG standard almost entirely. 
- Optional RHS and CUP compatibility patches updated to reflect most current versions respectively
- General Material changes. RVMAT Fresnels altered for better effect, less dependency on generic maps.

__Link:__ http://www.armaholic.com/page.php?id=26299
__Size:__ 199 MB

**Comment by Fourjays** [comment]
Update uploaded to the test repo, ready for deployment.
