### ISSUE TITLE
HLC G3 Pack Update to v1.9

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#379]
v1.9
- Conformed mod icons,mod.cpp to rebranding
- Soundshaders implemented, minor discretionary sound tweaks
- Arsenal Icons implemented
- Grenade sight accuracy improved(all). Should hit more or less Bang on for respective zeroings.
- Removed redundant inventory slots. Adheres the CBA/ASDG standard almost entirely. 
- Optional RHS and CUP compatibility patches updated to reflect most current versions respectively
- General Material changes. RVMAT Fresnels altered for better effect, less dependency on generic maps.
- PSG1 and HK53/HK51 character animations redone. One to exist, one to not be terrible anymore.
- Added:
hlc_rifle_hk33a2
hlc_rifle_hk33a2RIS
hlc_rifle_psg1A1
hlc_rifle_PSG1A1_RIS
hlc_rifle_g3a3v
hlc_rifle_hk53RAS

__Link:__ http://www.armaholic.com/page.php?id=26021
__Size:__ 93 MB

**Comment by Fourjays** [comment]
Update uploaded to the test repo, ready for deployment.
