### ISSUE TITLE
HLC FAL Pack Update to v1.8

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#380]
v1.8
- Conformed mod icons,mod.cpp to rebranding
- Soundshaders implemented, minor discretionary sound tweaks
- Arsenal Icons implemented
- Grenade sight accuracy improved(all). Should hit more or less Bang on for respective zeroings.
- Removed redundant inventory slots. Adheres the CBA/ASDG standard almost entirely. 
- Optional RHS and CUP compatibility patches updated to reflect most current versions respectively
- General Material changes. RVMAT Fresnels altered for better effect, less dependency on generic maps.
- hlc_rifle_osw_GL no longer accepts bipod
-Added:
*IMPORTANT*
SOME INHERITANCIES HAVE BEEN ALTERED. IF YOU HAVE REFERRED TO CLASSES IN THIS PACK, PLEASE DOUBLE CHECK class CHILD : PARENT RELATIONSHIPS	

__Link:__ http://www.armaholic.com/page.php?id=26029
__Size:__ 54 MB

**Comment by Fourjays** [comment]
Update uploaded to the test repo, ready for deployment.
