### ISSUE TITLE
R3F French Weapons Pack

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#389]
**Description:**
R3F French Weapons Pack is a french's army weapons and accessories addon. This pack contains high definition models without any game performance decrease. It's a ported version of our Arma 2 R3F Armes addon, using Arma 3 new possibilities.

**Download:** http://www.armaholic.com/page.php?id=20128
**Size:** 159MB

**Comment by Fourjays** [comment]
This was provisionally accepted in the meeting on 11/04/2016, pending testing.

**Comment by abelarno** [comment]
Quality wise its nice gear. Looking good with some nice animations. It adds some cool heavy snipers and bolt action rifles, as well as an alternative javalin (the ERYX) and a reloadable AT4.

Only downside I could find so far was that the gear is incompatible with our current weapon accesories. You can only use their scopes/silencers/lasers etc, or Bohemia's. 

If that isn't an issue, thumps up from me.

**Comment by Fourjays** [comment]
@abelarno There is a small optional download that enables ASDG JointRails for the scopes. Only just found it myself as it is a non-clickable Dropbox link hidden further down the page.

**Comment by abelarno** [comment]
Ill Check that out Today then
Op 18 apr. 2016 12:47 p.m. schreef "Fourjays" <notifications@github.com>:

**Comment by abelarno** [comment]
The ASDG fixed the issue for the most part.
On the HK416 and HK417 scopes still don't work, even tough arsenal gives the option. The rest works fine.

**Comment by Fourjays** [comment]
It still not working with the HK416/417 is annoying, given they are the main draw for adopting this pack.

**Comment by Ludvigroosen** [comment]
**Tested** (Which map this took place on)
Altis

**Compatibility**(If it compatible with the mod pack)
Yes, this mod works with our mod pack

**Performance Issues**
No issues found

**Playstyle**(If it compatible with how we play)
This mod is for sure compatible with our playstyle

**Impacts** (Any extra work/impacts & needed mods)
 No extra work. Needs CBA to work properly but CBA is already in the mod pack. 

**Quality** (Quality of mod, graphic, works correct etc.)
I feel that the mod is graphically good & the quality is good as well didn’t find any problems with this mod. Didn’t test the weapons up close

**Sounds**
Sounded as usually. Good

**Uncompressed Size**
244 MB

**Activity - Development**
06 March 2016

**Personal opinion**
I would like to see this mod. This can create some good OP’s

**Comment by Ludvigroosen** [comment]
**Compatibility** (If it compatible with the mod pack)
Yes, this mod works with our mod pack

**Performance Issues**
No issues found

**Playstyle** (If it compatible with how we play)
This mod is for sure compatible with our playstyle

**Impacts** (Any extra work/impacts & needed mods)
 No extra work. Needs CBA to work properly but CBA is already in the mod pack. 

**Quality** (Quality of mod, graphic, works correct etc.)
I feel that the mod is graphically good & the quality is good as well didn’t find any problems with this mod. Didn’t test this mod really long, picked out some weapons and tried all the sights for it. Most of them worked. The one who didn’t work was not surprising, for example FAMAS with an Sniper scope.

**Sounds**
Sounded good 

**Uncompressed Size**
244 MB

**Activity - Development**
06 March 2016

**Personal opinion**
I would like to see this mod. This can give some alternative weapons to use. I myself like them really much.

**Comment by Fourjays** [comment]
Marking this as rejected following testing, due to the inconsistent ASDG JointRails support and that the addition of RobertHammers M4s/M16s (#407) includes fully functining versions of those same weapons.
