### ISSUE TITLE
Real Armor Mod

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#390]
**Description:**
What is this? Real Armor Mod, it improves some armor related things
Who is it for? Anybody, but it's especially recommended to those who use both RHS and other mod or stock content together
Server or client? Both, all machines should run the full mod
What does it do? HEAT warheads spawn a projectile on impact, which enables engine AP simulation
Is this script intensive? Nope, there's a tiny script that runs once on HEAT impact and the rest is done by the engine

**Download:** http://www.armaholic.com/page.php?id=24451
**Size:** 1MB

**Comment by Fourjays** [comment]
This was provisionally accepted in the meeting on 11/04/2016, pending testing.

**Comment by abelarno** [comment]
Tested using RHS HEAT m136 launchers, on T-72 1985 tanks

Research can be found here:
https://docs.google.com/spreadsheets/d/1mMjdBwRd67b-5fLmakRe9FM2BaliE5drcPvUJWc1HZU/edit?usp=sharing


Damage on the armor is much more consistent and realistic with RAM on. Well armored tanks are pretty much indistructable with hand held AT when facing it with the front. The back side is very vunerable and when hit will almost instantly destory the tank.
The  T-72 has reactive armor on the front and side. That explains why a side hit usually takes two rockets.

The vanilla tanks take almost zero damage when not using RAM. When RAM is enabled it goed to about the same level als RHS armor.

I highly recommend using this mod. There are no downsides to using it as far as I know, and it makes tanks not only more challenging, but also gives us a lot more vanilla stuff to play with.

**Comment by Fourjays** [comment]
Uploaded to the test repository, ready for deployment.
