### ISSUE TITLE
ALiVE Update to v1.0.3.1604121

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#398]
__Changelog:__
v1.0.3.1604121
[VARIOUS] Fixed placement modules Readiness parameter not working properly when option other than 100% was selected.
[MIL C2ISTAR] Set input default to Array as _logic needs to be a hash
[MIL CQB] Disabled client FPS reporting as obsolete since JIP-AI-spawn option was disabled
[MIL_C2ISTAR] Fix error due to incorrect usage of BIS_fnc_param
[X_LIB] Fixed fnc_inArea to handle location objects
[SUP MULTISPAWN] Fixed crew was not deleted from a synced helicopter. Fixed: If a synced helicopter was not of the same faction as the player (f.e. if default vehicle was chosen) then insertion worked only once, making players hang in waiting screen. Fixed: If an ALiVE_SUP_MULTISPAWN_INSERTION_%FACTION% marker was used and a vehicle was synced a script error was thrown. Added: "Respawn With Gear" option on the module (backward compatible)
[INDEXES] Added full index of Australia (thanks Fadi)
[SUP_COMMAND] Fixes getPos --> getDir
[SUP_COMMAND] Reverting to group list now works when a waypoint is selected. Performance improvements
[X LIB] Fixed: Group didn't move to ambush position properly on HC
[MAIN] Enabled Kunduz data
[VARIOUS] Fixed wrong or missing default values on modules placed with 3DEN
[SUP_COMBATSUPPORT] Fixed issue where rounds for incorrect Ordnance
[SUP_COMMAND] Pressing back when editing a group's waypoints will reset to group list instead of commander selection. Reverted dynamic profile selection radius.
[SYS_INDEXER] Fix indexing for non dev environments.
[MIL CQB | MIL C2ISTAR] Moved T.R.A.C.E. Intel system from CQB to C2ISTAR. Fixed: TRACE was marking grids green for players of other sides. Fixed: Sometimes grids were not showing as cleared for JIP players. Fixed: Re-occupied grids were not always uncleared, but stayed green. Improved: every side now gets their own cleared sectors displayed. Improved: Storing cleared sectors-data (preparation for DB persistency).
[SUP_COMBATSUPPORT] Fixed buttons turning back when focused
[SUP_COMBATSUPPORT] Added code field to artillery module
[SYS_STATISTICS] Fixed issue where number of shots fired per weapon were not reported
[SYS_STATISTICS] Added compatibility for ACE and War Room stats when using ACE Medical and preventing instant deaths. ACE kills now recorded!
[SYS_STATISTICS] Initial fix for ACE damage / kills compatibility
[SYS_INDEXER] Removed debug output
[SYS_DATA] Improved logging for clarity
[SYS_VIEWDISTANCE] Fixed rpt error caused by duplicated logic creation
[VARIOUS] Fixed remaining UI errors ("cannot load control")
[MIL CQB] Changed "error" to "none" to avoid sys data false-positives
[MIL C2ISTAR] Fixed ALiVE_taskhandler and ALiVE_taskhandlerClient haven't been created correctly and script error was thrown if task events were received from the server before task system was fully initialized locally on the JIP client
[SYS PROFILE] Fixed: If a persistent mission was loaded from DB then newly created virtual groups where not given unique IDs (overwriting existing groups in some cases)
[VARIOUS] Removed usage of BIS_fnc_inTrigger and switched to ALiVE_fnc_inArea
[X LIB] Updated ALiVE_fnc_inArea to accept also position-array as input

__Link:__ http://www.armaholic.com/page.php?id=23684
__Size:__ 109MB

**Comment by TheGrandVizier** [comment]
Since alive was fixed, not a single person used it.
I must question it's inclusion in the mod pack at this point.

**Comment by Fourjays** [comment]
Uploaded to the test repository, Ready for deployment.
