### ISSUE TITLE
Advanced Towing  

### ISSUE THREAD

**Issue by abelarno** [blackwatchint/modpack#400]
Description:
Adds support for towing vehicles using ropes. 
- Tow other vehicles behind Ships, Cars, Trucks and Tanks 
- The size of the vehicle impacts it's towing capability 
- Other players (including AI) can tow other players 
- Supports towing damaged / destroyed vehicles 
- Supports towing "trains" of vehicles 

This could be very useful for the engineers.
Tested it and everything seems to work fine in singleplayer so far. Only downside I see so far is that everybody can rope up the vehicles, we might need to modify the mod so only engineers can do that. 

// EDIT:
It's so easy I've already done that actually.

Download: http://www.armaholic.com/page.php?id=30575
Size: 1MB

**Comment by TheGrandVizier** [comment]
I disagree with the "engi" only definition.
In the interest of keeping it in line with deployment system (fob, med) and in the interest of supporting varying types of platoon formats and sizes, I think it should remain enabled for all, or at least, not limited to single role.

**Comment by abelarno** [comment]
Maybe we could figure Out a way to add the option to Ace interact then. Im
not a fan of adding More options to the Action menu, when People might need
to get in a vehicle fast.
Op 14 apr. 2016 2:37 p.m. schreef "TheGrandVizier" <notifications@github.com

**Comment by Ludvigroosen** [comment]
**Tested** (Which map)
Virtual Reality

**Compatibility** (If it compatible with the mod pack)
Works without problems

**Performance Issues**
None found

**Playstyle** (If it compatible with how we play)
 Yes I can see we can use this to transport cars.

**Impacts** (Any extra work/impacts & needed mods)
 A bit of coding maintenance 

**Quality** (Quality of mod, graphic, works correct etc.)
The quality of the mod is quite good. It has great graphic. The only thing I feel should be a part of this mod is that when you’re towing you can’t go as fast as you usually can in the same vehicle.

**Sounds**
No sound on the rope.

**Screenshot's** - [Imgur](http://imgur.com/a/zHBDG)

**Uncompressed Size**
84,3 KB

**Activity - Development**
Update 13 April 2016 

**Personal opinion**
To small mod to have an opinion. It works.

**Comment by abelarno** [comment]
Tested it, works like advertised. The tow trains can get a bit ridiculous, but I don't think those will happen in actual operations. Like I stated before, we might wanna try to make it an ace interact option tough, as it adds even more action menu options.

I can see this being very userful for engineers during our operations.

**Comment by Fourjays** [comment]
ACE is introducing some kind of towing feature in the future, so any decision on this will be pending the specifics of the ACE implementation.

**Comment by Fourjays** [comment]
Issue no longer relevant due to modpack reset.
