### ISSUE TITLE
ALiVE missions not loading

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#402]
Had reports that missions made using ALiVE are not loaded by the server when the admin attempts to start them.

**Comment by Fourjays** [comment]
Needs testing to determine if this is an ALiVE or mission making issue.

**Comment by Ludvigroosen** [comment]
Have to do some research if any requirement modules have changed. Checking this during the weekend.

**Comment by ShiFoo** [comment]
One problem could be that TFAR modules are still on the template but you have loaded the game with ACRE instead of TFAR. Could that be possible?

**Comment by Ludvigroosen** [comment]
@ShiFoo i tested with the Live repo so i could launch it on the server. There seems to be a problem l. So I have to do some research on this issue to make an conclusion.

**Comment by Fourjays** [comment]
It's weird as I ran test templates that had the "ALiVE (Required)" module on them quite a few times for the last modpack update.

**Comment by Ludvigroosen** [comment]
Gonna do an moduel by moduel test on this. 

- Research if alive have new requirments.
- Test moduel by moduel.

**Comment by Ludvigroosen** [comment]
So, Alive seems to be working okey. So far I have only tested with the Alive (Required) Moduel only. 

Gonna continue testing this issue, if no issues are found with the Alive mod I'm gonna create an Alive mod guide how to set it up. With all the settings and information on the different modules. 

The test were performed on the test server.

**Comment by Ludvigroosen** [comment]
Tested this on the "test - repo" Had no problems with it. 

3D templates and "test - repo" alive
