### ISSUE TITLE
Suggestion to improve Nimitz teleporter and fold F18 wings by default

### ISSUE THREAD

**Issue by PalmersPhil** [blackwatchint/modpack#403]
ey guys, I took a look at the Nimitz for my campaign and changed a couple of things that have always been an issue with the Nimitz since A2. I also switched to a marker based teleport for convinenience instead of location based as I find it more reliable and because you dont have to change all the positions in all templates all the time. already excluded USS Wasp  #385

I put in 3 small changes
+ folded the wings of the FA18s, looks nicer and you can stack them better, they start unfolded so watch out they dont overlap at the editor. this is mainly ambience, but you dont hit as many planes when driving around into starting position
this animate ["l_wingfold",1]; this animate ["r_wingfold",1];

+ positioning planes and stuff, I used 18.2 height, reason, if you put them on 18 they are on/in the deck, 19 is too high they will take damage, 18.2 makes them drop 20cm and stand on top of the deck. (7.2 for cargo bay and 12.2 for the briefing area)

+ Marker based teleport script. used via the notice board it has an addaction and ports you to the selected destination. 
Nimitz  has its own (nimitz_tp2) to get you to the cargo hall of the carrier. 
this addAction ["USSNimitz Flight Deck","BWI\scripts\nimitz_tp2.sqf",["nim1"]];
general porter, can add mulitple destinations, just add:
this addAction ["Destination Text blabla","BWI\scripts\teleport.sqf",["MarkerName"]];

[[BWI]Altis.Altis.zip](https://github.com/blackwatchint/modpack/files/222652/BWI.Altis.Altis.zip)

**Comment by PalmersPhil** [comment]
As we have no message system on the forum that I know of, and steam is really inconvienient to use for this purpose I thought I ll put it up here, Just delete it if unnescassary Fourjays.

**Comment by Fourjays** [comment]
These seem like worthwhile suggestions. Assigning to @ShiFoo but he can delegate as required.

**Comment by Fourjays** [comment]
F18 height increased and wings folding implemented. Marker based teleport has been split off to #417, pending a Nimitz update due to lack of 3D editor support.
