### ISSUE TITLE
Suggestion: Vehicle (air and land) repair script via trigger

### ISSUE THREAD

**Issue by PalmersPhil** [blackwatchint/modpack#404]
A nice and leightweight repair and rearm script. Basically a trigger rearming the standard weapon setup and ammo of a vehicle (land and air) within a trigger area after x amount of time passed, triggered by faction y. Land and air use two different triggers, can be configured to be single or multi faction. Air vehicle triggers have to be named (also a var in the trigger) 

readme has everything in it. Could be a nice addition for a training map, base or airfield structure, or within a mission as part of a supply component.

Did you test this? Yes on a dedicated and in missions with 20+ clients.no issues

[Vehicle Pad.zip](https://github.com/blackwatchint/modpack/files/222710/Vehicle.Pad.zip)

**Comment by Fourjays** [comment]
Vehicle repair/rearming is done via ACE.
