### ISSUE TITLE
Update CommCard

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#409]
The CommCard will need updating due to the new platoon structure and the removal of the long range radio from all roles except Platoon Leader/Sergeant, Radio Transmitter Operator and Joint Terminal Attack Controller.

**Comment by Fourjays** [comment]
Details still need to be figured out, but imagine that it will go as follows:
- Fireteams remain on current channels (111/112, 121/122, etc).
- Squad Leader communicates with Fireteams on 110, 120, etc (no more "additional" frequency).
- Platoon communicates with Squads and Vehicles on a defined frequency in the LR frequency range (30-87).
- JTAC and aircraft will similarly communicate using a seperate frequency.

**Comment by Ludvigroosen** [comment]
I thing we should remove the additional channel that Squad Leaders are using. Can be used when "Cooping" with a vehicle or an JTAC etc.

**Comment by ShiFoo** [comment]
Maybe @abelarno can help out here. I already liked the graphics from the bootcamp. Would love to see this style more often!

**Comment by TheGrandVizier** [comment]
I am a touch confused, please clarify.
How are FTLs supposed to talk to SL and their FT without using additional, where FT is 111 and SL is 110?

**Comment by Fourjays** [comment]
@TheGrandVizier There is no need for an "additional" channel as in a frequency specifically for it (currently 115, 125, etc). They will still use the additional _feature_, but instead with frequency 110, 120, etc.

**Comment by abelarno** [comment]
@fourjays That is the same right? Just different channels? Not sure why we should different terminology, seems to make it just more confusing.

**Comment by PalmersPhil** [comment]
no it scraps one channel for the SL and the FTL (the 115/125 one) as the 110/120 is the one where SL/FTL coordinate now while FT stay on their respective channels. Also about the roles, you missed the SL in the LongRange Radio list, or?

**Comment by Fourjays** [comment]
@PalmersPhil Squad Leaders will be talking to Platoon Leader using a short range radio on a long range frequency. Platoon will have a long range radio still. Roles below the level of Fireteam Leader will have the rifleman radio with no additional, same as now.

**Comment by PalmersPhil** [comment]
rgr understood. That means a JTAC or FCO will be needed if support is available or has to run via platoon right!? Cause SR has 2 clicks max range, pretty hard to get in contact with air or artillery elements for a SL then. The PL or APL becomes JTAC / FCO then too in many mission and if HQ is compromised and both go down, the Squads have no way of communicating with the outside world. before that they had the RTO or the SL with a LR.

**Comment by Fourjays** [comment]
@PalmersPhil Short range radios that Squad/Fireteam Leaders use have a 5km range. This is plenty for Platoon-Squad communications as they shouldn't be further away than 1-2km at max. JTAC will (and should only) be handled via a JTAC operator using a long range radio (20km range). If a mission specifically calls for long range capabilities, RTOs can be attached to squads (20km range again). Vehicles also have long range capabilities (up to 30km) as an option if squads are going out of normal range. The only way you end up without comms is if a mission ends up outside the boundaries that it was prepared for, in which case you deal with what you've got as best you can (just like IRL).

**Comment by Ludvigroosen** [comment]
Personal opinion is to wait until acre is getting implemented and push it out together

**Comment by Fourjays** [comment]
@Ludvigroosen Is going ahead with this update. The weight and space impact of the long range radios on loadouts is too significant to ignore.

**Comment by Fourjays** [comment]
Updated CommCard created by @abelarno committed to the develop branch.
