### ISSUE TITLE
Swedish Forces Pack

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#411]
**Description:**
Includes features such as advance missiles.buddy reload, backblast, "random" numbers on helicopters.
More than 11 new completely new vehicles, including airplane, helicopter, drones, jeeps and boats.
Over 20 new weapons and to enjoy all this are over 15 missions for 2-40 players. Coop and PvP.

**Download:** http://www.armaholic.com/page.php?id=20042
**Size:** 1.1GB

**Comment by abelarno** [comment]
http://www.armaholic.com/datas/users/swedish-forces-pack-v051-4_4.jpg

I _need_ this.

**Comment by Ludvigroosen** [comment]
The graphics of this mod is to bad for me to wanna do an review, i wouldn't like to see this mod pack in our mod pack

**Comment by abelarno** [comment]
This pack is really hit or miss, depending on what you're looking at.
The vehicles does not seem to have proper damage states. The wheels are indistructable and are not removable with ace. There are some that look quite nice tough. On the other hand some vehicles really don't look that good at all.
Some vehicles are just reskins, others (usually the ones with lesser quality) are original work I think.
There is a big missile boat that works nicely

The weapons are nice, but there are not that many variants. 

This mod has a bunch of stuff in it, and I think that's its biggest weakness. I don't trust this to work nicely in our missions at all. I don't trust the vehicles to always work, or do what they are supposed to do. It as too many moving parts.
This mod is clearly quantity over quality. We already have quantity, so I don't recommend using this mod.

**Comment by Fourjays** [comment]
Rejected in the meeting on 20/06/2016 due to quality concerns.
