### ISSUE TITLE
Consistently name all factions within the Armory

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#413]
As many new factions may be added to the Armory in future, all existing factions need to be named using a consistent format that conveys the camo and era of the loadout. Furthermore, the factions should be better grouped and sorted.

**Comment by Ludvigroosen** [comment]
Give me a list and i will fix this with all new mods added

**Comment by Fourjays** [comment]
Will need to make sure all new loadouts added via #420 are incorporated. Likely format will be "Faction > Camo (Year)"

Example:
- USMC
  - Wood (c. 1986)
  - Desert (c. 2005)
  - Desert (c. 2018)
  - Wood (c. 2005)
  - Wood (c. 2018)

**Comment by Fourjays** [comment]
Changes committed to develop branch.
