### ISSUE TITLE
Aiming to low and shooting to low

### ISSUE THREAD

**Issue by Ludvigroosen** [blackwatchint/modpack#423]
User reported that there was a problem with the Izhmash AKS74U (hlc_rifle_aks74u) from NIArsenal: AK Rifles and the aim function with it. You can find pictures down below on the issue. It works as it should with an "scope".

[Link](http://imgur.com/o8PgryL)

During a brief testing of this issue i discovered that it was shooting to low as well.

**Comment by Ludvigroosen** [comment]
Replace with Izhmash AKS74U(MTK), Class name is (hlc_rifle_aks74u_MTK) and the problem is solved

**Comment by Fourjays** [comment]
Fix commited to develop branch.
