### ISSUE TITLE
Southern Wardak Province, Afghanistan

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/modpack#43]
**Description:**
This map is based on the border of Wardak Province and Logar Province. I am naming the map Wardak Province, due to a majority of the map is on the Wardak Province.

**Download:** http://www.armaholic.com/page.php?id=28535
**Size:** 50MB

**Comment by wingatex** [comment]
Map works fine without issue. No issues with the map and works with our modset. Do not like as the map is pretty barren and empty and able to see the edge of the map from all of it. I would not include as we have better maps what are similar. 

http://steamcommunity.com/sharedfiles/filedetails/?id=567952846
http://steamcommunity.com/sharedfiles/filedetails/?id=567953073
http://steamcommunity.com/sharedfiles/filedetails/?id=567953252
http://steamcommunity.com/sharedfiles/filedetails/?id=567953800

**Comment by Ludvigroosen** [comment]
Gonna check out the map and leave a review today when i get home.

**Comment by Ludvigroosen** [comment]
Had some issues, http://imgur.com/a/iWefB. Would agree with @wingatex that the map feels really empty and i would say that we got better maps with the same type of environment. Wouldn't add this to the mod pack.

**Comment by Fourjays** [comment]
Rejected in meeting on 21/03/2016 due to quality concerns.
