### ISSUE TITLE
RHS Update to v0.4.1.1

### ISSUE THREAD

**Issue by abelarno** [blackwatchint/modpack#432]
USAF changelog/download: http://www.rhsmods.org/mod/2
Armaholic link: http://www.armaholic.com/page.php?id=27149

AFRF changelog/download: http://www.rhsmods.org/mod/1
Armaholic link: http://www.armaholic.com/page.php?id=27150

**Comment by Fourjays** [comment]
Shifting GREF to a request as it'd be a new mod.

This will need testing to find bugs and detect problem areas for integration with existing elements (such as loadouts).

**Comment by abelarno** [comment]
The update adds a bunch of littlebirds. They seem to be very much inspired by the Mission Enhanched Littlebirds that we use right now. If they fly like they should, they seem to be a good replacement for the MELB mod.

**Comment by Fourjays** [comment]
Armor behaviour with RHS tanks and anti-tank weapons, as well as mixed engagements between RHS and non-RHS vehicles/equipment, need testing.

**Comment by Fourjays** [comment]
Uploaded to the test repo, waiting deployment.

**Comment by Fourjays** [comment]
Testing also needs to determine all new vehicles added that require ACE cargo and inventory sizes updating.

**Comment by abelarno** [comment]
Updated issue for version v0.4.1.1

**Comment by Fourjays** [comment]
Uploaded to test repository, ready for deployment.

**Comment by Fourjays** [comment]
Issue no longer relevant due to modpack reset.
