### ISSUE TITLE
Kunduz Update to v1.20.2

### ISSUE THREAD

**Issue by abelarno** [blackwatchint/modpack#449]
**Changelog:**
v1.20.2
- Optimized Vegetation LOD Performance
- Optimized File Size By ~177Mb
- Tweaked Door Sounds
- Tweaked Vegetation Shading
- Fixed Tunnel Shadows
- Fixed Code Pathing Bugs
- Fixed Code Formatting

v1.20.1
- Fixed missing moon and stars
- Fixed AI/AI vehicles can now cross the two main north and south river bridges
- Fixed tunnel system shadows

v1.20
- Updated terrain lighting to v1.60+
- Updated tree shaders
- Updated satellite image
- Updated normal image
- Updated object textures
- Updated terrain textures
- Updated clutter
- Updated road network
- Updated location names
- Updated door system to A3 standard
- Updated vegetation layout
- Updated compound layout
- Updated terrain layout
- Updated config code standards
- Updated sounds
- Updated fort compound
- Fixed satellite colour imbalance
- Fixed floating objects
- Fixed airport road elevation
- Fixed road paths
- Fixed object angles
- Fixed door issues
- Fixed clipping objects
- Fixed outside terrain
- Fixed dust effects

**Download:** http://www.armaholic.com/page.php?id=27882

**Comment by Fourjays** [comment]
Uploaded to test repository, ready for deployment.
