### ISSUE TITLE
Australia

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#459]
**Description:**
Welcome to Australia island addon for Arma3. This is a Work in Progress but I have decided to release to the Public to get some feedback on How to improve your playing experience. This is Version 1.0

This island took many years to complete, Ive worked on it when I have had free time, I hope you like it, The island is 8 times larger than Altis and is 1600Km2 compared to Altis 270Km2.
I've left areas in the cities for RPG players to add their own buildings, there are police stations but they are not open (as I didnt receive the scripts from the maker).
Hopefully I can get them so you can use those buildings. I also had to remove some custom buildings as they were causing game glitches.

**Download:** http://www.armaholic.com/page.php?id=28882
**Size:** 968MB

**Comment by Fourjays** [comment]
Australia was previously in our modpack, but removed due to massive FPS issues. With recent updates to Arma 3's graphics engine, as well as a significant number of changes to the terrain itself, we wish to re-check it to see if prior issues have been resolved.

**Comment by Ludvigroosen** [comment]
I found the FPS issue inside the EDEN editor. When playing and flying around i can't find a issue with FPS

**Comment by wingatex** [comment]
First issue is that skybox is broken still on this map. Map is big and has tops of potential for a lot of different types of operations. Seems to work well with current mod pack no issues. Has a lift in some buildings but doesn't work as you will fall through the floor. fps running around is around 35-40 without any sort of fighting. FPS in a 5x5 firefight held at 25 frames for we with explosions. Will be key to make sure people have their view distance at a manageable distance as will cause issue for people. Their is alarge distances of nothing as it being a desert map. Screenshot below of the map.

http://steamcommunity.com/sharedfiles/filedetails/?id=721581970
http://steamcommunity.com/sharedfiles/filedetails/?id=721581945
http://steamcommunity.com/sharedfiles/filedetails/?id=721581918
http://steamcommunity.com/sharedfiles/filedetails/?id=721581901
http://steamcommunity.com/sharedfiles/filedetails/?id=721581850
http://steamcommunity.com/sharedfiles/filedetails/?id=721581792
http://steamcommunity.com/sharedfiles/filedetails/?id=721581762
http://steamcommunity.com/sharedfiles/filedetails/?id=721581737
http://steamcommunity.com/sharedfiles/filedetails/?id=721581820
http://steamcommunity.com/sharedfiles/filedetails/?id=721581705

**Comment by Fourjays** [comment]
Performance on Australia still seems to be very poor. In a simple test of driving around Sydney before driving into the rural outback, it started at 23FPS in the city. It rose as high as 60FPS once into the rural areas, but returning to the city again dropped it to the mid-20s.

For comparison, Altis runs at a low of 37FPS and a high of 60FPS.

**Comment by Fourjays** [comment]
Rejected in the meeting on 11th July 2016.
