### ISSUE TITLE
Bornholm Lite

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#460]
**Description:**
Bornholm is a prize winning map by Egil Sandfeld.
https://forums.bistudio.com/topic/174278-bornholm-denmark-terrain/
 
Since the day map was released, i've liked it alot. It coverages huge area and is still very detailed in visuals and audio.
Originally it was made to be standalone. This meant that all us AiA TP users had to download lots of data we already had again. Disk storage isn't expensive but this felt always really inefficient.
 
So I've decided to make a AiA TP compatible version of the map I love with a source files Egil has shared with the community.
 
lite_Bornholm is Bornholm that uses objects from AiA TP, and CUP in the future. Original Bornholm had a lots of nice retextured objects like trees and plants and they are the only thing that are missing here. All the retextured objects are replaced with "vanilla" objects from A2 and A2 ep1.
I guess we can say that summer has turned into autumn in Bornholm now.

**Download:** http://www.armaholic.com/page.php?id=29777
**Size:** 535MB

**Comment by Fourjays** [comment]
We previously had Bornholm in the modpack (original is here for comparison: http://www.armaholic.com/page.php?id=27056), but it had a number of performance related issues. This new "lite" version is claimed to have many improvements, and the Arma 3 engine has improved since then. We want to see if this new version fixes our prior issues with the terrain.

**Comment by Ludvigroosen** [comment]
FPS issues exist and black sky issue from graphic rework. Current version is not good enough for mod pack imo. I would say no due to this map.

**Comment by wingatex** [comment]
Skybox is broke on this map. Map has a lot of potential for both urban and forest gameplay. Lot of different areas as shown from screenshots. FPS seems to be a solid 35 throughout and through a 5x5 firefight went to a low of 20 for me. Nothing seems to stand out as wrong with it. Needs testing on server to see if fps holds up on it.

http://steamcommunity.com/sharedfiles/filedetails/?id=721588264
http://steamcommunity.com/sharedfiles/filedetails/?id=721588246
http://steamcommunity.com/sharedfiles/filedetails/?id=721588218
http://steamcommunity.com/sharedfiles/filedetails/?id=721588186
http://steamcommunity.com/sharedfiles/filedetails/?id=721588149
http://steamcommunity.com/sharedfiles/filedetails/?id=721588118
http://steamcommunity.com/sharedfiles/filedetails/?id=721588057
http://steamcommunity.com/sharedfiles/filedetails/?id=721588023
http://steamcommunity.com/sharedfiles/filedetails/?id=721587996
http://steamcommunity.com/sharedfiles/filedetails/?id=721588086
http://steamcommunity.com/sharedfiles/filedetails/?id=721587948

**Comment by Fourjays** [comment]
Performance is pretty normal on Bornholm, with it typically ranging between 37FPS and 60FPS. For comparison, Altis runs in the same range (37-60FPS) and Tanoa runs between 33FPS and 60FPS.

Bornholm feels pretty unique, but just driving around doing these performance tests it was obvious that the severity and bumpiness of the terrain could be very challenging at times.

**Comment by Fourjays** [comment]
Rejected in the meeting on 11th July 2016.
