### ISSUE TITLE
ASR AI 3 Update to v0.9.30

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#464]
**Changelog:**
v0.9.30
- configs updated for new 1.62/APEX content
- added config fix to prevent this from becoming dependency when editing
- tweaked configs for shot detection; scripted fired event handler disabled by default
- tweaked detection related config parameters (AI was too good at detecting things in the jungle)
- reduced aiming abilities for lower skilled units
- removed shooting stance tweaks (were slowing down unit moves too much)
- improved code (made a bit prettier and more efficient using newer sqf syntax and commands)
- improve debug logging by tagging each line in RPT
- settings overhauled; moved most user configurable options to the CBA settings framework (in game)
- asr_ai3_settings.sqf no longer used
- these settings can't be set in game and remain configurable by editing asr_ai3_settings_ss.sqf: asr_ai3_main_sets, asr_ai3_main_levels_units, asr_ai3_main_factions
- added options for radioing delays (prevent enemy calling your position to ther groups by shooting leader in less than x time since detected)
- added options for how many mags and first aid kits units are trying to maintain (rearming)
- allowed changing settings on the fly using in game settings dialogue (rearming for example)

v0.9.29
- updated configs for Arma3 1.60
- fix author related error message
- UAV_AI units have max skill by default
- remove CAManBase::{audible,spotableDarkNightLightsOff,spotableNightLightsOff}, cfgAISkill::spotDistance tweaks in favor to updated vanilla settings; may need to re-evaluate and tweak these again.
- minor tweaks to userconfig defaults
- allow usage of base classes in class level overrides; Example: asr_ai3_main_levels_units[10] pushBack "B_Soldier_sniper_base_F";

**Download:** http://www.armaholic.com/page.php?id=24080

**Comment by Fourjays** [comment]
Uploaded to test repository, ready for deployment.

**Comment by blackwatchint** [comment]
A new update has been released for ASR. Reopened and edited accordingly.

**Comment by Fourjays** [comment]
A new update has been released for ASR. Reopened and edited accordingly.

**Comment by Fourjays** [comment]
Uploaded to test repository, ready for deployment.

**Comment by Fourjays** [comment]
Issue no longer relevant due to modpack reset.
