### ISSUE TITLE
ACE X 

### ISSUE THREAD

**Issue by abelarno** [blackwatchint/modpack#467]
**Description:**
This is the first release of the ACEX package. This is a mod aimed at adding in extra and optional modules on top of ACE3.

At the moment ACEX is focused on gameplay that the ACE team considers added value, but does not properly fit within the main project itself. The initial release contains mission and multiplayer enhanced frameworks, such as the Headless Client Load Balancing.

**Download:**
https://github.com/acemod/ACEX/releases/download/v3.0.0/acex_3.0.0.zip

**Comment by Fourjays** [comment]
Out of the three features, two of them are just splintered off from the main ACE project, so is accepted by default.

Introduces some sort of headless client support. No documentation on it currently though. Would like to test it as a potential replacement for WHK and if it can possibly provide any more control. We'll schedule a server test session when the next modpack update is almost completed.

**Comment by Fourjays** [comment]
This does *not* appear to need a further update as with #466.

**Comment by Fourjays** [comment]
Uploaded to the test repo, waiting deployment.

**Comment by Fourjays** [comment]
Integrated as part of modpack reset.
