### ISSUE TITLE
BWMod Update to v1.4

### ISSUE THREAD

**Issue by abelarno** [blackwatchint/modpack#468]
**Changelog:**
added: LLM01 Underbarrel
added: G38 variants
added: G36C Ironsights
added: Localized names of mod components for "Required addons for scenario" tab
changed: RGW90 position on back
changed: Increased limit of drawn group members for NaviPad and enabled showing free hand lines
fixed: After 1.60 the flight path of PzF3 rocket was wrong
fixed: Mixed up description of HE and HEAT ammunition for 84mm Leuchtbüchse
fixed: Night vision device was attachable to 84mm Leuchtbüchse
fixed: Undefined variable "BWA3_optics_camera" when leaving Puma or Leopard
fixed: No entry 'bin\config.bin/CfgVehicles/Tank_F/HitPoints/HitFuel.name'

**Download:**
http://www.armaholic.com/page.php?id=24147

**Comment by Fourjays** [comment]
Issue for this already exists at #451.
