### ISSUE TITLE
Isla Duala Update to v3.66

### ISSUE THREAD

**Issue by PalmersPhil** [blackwatchint/modpack#470]
**Changelog:**
- fixed skies & lighting that got wrecked with release of official patch 1.60+
- improved satellite image graphics
- removed dependency of Island Panthera & ibr_rn.pbo
- removed dependency of CUP Terrains Maps, only CUP Terrains Core is required
- added runway lights to both main paved airports

**Download:** http://www.armaholic.com/page.php?id=27700

**Comment by Fourjays** [comment]
@PalmersPhil Please post changelog and download link with the mods title in future.

Fairly meaningless update, just need to remove our 1.60 sky patch for this terrain.

**Comment by Fourjays** [comment]
Uploaded to test repository, ready for deployment.
