### ISSUE TITLE
Esseker

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#474]
**Description:**
169km2 of Post-apocalyptic world designed for survival gameplay. Based on real world location in Bosnia, modeled after reference and satellite images. 1.480.000 objects so far. We are aiming for realism, and we are putting a lot of effort in details to make everything look natural and organic.

**Download:** http://www.armaholic.com/page.php?id=28815
**Size:** 2.4GB

**Comment by Fourjays** [comment]
Esseker was previously in our modpack and was removed due to CTDs when switching maps (see #32). With updates to both Arma and Esseker since then, and the replacement of All in Arma with CUP Terrain, it seems worthwhile to re-test it.

**Comment by Fourjays** [comment]
Particular attention should be paid to testing for issues with switching maps with this map. Performance and general stability should also be checked.

Quality should also be verified - it remains a WIP terrain and there may be incomplete areas.

**Comment by wingatex** [comment]
Checked map and seemed good visually. Screenshots below. Performance of the map needs testing on server. Tested a firefight of 5x5 fireteams with frames before at around 25-30 and during go to as low as 5 during initial contact. Improved throughout when zoomed in on particular areas but for the most part stayed around 20. Testing on map to see what happens on server to see if it drops anymore. Over I would like to see this proving the fps can stand up on server.

http://steamcommunity.com/profiles/76561198026819968/screenshots/
http://steamcommunity.com/sharedfiles/filedetails/?id=721237412
http://steamcommunity.com/sharedfiles/filedetails/?id=721237379
http://steamcommunity.com/sharedfiles/filedetails/?id=721237334
http://steamcommunity.com/sharedfiles/filedetails/?id=721237296
http://steamcommunity.com/sharedfiles/filedetails/?id=721237257
http://steamcommunity.com/sharedfiles/filedetails/?id=721237190
http://steamcommunity.com/sharedfiles/filedetails/?id=721237125
http://steamcommunity.com/sharedfiles/filedetails/?id=721237159
http://steamcommunity.com/sharedfiles/filedetails/?id=721237225
http://steamcommunity.com/sharedfiles/filedetails/?id=721237087
http://steamcommunity.com/sharedfiles/filedetails/?id=721237017
http://steamcommunity.com/sharedfiles/filedetails/?id=721237053

**Comment by Fourjays** [comment]
Has improved since we last had it in the modpack. Many of the errors have been fixed, although there is a new one relating to a missing texture file (fires once at map load then doesn't reappear). As before, there theme of the map is unique, if a little bit unflexible because of everything looking post-apocalyptic.

Performance seems pretty comparable to Altis. With an 8v8 battle Altis will run at 34-55 FPS in a city, and 52-60FPS in a village. On Esseker, the city area runs at 36-54FPS and the villages at 45-53FPS.

Screenshots:
http://steamcommunity.com/sharedfiles/filedetails/?id=721261704
http://steamcommunity.com/sharedfiles/filedetails/?id=721261625
http://steamcommunity.com/sharedfiles/filedetails/?id=721261774
http://steamcommunity.com/sharedfiles/filedetails/?id=721261853
http://steamcommunity.com/sharedfiles/filedetails/?id=721261920
http://steamcommunity.com/sharedfiles/filedetails/?id=721261996
http://steamcommunity.com/sharedfiles/filedetails/?id=721262043
http://steamcommunity.com/sharedfiles/filedetails/?id=721262092

**Comment by Fourjays** [comment]
Further testing has revealed that prior issues with Esseker have not been resolved. It generates the following error on _other_ terrains (presumably as it modifies the objects): http://steamcommunity.com/sharedfiles/filedetails/?id=722295883

This error is very likely what lead to the crashes while changing maps on the server when Esseker was previously in the modpack.

**Comment by Fourjays** [comment]
Rejected in the meeting on 11th July 2016.
