### ISSUE TITLE
Isla Abramia

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#476]
**Description:**
Inspirations for island were Scotland, Bosnia and Norway. I've wanted to give players of Armaverse something new to toy with and mix of green and snowy mountains always attracted me. Hopefully you'll like it as same I do.

**Download:** http://www.armaholic.com/page.php?id=30616
**Size:** 211MB

**Comment by Fourjays** [comment]
Isla Abramia is a relatively simply designed map, but with significant character. The lighting for the whole map is well done, with a soft/cool feeling that is fitting to the mixture of forested valleys and snow-covered mountain tops. At first the map feels small, but as it is made up of multiple islands it is bigger than it initially looks.

There is a good number of enterable buildings, including some that are rarely used in other maps, which helps to give the urban areas a unique feeling. While the urban areas are not densely detailed, they do perform very well (low of 52FPS) and provide enough detail to be satisfying.

There is one known issue with the latest version of this terrain, whereby some bridges are too high and some buildings are sunk. According to the author this was caused by an error in the build process for the latest version, and a update can be expected immintently. For now he recommends locating and using an older version of the map.

Given the unique feeling that this map has, the author's proven history for good support, the reasonable size (280MB) and excellent performance, I think this terrain would be a good addition to our modpack.

Screenshots:
http://steamcommunity.com/sharedfiles/filedetails/?id=722324865
http://steamcommunity.com/sharedfiles/filedetails/?id=722324930
http://steamcommunity.com/sharedfiles/filedetails/?id=722325048
http://steamcommunity.com/sharedfiles/filedetails/?id=722325093
http://steamcommunity.com/sharedfiles/filedetails/?id=722325384
http://steamcommunity.com/sharedfiles/filedetails/?id=722325327
http://steamcommunity.com/sharedfiles/filedetails/?id=722325479
http://steamcommunity.com/sharedfiles/filedetails/?id=722325698
http://steamcommunity.com/sharedfiles/filedetails/?id=722325595
http://steamcommunity.com/sharedfiles/filedetails/?id=722325542
http://steamcommunity.com/sharedfiles/filedetails/?id=722325645
http://steamcommunity.com/sharedfiles/filedetails/?id=722325769
http://steamcommunity.com/sharedfiles/filedetails/?id=722325810
http://steamcommunity.com/sharedfiles/filedetails/?id=722325858
http://steamcommunity.com/sharedfiles/filedetails/?id=722325965

**Comment by wingatex** [comment]
Map is fine, works like the others from this developer. Has a lot of potential for different styles of ops. No FPS issues when testing with firefight and driving around. For the size of the mod I would say it is worth being included in it.

**Comment by Fourjays** [comment]
Accepted into the modpack in the meeting on 11th July 2016.

**Comment by Fourjays** [comment]
Uploaded to the test repo and awaiting deployment.

Leaving open for now while waiting for a fix to the known issue.

**Comment by Fourjays** [comment]
A fixed version has been released, changelog is as follows:

v1.7
- fixed object positions that got borked up in 1.66
- improved graphics: satellite texture, middle texture and clutter
- removed default 5 percent fog setting, use Zeus advanced fog that is based on proper height
- smaller object placement fixes

**Comment by Fourjays** [comment]
Issue no longer relevant due to modpack reset.
