### ISSUE TITLE
Kerama Islands

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#477]
**Description:**
The Kerama archipelago is a group of islands at the south-west of Japan, part of the Ryūkyū archipelago in the China Seas.
It is composed of 5 inhabiteds islands, of which only 3 have been taken into the map along with some of the lesser islands.

**Download:** http://www.armaholic.com/page.php?id=30967
**Size:** 246MB

**Comment by Fourjays** [comment]
There is a lot of unique and incredibly creative use of Arma 3 assets within this map that results in a terrain that feels "real". Industrial areas feel large and sprawling, towns feel tight, dense and urban, rural areas are sparse yet remain detailed. There are tiny waterfalls, massive bridges, walkway tunnels through rocks, hilltop castle villages and even a submarine base. The author has done an excellent job of capturing a real and lifelike environment, and has done so without any third party assets. 

The biggest problems with this map are probably as a result of this creativity. Sometimes a building or object can initially appear to be "glitched" before you realise how it has been used to create a different illusion. In some areas, such as the submarine base, there is z-fighting caused by the layered objects. With such creative use of objects, I am also concerned about how the AI and even players will react to the environment in some places.

Performance may also be a small concern. For me it ran between 30FPS and 42FPS. Altis and Tanoa run 37-60FPS and 33-50FPS respectively.

Overall, I think while this map has a high risk of issues, it also has a high possiblity of providing some unique experiences. For the small size, it may be worth a gamble.

Screenshots:
http://steamcommunity.com/sharedfiles/filedetails/?id=722350049
http://steamcommunity.com/sharedfiles/filedetails/?id=722350204
http://steamcommunity.com/sharedfiles/filedetails/?id=722350153
http://steamcommunity.com/sharedfiles/filedetails/?id=722350319
http://steamcommunity.com/sharedfiles/filedetails/?id=722350362
http://steamcommunity.com/sharedfiles/filedetails/?id=722350458
http://steamcommunity.com/sharedfiles/filedetails/?id=722350878
http://steamcommunity.com/sharedfiles/filedetails/?id=722350818
http://steamcommunity.com/sharedfiles/filedetails/?id=722351097
http://steamcommunity.com/sharedfiles/filedetails/?id=722351059
http://steamcommunity.com/sharedfiles/filedetails/?id=722351436
http://steamcommunity.com/sharedfiles/filedetails/?id=722351487
http://steamcommunity.com/sharedfiles/filedetails/?id=722351537
http://steamcommunity.com/sharedfiles/filedetails/?id=722351601
http://steamcommunity.com/sharedfiles/filedetails/?id=722351789

**Comment by wingatex** [comment]
Map is awsome as it has a lot of unique places which we haven't seen before. Their is a few issues of clipping with objects hitting each other but for the most part looks really good. The major problem is this place has 4-5 unique areas so may get over used very quick but i still think it is worth including as some very different types of operations can take place on this map. FPS is ok as well with an average of 35 when driving around and 25 with a firefight.

**Comment by Fourjays** [comment]
Accepted into the modpack in the meeting on 11th July 2016.

**Comment by Fourjays** [comment]
Uploaded to the test repo, awaiting deployment.
