### ISSUE TITLE
USS Nimitz Update to v0.95

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#485]
**Changelog:**
v0.95-beta
- add walkway from fore to weapons room
- fix some textures

2016-07-09 config.cpp, model
- added new rooms but geo lod is in the way
- halfway connected fore front walk to weapons room
- fixed Apex crash, nimspots and nimlights have empty res 0 lod now

2016-06-18 config.cpp, model
- added a 'door' to the hull at the fore, kudos to Megadeth
- added preview image for editor

2016-02-20 config.cpp, models
- add new rooms between weapons room and hangar4
- try to fix elevator 3 missing texture
- try to fix geo lod for animated fence at elevator3
- fix road lod on hangar level, introduce new lods

**Download:** http://www.armaholic.com/page.php?id=23049

**Comment by PalmersPhil** [comment]
there was a huge Nimitz update 10th july, a lot of glitches with floors n other things fixed.
http://www.armaholic.com/page.php?id=23049

**Comment by Fourjays** [comment]
We're going to check it out, but there doesn't seem to be any mention of supporting 3DEN placement which is the primary problem.

**Comment by PalmersPhil** [comment]
what is the problem with the placement? the main issue I found was that the planes and stuff do not keep an ASL setting when you move the carrier over to another place and with it a different depth of water and you have to manually reset it. Once you do it manually the planes can take off and stuff just fine.

**Comment by Fourjays** [comment]
It was simply unplaceable in 3DEN, with many visual and functional glitches. The latest version appears to have fixed it.

**Comment by Fourjays** [comment]
Nimitz will be retained for now, but on a "last chance" basis due to history of problems and low usage.

**Comment by Fourjays** [comment]
Uploaded to the test repo, awaiting deployment.
