### ISSUE TITLE
Suggestion: Project OPFOR (RHS only Based tons of factions mod)

### ISSUE THREAD

**Issue by PalmersPhil** [blackwatchint/modpack#495]
http://www.armaholic.com/page.php?id=31310

Project OPFOR is an initiative to bring community forces and armies, which were included in recent military events.
We will keep as simple requirements as possible, for now it is only RHS Escalation (AFRF and USAF). 
GREF dependency is still to be discussed, also we do not consider dependency on modifications with poor quality.

-----
Maybe a thing to keep on the radar as its RHS core makes it highly compatible to our Modpack and delivers pretty much for 900MB saving us probably hundreds of groups.cfg and loadout work

Its also modular and splitted into several independent regional pbos, maybe making it a gap filling package or easier to include.

po_factions_afr: consists of civilians, armed civilians and pirates
po_factions_eu: for now it consists of civilians, Armed Forces of Ukraine and Novorossiya Forces
po_factions_fic: gives you fictional factions form arma universe like CDF, CHDKZ, NAPA, RACS, SLA, TKA, UN and Ultranationalists
po_factions_me: Afghan Natonial Army and Police, Middle Eastern Militia, Civilians, Iraqi Army, Islamic State, Peshmerga and PMC

**Comment by Fourjays** [comment]
Closing as mod doesn't meet new modpack criteria requirements.
