### ISSUE TITLE
New Faction - US Vietnam

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/modpack#64]
New Faction for loadout stands representing Vietnam-era US.

* Squad Leader
* Fireteam Leader
* Radio Transmitter Operator
* Corpsman
* Engineer
* Combat First Responder
* Automatic Rifleman
* Assistant Automatic Rifleman
* Rifleman (AT)
* Heavy Machine Gun
* Helicopter Pilot
* Pilot
* Designated Marksman
* Sniper
* Demolition Man
* Crewman
* Rifleman

**Comment by ShiFoo** [comment]
I have asked Dusty if he could send me his Vietnam loadotus. I will then adapt them to the gear functions... If he cannot deliver them in the near future i will do them myself...

**Comment by ShiFoo** [comment]
Moved to backlog for now. Might get picked up in the future.

**Comment by Fourjays** [comment]
Due to significant increase in available loadouts and the new development methodology, this request has been obsoleted.
