### ISSUE TITLE
Atlantis Map

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/modpack#82]
**Description:**
A 20x20km Terrain offering potential for large air assault and naval operations as well Spec Ops scenarios. 
20 Large and smaller islands with unique locations: 
- 1 Airfield 
- 2 Sea Port 
- 2 x Radar installation 
- 3 x Army Camp 
- Large Open Mine 
- 4 Larger Towns 
- 3 Villages 
- 2 Large Bridges 
- Other smaller locations.. 

**Download:** http://www.armaholic.com/page.php?id=29022
**Size:** 1.4GB

**Comment by karlkarl93** [comment]
http://imgur.com/a/B8JeL - Screenshots

This map is overall, pretty good. It's a very mountainous map with a jungle environment. It has several small military bases, a few radar and radio stations but it doesn't have too many villages that I saw.

The problems with the map are roads that aren't connected to each other and bridges that have "steps", as you can see in the screenshots.

**Comment by LordCavac** [comment]
My initial look around in Zeus would lead me to say no to this map. There are lots of clipping and graphical issues, plus all the issues we are already having with boats (especially RHIBs randomly exploding or flipping and killing all their crew) I'm not sure that we need any water based maps. We could do aircraft to overcome, but the jungle is super thick with little to no clearings excluding military bases and towns. I'll look more in-depth soon.

**Comment by wingatex** [comment]
I have looked at the map and seen no major issues with it other than some objects going into each other. The map has a lot of potential for water incursion operations and adds something we currently don't have. It also has villages under water for anyone who would like to do a water operation. It is heavy on the forest with few towns. Personally I like it. Below are some screen shots of the islands.
http://steamcommunity.com/sharedfiles/filedetails/?id=645281893
http://steamcommunity.com/sharedfiles/filedetails/?id=645281870
http://steamcommunity.com/sharedfiles/filedetails/?id=645281856
http://steamcommunity.com/sharedfiles/filedetails/?id=645281826
http://steamcommunity.com/sharedfiles/filedetails/?id=645281803
http://steamcommunity.com/sharedfiles/filedetails/?id=645281768
http://steamcommunity.com/sharedfiles/filedetails/?id=645281706
http://steamcommunity.com/sharedfiles/filedetails/?id=645281735

**Comment by Fourjays** [comment]
Rejected in meeting on 21/03/2016 due to quality concerns.
