### ISSUE TITLE
Attempt to spawn specific units causes client to crash instantly.

### ISSUE THREAD

**Issue by TheGrandVizier** [blackwatchint/modpack#9]
Description:
As a zeus, when spawning specific units from Civ category, the client will crash and cause the regular problems of crashing zeuses.

Reproduce:
1. Open Zeus
2. Go to "Civilians" tab.
3. Search for a civilian unit named "BOSS" in one of the categories.
4. Attempt to spawn this unit.

Result:
Unit was not spawned, Zeus Arma Client crashes instantly.

**Comment by adios113** [comment]
** Confirmed. **

BOSS is a class name for a main character from Arma 1. Its either RDS which i don't think, cause it doesnt add Arma 1 Civs, but Arma 2 or its AIA, which adds Arma 1 maps and may contain couple of arma 1 units in config, but not the actualy file for the unit - Namals "Mutants" example.

**Comment by TheGrandVizier** [comment]
Note: There are other units that causes this, in other factions also. We need to track them down. I will try to do this.
Is there a way of removing them from the zeus interface if not removing them entirely?

**Comment by adios113** [comment]
Depends on the modpack structure. If it has a separate .pbo file for those specific, bugged units like namals had "mutants.pbo" then yes.

**Comment by TheGrandVizier** [comment]
When can we expect a definitive statement on this?

**Comment by adios113** [comment]
Working on this, trying to find the mod from where it comes from. I didnt find it in the AIA. ETA unknown.

**Comment by TheGrandVizier** [comment]
Weird shit.
Here is the only ref i found online:
https://forums.bistudio.com/topic/171988-all-in-arma-terrain-pack-aia-tp-a1a2oa-terrains-from-bi-in-a3/?p=2785425 and it does seem to address and blame AiA, dont know if it helps you though.

**Comment by Fourjays** [comment]
Needs testing to determine which units specifically causes crashes.

**Comment by wingatex** [comment]
civilian - other - cars - first one
civilian - other - men - both
Did random tests in each of the different category's on blue, op and indi which came up with nothing else.

**Comment by Fourjays** [comment]
@wingatex can you give a more precise list of the objects that cause client crashes?

**Comment by wingatex** [comment]
For the once I already found I can put the unit names. I haven't gone through everything and don't have time to go through everything on the zeus functions

**Comment by Fourjays** [comment]
@wingatex can you please verify if the problematic units are present in the test repository, and if they still indeed cause crashes on spawn.

**Comment by adios113** [comment]
The bug should be gone, since it was part of AIA.

**Comment by Ludvigroosen** [comment]
Checking if the issue is solved today.

**Comment by Ludvigroosen** [comment]
Checked on Live server and issue is fixed.
