### ISSUE TITLE
Arma's Nature

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#96]
**Description:**
How many times making a mission you just think "Yeah, that's nice, but some trees here and there would make it better"? 
Well, it happens a lot to me and some of my friends, so I decided to write some configs that will let you put down in the editor trees, plants, bushes and rocks, so you can change some ambient the way you like it more.
This little addon just use the models from Arma 3, so there shouldn't be big problems, the only annoying thing is that it's not just an editor update, so everyone who plays the mission must have it, not just the mission maker, but it's so little (18kb) that I hope it will not be a big problem for who decides to use it.

**Download:** http://www.armaholic.com/page.php?id=24184
**Size:** 1MB

**Comment by karlkarl93** [comment]
I didn't look very carefully but I think this probably doesn't work with Zeus.

**Comment by karlkarl93** [comment]
This mod works, but only in the editor, other than that it works perfectly and just as advertised.

**Comment by wingatex** [comment]
After trying this it is cool to use but no one in my opinion will ever use this and it can only be used in editor. I honestly think it is a waste of time and adds to an already huge list of objects you can place own. Not needed.

**Comment by Fourjays** [comment]
Been no updates to this since January 2014, BI thread is barren. Appears to be abandoned.

**Comment by adios113** [comment]
You can now place CUP objects, buildings, trees, bushes and so on in 3DEN which was not possible in 2d editor.

**Comment by Fourjays** [comment]
Rejected in meeting on 14/03/16 due to limited usefulness and lack of development.
