### ISSUE TITLE
CJTF101 Editor

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#98]
**Description:**
You can now acces to a lot of objects. Houses, misc items, ruins, Ghost hotel, HMS Proteus, etc ... !

**Download:** http://www.armaholic.com/page.php?id=20821
**Size:** 1MB

**Comment by ShiFoo** [comment]
It is only 1 MB but if it keeps the promise of enabling more stuff in the editor, it would be good to have it. Eventhough we do not make too many editor missions: e.g. in the editor you can't place lamps! This mod seems to enable that. We should consider it!

**Comment by TheGrandVizier** [comment]
Is there any possibility to add these objects, or some of them, to zeus?

**Comment by wingatex** [comment]
I see no issue in having this, adds a lot to the people who know how to use the editor. It is only for standard ARMA 3 object though. With the use of 3D editor this can be a very powerful tool. Does not work in zeus functionality, have to be on the editor.

**Comment by Fourjays** [comment]
Is this still relevant/functional with the 3D editor?

**Comment by Fourjays** [comment]
This looks like a pretty abandoned mod. No updated since July 2014, last comment is from someone saying it doesn't work with 3DEN.

**Comment by ShiFoo** [comment]
One major thing this mod enabled was placing lamps in the editor. I dont know if this now works with 3DEN. If so, we could reject this mod. I can check later.

**Comment by ShiFoo** [comment]
You can place lamps in the 3D editor. Even though they are switched off in the editor when you place them as "on", a preview of a short scenario shows, that the lamp is, in fact, on. Additionally, the incompatability to 3DEN kind of disqualifies it already.

**Comment by Fourjays** [comment]
Rejected in meeting on 14/03/16 due to limited usefulness and lack of development.
