### ISSUE TITLE
Static Line Parachutes

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#99]
**Description:**
Parachutes updated on github, this is a replacement of the Static Line mod. The reason it has an individual release is due to the fact that this will be branching out to more than just static line parachutes.

**Download:** http://www.armaholic.com/page.php?id=29552
**Size:** 15MB

**Comment by wingatex** [comment]
Needs to be tested on server as cant test with AI

**Comment by Fourjays** [comment]
Last release in September 2015. Sounded promising, but Github activity indicates no new development or responses to issues since the last release. BI thread seems to indicate developer may have abandoned his projects to assist with CUP.

**Comment by Fourjays** [comment]
We will be testing this on the test server in future.

**Comment by Fourjays** [comment]
We will attempt to test this as part of the tests for the next milestone.

**Comment by Fourjays** [comment]
Issue no longer relevant due to modpack reset.
